// 100% auto-generated by Source Genesys Core
// copyright © 2000-2026 Menphis - Sistemas Inteligentes
// This file is part of the Source Genesys project                     
// ReSharper disable once CheckNamespace
namespace MenphisSI.SG.GerAdv;
public partial class DBOperador
{
    public const string CadastroGuid = "911113d5-1c7b-4c9a-a4cc-30d09809b5a7";
    public const string PTabelaNome = "Operador";
    public const string CamposSqlX = " Operador.* ";
    public const string CampoCodigo = "operCodigo";
    public const string CampoNome = "operNome";
    public const string PTabelaPrefixo = "oper";
#pragma warning disable CA1822 // Mark members as static

    public string Prefixo => PTabelaPrefixo;
#pragma warning restore CA1822 // Mark members as static

}