// 100% auto-generated by Source Genesys WebApi Front & Back Creator
// copyright © 2000-2025 Menphis - Sistemas Inteligentes
// This file is part of the Source Genesys project                     
'use client';
import { useState, useEffect, useCallback, useRef, useMemo } from 'react';
import { IObjetosService } from '../Services/Objetos.service';
import { NotifySystemActions, subscribeToNotifications } from '@/app/tools/NotifySystem';
import { IObjetos } from '../Interfaces/interface.Objetos';
import { FilterObjetos } from '../Filters/Objetos';
import { isValidDate } from '@/app/tools/datetime';
import { ObjetosApi } from '../Apis/ApiObjetos';

export const useObjetosForm = (
  initialObjetos: IObjetos,
  dataService: IObjetosService
) => {
  const [data, setData] = useState<IObjetos>(initialObjetos);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleChange = useCallback((e: any) => {
    const { name, value, type, checked } = e.target;
    setData((prev) => ({
      ...prev,
      [name]: type === 'checkbox' ? checked : value,
    }));    
  }, []);

  const loadObjetos = useCallback(async (id: number) => {
    if (!id || id === 0) {
      setData(initialObjetos);
      return;
    }

    setLoading(true);
    setError(null);
    
    try {
      const dados = await dataService.fetchObjetosById(id);
      setData(dados);
    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : 'Erro ao carregar Objetos';
      setError(errorMessage);
      //console.log('Erro ao carregar Objetos');
    } finally {
      setLoading(false);
    }
  }, [dataService, initialObjetos]);

  const resetForm = useCallback(() => {
    setData(initialObjetos);
    setError(null);
  }, [initialObjetos]);

  const returnValue = useMemo(() => ({
    data,
    loading,
    error,
    handleChange,
    loadObjetos,
    resetForm,
    setData
  }), [data, loading, error, handleChange, loadObjetos, resetForm]);
  return returnValue;
};


export const useObjetosNotifications = (
  onUpdate?: (entity: any) => void,
  onDelete?: (entity: any) => void,
  onAdd?: (entity: any) => void
) => {
  const callbacksRef = useRef({ onUpdate, onDelete, onAdd });
  
  useEffect(() => {
    callbacksRef.current = { onUpdate, onDelete, onAdd };
  }, [onUpdate, onDelete, onAdd]);

  useEffect(() => {
    const unsubscribe = subscribeToNotifications('Objetos', (entity) => {
      try {
        const { onUpdate, onDelete, onAdd } = callbacksRef.current;
        
        switch (entity.action) {
          case NotifySystemActions.DELETE:
            onDelete?.(entity);
            break;
          case NotifySystemActions.UPDATE:
            onUpdate?.(entity);
            break;
          case NotifySystemActions.ADD:
            onAdd?.(entity);
            break;
        }
      } catch (err) {
        //console.log("Erro no listener de notificações.");
      }
    });

    return () => {
      unsubscribe();
    };
  }, []);
};


export const useObjetosList = (dataService: IObjetosService, currentFilter?: FilterObjetos | undefined | null) => {
  const [data, setData] = useState<IObjetos[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null); 
  const currentFilterRef = useRef<FilterObjetos | undefined | null>(currentFilter);

  useEffect(() => {
    currentFilterRef.current = currentFilter;
  }, [currentFilter]);

  const fetchData = useCallback(async (filtro?: FilterObjetos | undefined | null) => {
   
    setLoading(true);
    setError(null);
    
    try {
      const result = await dataService.getAll(filtro ?? {} as FilterObjetos);
      setData(result);
    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : 'Erro ao carregar objetos';
      setError(errorMessage);
      //console.log('Erro ao carregar objetos');
    } finally {
      setLoading(false);
    }
  }, [dataService]);   

 const refreshData = useCallback(() => {
     fetchData(currentFilterRef.current);
  }, [fetchData]);
  
  useObjetosNotifications(
    refreshData, // onUpdate
    refreshData, // onDelete  
    refreshData  // onAdd
  );
   

  return {
    data,
    loading,
    error,
    fetchData,
    refreshData
  };
};


export function useValidationsObjetos() {

  async function runValidation(data: IObjetos, uri?: string, token?: string): Promise<{ isValid: boolean; message: string } | null> {

    const objetosApi = new ObjetosApi(uri ?? '', token ?? '');

    const result = await objetosApi.validation(data);

    return result;
  }

  function validate(data: IObjetos): { isValid: boolean; message: string } {
    if (!data) return { isValid: false, message: 'Dados não informados.' };
    
      try {
   
        if (data.nome.length <= 0) { 
                                             return { isValid: false, message: 'O campo Nome não pode ficar vazio.' };
                                         } 
if (data.nome.length > 255) { 
                                             return { isValid: false, message: 'O campo Nome não pode ter mais de 255 caracteres.' };
                                         } 



        return { isValid: true, message: '' };

         } catch (error) {
          return { isValid: true, message: 'Erro ao validar os dados.' };
    }

  }

 return { validate, runValidation };
}export const useObjetosComboBox = (
  dataService: IObjetosService,
  initialValue?: any
) => {
  const [options, setOptions] = useState<any[]>([]);
  const [filteredOptions, setFilteredOptions] = useState<any[]>([]);
  const [loading, setLoading] = useState(false);
  const [selectedValue, setSelectedValue] = useState(initialValue);
  const [hasLoaded, setHasLoaded] = useState(false);

  const fetchOptions = useCallback(async () => {
    if (loading) return; // Evita múltiplas requisições simultâneas
    
    setLoading(true);
    try {
      const response = await dataService.getList();
      const mappedOptions = response.map(item => ({
        id: item.id,
        nome: item.nome
      }));
      setOptions(mappedOptions);
      setFilteredOptions(mappedOptions);
      setHasLoaded(true);
    } catch (err) {
      //console.log('Erro ao buscar opções do ComboBox');
    } finally {
      setLoading(false);
    }
  }, [dataService, loading]);

  const handleFilter = useCallback((filterText: string) => {
    if (!filterText) {
      setFilteredOptions(options);
      return;
    }
    
    const filter = filterText.toLowerCase();
    const filtered = options.filter(option =>
      option.nome.toLowerCase().includes(filter)
    );
    setFilteredOptions(filtered);
  }, [options]);

  const handleValueChange = useCallback((newValue: any) => {
    setSelectedValue(newValue);
  }, []);
  
  useEffect(() => {
    if (!hasLoaded) {
      fetchOptions();
    }
  }, [fetchOptions, hasLoaded]);

  const refreshCallback = useCallback(() => {
    if (hasLoaded) {
      fetchOptions();
    }
  }, [fetchOptions, hasLoaded]);

  useObjetosNotifications(
    refreshCallback, // onUpdate
    refreshCallback, // onDelete
    refreshCallback  // onAdd
  );

  return {
    options: filteredOptions,
    loading,
    selectedValue,
    handleFilter,
    handleValueChange,
    refreshOptions: fetchOptions,
    clearValue: () => setSelectedValue(null)
  };
};