// 100% auto-generated by Source Genesys WebApi Front & Back Creator
// copyright © 2000-2026 Menphis - Sistemas Inteligentes
// This file is part of the Source Genesys project                     
import { useState } from 'react';
import InputInput from '@/app/components/Inputs/InputInput';
import InputDate from '@/app/components/Inputs/InputDate';
import InputHora from '@/app/components/Inputs/InputHora';
import InputValor from '@/app/components/Inputs/InputValor';
import InputComboFilterYesNo from '@/app/components/Inputs/InputComboFilterYesNo';
import { FilterHandlers } from '@/app/components/Cruds/GenericFilterDialog';
import { FilterTribunal } from '@/app/GerAdv_TS/Tribunal/Filters/Tribunal';
import FilterDialogButton from '@/app/components/Cruds/FilterDialogButton';
import {useAreaFilter} from '@/app/GerAdv_TS/Area/Hooks/hookAreaFilter';
import {useJusticaFilter} from '@/app/GerAdv_TS/Justica/Hooks/hookJusticaFilter';
import {useInstanciaFilter} from '@/app/GerAdv_TS/Instancia/Hooks/hookInstanciaFilter';
import AreaComboBox from '@/app/GerAdv_TS/Area/ComboBox/Area';
import JusticaComboBox from '@/app/GerAdv_TS/Justica/ComboBox/Justica';
import InstanciaComboBox from '@/app/GerAdv_TS/Instancia/ComboBox/Instancia';
import InputGuid from '@/app/components/Inputs/InputGuid'


interface UseTribunalFilterProps {
    handleFetchWithFilter: (filtro?: FilterTribunal | undefined | null) => Promise<void>;
}

interface UseTribunalFilterReturn {
    // Estados
    showSearch: boolean;
    windowFilter: FilterTribunal;
    setWindowFilter: React.Dispatch<React.SetStateAction<FilterTribunal>>;

    // Handlers do Dialog
    handleSearch: () => void;
    handleCloseSearch: () => void;
    handleConfirmSearch: (filter: FilterTribunal) => Promise<void>;

    // Render function
    renderInputFilters: (handlers: FilterHandlers<FilterTribunal>) => React.ReactNode;

    // Utilitários
    clearFilter: () => void;
    hasActiveFilter: boolean;
}

export const useTribunalFilter = ({ handleFetchWithFilter }: UseTribunalFilterProps): UseTribunalFilterReturn => {
    const [showSearch, setShowSearch] = useState(false);
    const [windowFilter, setWindowFilter] = useState<FilterTribunal>({} as FilterTribunal);

    // Handlers do Dialog
    const handleSearch = () => {
        setShowSearch(true);
        const filterWildechar = {...windowFilter, wildcardChar: '%' } as FilterTribunal;
        setWindowFilter(filterWildechar);
    };

    const handleCloseSearch = () => {
        setShowSearch(false);
    };

    const handleConfirmSearch = async (filter: FilterTribunal) => {
        await handleFetchWithFilter(filter);
    };

    // Função para limpar filtros
    const clearFilter = () => {
        setWindowFilter({} as FilterTribunal);
        sessionStorage.removeItem(btoa('TribunalFilter'));
        handleFetchWithFilter({} as FilterTribunal);
    };

    // Verificar se há filtros ativos
    const hasActiveFilter = Object.values(windowFilter).some(value =>
        value !== undefined && value !== null && value !== '' && value !== -2147483648
    );

    // Função para renderizar os campos de filtro
    const renderInputFilters = (handlers: FilterHandlers<FilterTribunal>) => (        
        <>
        <InputInput
                        type='text'
                        id='nome'
                        name='nome'
                        value={handlers.windowFilter?.nome ?? ''}
                         onChange={handlers.handleInputChange}
                        placeholder='Informe Nome'
                        label='Nome'
                        className='input-default-main inputSearch'
                        />
<AreaComboBox
                name='area'
                dataForm={null}
                value={handlers.windowFilter?.area}
                setValue={(e:any) => handlers.handleComboChange(e, 'area')}
                className='inputSearch inputSearchComboboxTab'
                label='Área'
            />
<JusticaComboBox
                name='justica'
                dataForm={null}
                value={handlers.windowFilter?.justica}
                setValue={(e:any) => handlers.handleComboChange(e, 'justica')}
                className='inputSearch inputSearchComboboxTab'
                label='Justiça'
            />
<InputInput
                        type='text'
                        id='descricao'
                        name='descricao'
                        value={handlers.windowFilter?.descricao ?? ''}
                         onChange={handlers.handleInputChange}
                        placeholder='Informe Descrição'
                        label='Descrição'
                        className='input-default-main inputSearch'
                        />
<InstanciaComboBox
                name='instancia'
                dataForm={null}
                value={handlers.windowFilter?.instancia}
                setValue={(e:any) => handlers.handleComboChange(e, 'instancia')}
                className='inputSearch inputSearchComboboxTab'
                label='Instancia'
            />
<InputInput
                        type='text'
                        id='sigla'
                        name='sigla'
                        value={handlers.windowFilter?.sigla ?? ''}
                         onChange={handlers.handleInputChange}
                        placeholder='Informe Sigla'
                        label='Sigla'
                        className='input-default-main inputSearch'
                        />
<InputInput
                        type='text'
                        id='web'
                        name='web'
                        value={handlers.windowFilter?.web ?? ''}
                         onChange={handlers.handleInputChange}
                        placeholder='Informe Web'
                        label='Web'
                        className='input-default-main inputSearch'
                        />
<InputInput
                type='text'
                id='quemcad'
                name='quemcad'
                value={handlers.windowFilter?.quemcad ?? ''}
                onChange={handlers.handleInputChange}
                placeholder='Informe Usuário de Cadastro'
                label='Usuário de Cadastro (igual ou inicial)'
                className='input-default-main inputSearch'
                />
<InputInput
                type='text'
                id='quemcad_end'
                name='quemcad_end'
                value={handlers.windowFilter?.quemcad_end ?? ''}
                onChange={handlers.handleInputChange}
                placeholder='Informe Usuário de Cadastro final'
                label='Usuário de Cadastro final'
                disabled={handlers.windowFilter?.quemcad ? false : true}
                className='input-default-main inputSearch'
                />
<InputDate
                type='text'
                id='dtcad'
                label='Data de Cadastro (igual ou início)'
                dataForm={null}
                className='inputSearch'
                name='dtcad'
                value={handlers.windowFilter?.dtcad ?? ''}                
                onChange={(value: string) => handlers.handleDateChange('dtcad', value)}
            />
<InputDate
                type='text'
                id='dtcad_end'
                label='Data de Cadastro (final)'
                dataForm={null}
                className='inputSearch'
                name='dtcad_end'
                value={handlers.windowFilter?.dtcad_end ?? ''}
                disabled={handlers.windowFilter?.dtcad ? false : true}
                onChange={(value: string) => handlers.handleDateChange('dtcad_end', value)}
            />
<InputInput
                type='text'
                id='quematu'
                name='quematu'
                value={handlers.windowFilter?.quematu ?? ''}
                onChange={handlers.handleInputChange}
                placeholder='Informe Usuário de Atualização'
                label='Usuário de Atualização (igual ou inicial)'
                className='input-default-main inputSearch'
                />
<InputInput
                type='text'
                id='quematu_end'
                name='quematu_end'
                value={handlers.windowFilter?.quematu_end ?? ''}
                onChange={handlers.handleInputChange}
                placeholder='Informe Usuário de Atualização final'
                label='Usuário de Atualização final'
                disabled={handlers.windowFilter?.quematu ? false : true}
                className='input-default-main inputSearch'
                />
<InputDate
                type='text'
                id='dtatu'
                label='Data de Atualização (igual ou início)'
                dataForm={null}
                className='inputSearch'
                name='dtatu'
                value={handlers.windowFilter?.dtatu ?? ''}                
                onChange={(value: string) => handlers.handleDateChange('dtatu', value)}
            />
<InputDate
                type='text'
                id='dtatu_end'
                label='Data de Atualização (final)'
                dataForm={null}
                className='inputSearch'
                name='dtatu_end'
                value={handlers.windowFilter?.dtatu_end ?? ''}
                disabled={handlers.windowFilter?.dtatu ? false : true}
                onChange={(value: string) => handlers.handleDateChange('dtatu_end', value)}
            />
<InputComboFilterYesNo
                type='text'
                id='visto'
                name='visto'
                value={handlers.windowFilter?.visto ?? -2147483648}
                onChange={handlers.handleInputChange} 
                label='Visto'
                className='inputSearch inputSearchCheckbox'
                />
<InputGuid
                        type='text'
                        id='guid'
                        name='guid'
                        value={handlers.windowFilter?.guid ?? ''}
                         onChange={(value: string) =>
                      handlers.handleInputChange({ target: { name: 'guid', value } } as any)
                    }
                        placeholder='Informe Guid'
                        label='Guid'
                        className='input-default-main inputSearch'
                        />
<FilterDialogButton        
        filter={handlers.windowFilter.filterArea ?? ({} as any) as any}
        setFilter={(f: any) =>
          handlers.setWindowFilter((prev) => ({ ...prev, filterArea: f }))
        }        
        onConfirm={async (f: any) => {          
        }}
        title='Filtrar Área'
        buttonText='Área'
        renderInputFilters={renderAreaInputs}
      />
<FilterDialogButton        
        filter={handlers.windowFilter.filterJustica ?? ({} as any) as any}
        setFilter={(f: any) =>
          handlers.setWindowFilter((prev) => ({ ...prev, filterJustica: f }))
        }        
        onConfirm={async (f: any) => {          
        }}
        title='Filtrar Justiça'
        buttonText='Justiça'
        renderInputFilters={renderJusticaInputs}
      />
<FilterDialogButton        
        filter={handlers.windowFilter.filterInstancia ?? ({} as any) as any}
        setFilter={(f: any) =>
          handlers.setWindowFilter((prev) => ({ ...prev, filterInstancia: f }))
        }        
        onConfirm={async (f: any) => {          
        }}
        title='Filtrar Instancia'
        buttonText='Instancia'
        renderInputFilters={renderInstanciaInputs}
      />

<InputInput
                type='text'
                id='codigo_filtro'
                name='codigo_filtro'
                value={handlers.windowFilter?.codigo_filtro ?? ''}
                onChange={handlers.handleInputChange}
                dataForm={handlers.windowFilter}
                placeholder='Código do cadastro'
                label='Código (igual ou inicial)'
                className='input-default-main inputSearch'
                />
<InputInput
                type='text'
                id='codigo_filtro_end'
                name='codigo_filtro_end'
                value={handlers.windowFilter?.codigo_filtro_end ?? ''}
                onChange={handlers.handleInputChange}
                dataForm={handlers.windowFilter}
                placeholder='Código final do cadastro'
                label='Código final'
                disabled={handlers.windowFilter?.codigo_filtro ? false : true}
                className='input-default-main inputSearch'
                />

        </>        
    );


    const { renderInputFilters: renderAreaInputs } = useAreaFilter({
    handleFetchWithFilter: async () => {},
  });
const { renderInputFilters: renderJusticaInputs } = useJusticaFilter({
    handleFetchWithFilter: async () => {},
  });
const { renderInputFilters: renderInstanciaInputs } = useInstanciaFilter({
    handleFetchWithFilter: async () => {},
  });



    return {
        // Estados
        showSearch,
        windowFilter,
        setWindowFilter,

        // Handlers
        handleSearch,
        handleCloseSearch,
        handleConfirmSearch,

        // Render function
        renderInputFilters,

        // Utilitários
        clearFilter,
        hasActiveFilter
    };
};