// 100% auto-generated by Source Genesys WebApi Front & Back Creator
// copyright © 2000-2026 Menphis - Sistemas Inteligentes
// This file is part of the Source Genesys project
// Fonte:ReadersGenerator
namespace MenphisSI.GerAdv.Readers;
public partial class ObjetosReader(IFObjetosFactory objetosFactory) : IObjetosReader
{
    private readonly IFObjetosFactory _objetosFactory = objetosFactory ?? throw new ArgumentNullException();
    public async Task<IEnumerable<DBNomeID>?> ListarNAsync(int max, string uri, string cWhere, List<SqlParameter>? parameters, string order) => await DevourerSqlData.ListarNomeID(BuildSqlQuery("ojtCodigo, ojtNome", cWhere, order, max), parameters, uri, caching: false, max: max);
    public async Task<IEnumerable<ObjetosResponseAll>> ListarAsync(MsiSqlConnection oCnn, int max, string uri, string cWhere, List<SqlParameter>? parameters, string order, CancellationToken cancellationToken)
    {
        var stopwatch = ObjetosDatabaseMetrics.StartTimer();
        var connStopwatch = ObjetosDatabaseMetrics.StartTimer();
        try
        {
            ObjetosDatabaseMetrics.IncrementActiveConnections("ListarAsync", oCnn?.Uri);
            ObjetosDatabaseMetrics.RecordConnectionOpen("ListarAsync", oCnn?.Uri, connStopwatch);
            var result = await ListarTabelaAsync(oCnn, BuildSqlQuery(DBObjetos.CamposSqlX, cWhere, order, max), parameters, uri, caching: false, max: max, cancellationToken: cancellationToken);
            ObjetosDatabaseMetrics.RecordSqlQuery("ListarAsync", "SELECT", oCnn?.Uri, stopwatch, result.Count());
            return result;
        }
        catch (SqlException)
        {
            ObjetosDatabaseMetrics.RecordDatabaseError("ListarAsync", "SqlException", oCnn?.Uri);
            throw;
        }
        catch (TimeoutException)
        {
            ObjetosDatabaseMetrics.RecordDatabaseError("ListarAsync", "Timeout", oCnn?.Uri);
            throw;
        }
        finally
        {
            ObjetosDatabaseMetrics.DecrementActiveConnections("ListarAsync", oCnn?.Uri);
        }
    }

    private async Task<IEnumerable<ObjetosResponseAll>> ListarTabelaAsync(MsiSqlConnection? oCnn, string sql, List<SqlParameter>? parameters, string uri, bool caching = false, int max = 200, CancellationToken cancellationToken = default)
    {
        var stopwatch = ObjetosDatabaseMetrics.StartTimer();
        var result = new List<ObjetosResponseAll>(max);
        try
        {
            await using var cmd = new SqlCommand(cmdText: ConfiguracoesDBT.CmdSql(sql), connection: oCnn?.InnerConnection)
            {
                CommandTimeout = 120
            };
            if (parameters != null && parameters.Count > 0)
                foreach (var param in parameters)
                {
                    if (!cmd.Parameters.Contains(param.ParameterName))
                    {
                        var newParam = new SqlParameter(param.ParameterName, param.Value)
                        {
                            SqlDbType = param.SqlDbType,
                            Direction = param.Direction,
                            Size = param.Size,
                            Precision = param.Precision,
                            Scale = param.Scale
                        };
                        cmd.Parameters.Add(newParam);
                    }
                }

            await using var reader = await cmd.ExecuteReaderAsync(CommandBehavior.Default, cancellationToken);
            while (await reader.ReadAsync(cancellationToken))
            {
                if (cancellationToken.IsCancellationRequested)
                    return result;
                result.Add(ReadAll(_objetosFactory.CreateFromReader(reader), reader)!);
            }

            ObjetosDatabaseMetrics.RecordSqlQuery("ListarTabelaAsync", "SELECT", oCnn?.Uri, stopwatch, result.Count);
            return result;
        }
        catch (SqlException)
        {
            ObjetosDatabaseMetrics.RecordDatabaseError("ListarTabelaAsync", "SqlException", oCnn?.Uri);
            throw;
        }
        catch (TimeoutException)
        {
            ObjetosDatabaseMetrics.RecordDatabaseError("ListarTabelaAsync", "Timeout", oCnn?.Uri);
            throw;
        }
    }

    public async Task<ObjetosResponse?> ReadAsync(int id, MsiSqlConnection? oCnn)
    {
        var stopwatch = ObjetosDatabaseMetrics.StartTimer();
        try
        {
            ObjetosDatabaseMetrics.IncrementActiveConnections("ReadAsync", oCnn?.Uri);
            using var dbRec = await _objetosFactory.CreateFromIdAsync(id, oCnn);
            var result = dbRec == null || dbRec.ID.IsEmptyIDNumber() ? null : Read(dbRec);
            ObjetosDatabaseMetrics.RecordSqlQuery("ReadAsync", "SELECT", oCnn?.Uri, stopwatch, result != null ? 1 : 0);
            return result;
        }
        catch (SqlException)
        {
            ObjetosDatabaseMetrics.RecordDatabaseError("ReadAsync", "SqlException", oCnn?.Uri);
            throw;
        }
        catch (TimeoutException)
        {
            ObjetosDatabaseMetrics.RecordDatabaseError("ReadAsync", "Timeout", oCnn?.Uri);
            throw;
        }
        finally
        {
        // Ignore
        }
    }

    public async Task<Models.Objetos?> ReadMAsync(int id, MsiSqlConnection? oCnn)
    {
        using var dbRec = await _objetosFactory.CreateFromIdAsync(id, oCnn);
        var objetos = new Models.Objetos
        {
            Id = dbRec.ID,
            Justica = dbRec.FJustica,
            Area = dbRec.FArea,
            Nome = dbRec.FNome ?? string.Empty,
            Bold = dbRec.FBold,
            Guid = dbRec.FGuid ?? string.Empty,
        };
        return objetos;
    }

    public ObjetosResponse? Read(FObjetos dbRec, MsiSqlConnection? oCnn)
    {
        return Read(dbRec);
    }

    public ObjetosResponse? Read(string where, List<SqlParameter>? parameters, MsiSqlConnection? oCnn)
    {
        using var dbRec = _objetosFactory.CreateFromParameters(parameters, oCnn, sqlWhere: where);
        return dbRec is null || dbRec.ID.IsEmptyIDNumber() ? null : Read(dbRec);
    }

    public ObjetosResponse? Read(FObjetos dbRec) // Track 001.16072025
    {
        if (dbRec == null)
        {
            return null;
        }

        var objetos = new ObjetosResponse
        {
            Id = dbRec.ID,
            Justica = dbRec.FJustica,
            Area = dbRec.FArea,
            Nome = dbRec.FNome ?? string.Empty,
            Bold = dbRec.FBold,
            Guid = dbRec.FGuid ?? string.Empty,
        };
        return objetos;
    }

    public ObjetosResponse? Read(SG.GerAdv.DBObjetos dbRec) // Track 002.16072025
    {
        if (dbRec == null)
        {
            return null;
        }

        var objetos = new ObjetosResponse
        {
            Id = dbRec.ID,
            Justica = dbRec.FJustica,
            Area = dbRec.FArea,
            Nome = dbRec.FNome ?? string.Empty,
            Bold = dbRec.FBold,
            Guid = dbRec.FGuid ?? string.Empty,
        };
        return objetos;
    }

    public ObjetosResponseAll? ReadAll(FObjetos dbRec, IDataRecord dr)
    {
        if (dbRec == null)
        {
            return null;
        }

        var objetos = new ObjetosResponseAll
        {
            Id = dbRec.ID,
            Justica = dbRec.FJustica,
            Area = dbRec.FArea,
            Nome = dbRec.FNome ?? string.Empty,
            Bold = dbRec.FBold,
            Guid = dbRec.FGuid ?? string.Empty,
        };
        try
        {
            objetos.NomeJustica = dr[DBJusticaDicInfo.CampoNome]?.ToString() ?? string.Empty;
        }
        catch
        {
        }

        try
        {
            objetos.DescricaoArea = dr[DBAreaDicInfo.CampoNome]?.ToString() ?? string.Empty;
        }
        catch
        {
        }

        return objetos;
    }

    public ObjetosResponseAll? ReadAll(SG.GerAdv.DBObjetos dbRec, DataRow dr)
    {
        if (dbRec == null)
        {
            return null;
        }

        var objetos = new ObjetosResponseAll
        {
            Id = dbRec.ID,
            Justica = dbRec.FJustica,
            Area = dbRec.FArea,
            Nome = dbRec.FNome ?? string.Empty,
            Bold = dbRec.FBold,
            Guid = dbRec.FGuid ?? string.Empty,
        };
        try
        {
            objetos.NomeJustica = dr[DBJusticaDicInfo.CampoNome]?.ToString() ?? string.Empty;
        }
        catch
        {
        }

        try
        {
            objetos.DescricaoArea = dr[DBAreaDicInfo.CampoNome]?.ToString() ?? string.Empty;
        }
        catch
        {
        }

        return objetos;
    }
}