// 100% auto-generated by Source Genesys WebApi Front & Back Creator
                     // copyright © 2000-2025 Menphis - Sistemas Inteligentes
                     // This file is part of the Source Genesys project                     
                    export enum FieldsProObservacoes
{	processo = `Processo`,
	nome = `Nome`,
	observacoes = `Observacoes`,
	data = `Data`,
	guid = `GUID`,
}
