// 100% auto-generated by Source Genesys WebApi Front & Back Creator
// copyright © 2000-2025 Menphis - Sistemas Inteligentes
// This file is part of the Source Genesys project                     
#pragma warning disable IDE0130 // Namespace does not match folder structure

namespace MenphisSI.GerAdv.Models
{
#pragma warning restore IDE0130 // Namespace does not match folder structure

    [Serializable]
    public record ProDepositos
    {
        [JsonPropertyName("id")]
        public int Id { get; set; }

        /// <summary>
        /// Fase - pdsFase  
        /// </summary>
        [JsonPropertyName("fase")]
        public int Fase { get; set; }

        /// <summary>
        /// TipoProDesposito - pdsTipoProDesposito  
        /// </summary>
        [JsonPropertyName("tipoprodesposito")]
        public int TipoProDesposito { get; set; }

        /// <summary>
        /// Processo - pdsProcesso  
        /// </summary>
        [JsonPropertyName("processo")]
        public int Processo { get; set; }

        /// <summary>
        /// Data - pdsData  
        /// </summary>
        [JsonPropertyName("data")]
        public string Data { get; set; } = "";

        /// <summary>
        /// Valor - pdsValor  
        /// </summary>
        [JsonPropertyName("valor")]
        public decimal Valor { get; set; }
    }
}

namespace MenphisSI.GerAdv.Models.All
{
    [Serializable]
    public record ProDepositosAll
    {
        [JsonPropertyName("id")]
        public int Id { get; set; }

        /// <summary>
        /// Fase - pdsFase  
        /// </summary>
        [JsonPropertyName("fase")]
        public int Fase { get; set; }

        /// <summary>
        /// TipoProDesposito - pdsTipoProDesposito  
        /// </summary>
        [JsonPropertyName("tipoprodesposito")]
        public int TipoProDesposito { get; set; }

        /// <summary>
        /// Processo - pdsProcesso  
        /// </summary>
        [JsonPropertyName("processo")]
        public int Processo { get; set; }

        /// <summary>
        /// Data - pdsData  
        /// </summary>
        [JsonPropertyName("data")]
        public string Data { get; set; } = "";

        /// <summary>
        /// Valor - pdsValor  
        /// </summary>
        [JsonPropertyName("valor")]
        public decimal Valor { get; set; }

        [JsonPropertyName("descricaofase")]
        public string DescricaoFase { get; set; } = string.Empty;

        [JsonPropertyName("nometipoprodesposito")]
        public string NomeTipoProDesposito { get; set; } = string.Empty;
    }
}