global using MenphisSI.GerMDS.DicInfo;
global using MenphisSI.GerMDS.Interface;
global using MenphisSI.GerMDS.Models;
global using MenphisSI.GerMDS.Models.Response;
global using MenphisSI.GerMDS.Services;
global using MenphisSI.GerMDS.Validations;
global using MenphisSI.GerMDS.Writers;
global using MenphisSI.GerMDS.Readers;
global using MenphisSI.GerMDS;