// 100% auto-generated by Source Genesys WebApi Front & Back Creator
// copyright © 2000-2026 Menphis - Sistemas Inteligentes
// This file is part of the Source Genesys project
// Tabela:Penhora
// Fonte:ServiceGenerator
namespace MenphisSI.GerAdv.Services;
public partial class PenhoraService(IOptions<AppSettings> appSettings, IFPenhoraFactory penhoraFactory, IPenhoraReader reader, IPenhoraValidation validation, IPenhoraWriter writer, IPenhoraStatusReader penhorastatusReader, IHttpContextAccessor httpContextAccessor, IHybridCache cache, IMemoryCache memory, IConnectionService connectionService, IGenericVoiceFilterService<Filters.FilterPenhora> voiceFilterService, IServicesFilter serviceFilter, IEntityService entityService) : IPenhoraService, IDisposable
{
    private readonly IHttpContextAccessor _httpContextAccessor = httpContextAccessor;
    private readonly IOptions<AppSettings> _appSettings = appSettings;
    private readonly IHybridCache _cache = cache;
    private readonly IMemoryCache _memoryCache = memory ?? throw new ArgumentNullException(nameof(memory));
    private readonly IConnectionService _connectionService = connectionService ?? throw new ArgumentNullException(nameof(connectionService));
    private readonly IGenericVoiceFilterService<Filters.FilterPenhora> _voiceFilterService = voiceFilterService ?? throw new ArgumentNullException(nameof(voiceFilterService));
    private readonly IServicesFilter servicesFilter = serviceFilter ?? throw new ArgumentNullException(nameof(serviceFilter));
    private bool _disposed;
    private readonly IEntityService _entityService = entityService;
    private readonly IFPenhoraFactory penhoraFactory = penhoraFactory;
    private readonly IPenhoraReader reader = reader;
    private readonly IPenhoraValidation validation = validation;
    private readonly IPenhoraWriter writer = writer;
    private readonly IPenhoraStatusReader penhorastatusReader = penhorastatusReader;
    public async Task<IEnumerable<PenhoraResponseAll>> Filter([FromQuery] int max, [FromBody] Filters.FilterPenhora filtro, [FromRoute, Required] string uri)
    {
        ThrowIfDisposed();
        if (!(await Uris.ValidaUriAsync(uri, _entityService)))
        {
            throw new Exception("Penhora: URI inválida");
        }

        if (max <= 0)
        {
            max = BaseConsts.PMaxItens;
        }

        var connectionStopwatch = PenhoraDatabaseMetrics.StartTimer();
        try
        {
            var filtroResult = filtro == null ? null : servicesFilter.WFiltroPenhora(filtro!);
            string where = filtroResult?.where ?? string.Empty;
            List<SqlParameter>? parameters = filtroResult?.parametros ?? [];
            var filterHash = GenericVoiceFilterService<Filters.FilterPenhora>.GetFilterHash(filtro);
            using var scope = _connectionService.CreateConnectionScope(uri);
            using var oCnn = scope.Connection ?? throw new DatabaseConnectionException();
            PenhoraDatabaseMetrics.RecordConnectionOpen("Filter", uri, connectionStopwatch);
            var keyCache = await reader.ReadStringAuditorAsync(uri, oCnn, _cache);
            var cacheKey = $"{uri}-{max}Penhora-Filter-{where.GetHashCode2()}{filterHash}{keyCache}";
            var entryOptions = new HybridCacheEntryOptions
            {
                Expiration = TimeSpan.FromSeconds(BaseConsts.PMaxGetListSecondsCacheId),
                LocalCacheExpiration = TimeSpan.FromSeconds(BaseConsts.PMaxGetListSecondsCacheId)
            };
            var result = await _cache.GetOrCreateAsync(cacheKey, async cancel => await GetDataAllAsync(oCnn, max, string.IsNullOrEmpty(where) ? string.Empty : TSql.Where + where, parameters, uri, cancel), entryOptions, cancellationToken: CancellationToken.None);
            return result;
        }
        catch (SqlException ex)
        {
            PenhoraDatabaseMetrics.RecordDatabaseError("Filter", "SqlException", uri);
            throw new Exception($"Penhora - SQL error on filtering {ex.Message}.");
        }
        catch (TimeoutException ex)
        {
            PenhoraDatabaseMetrics.RecordDatabaseError("Filter", "Timeout", uri);
            throw new Exception($"Penhora - timeout on filtering {ex.Message}.");
        }
        catch (Exception ex)
        {
            throw new Exception($"Penhora - error on filtering {ex.Message}.");
        }
    }

    public async Task<Filters.FilterPenhora> FilterVoice([FromBody] Filters.FilterPenhora filtro, [FromBody] CommandSpeakerRequest? message, [FromRoute, Required] string uri)
    {
        ThrowIfDisposed();
        if (!(await Uris.ValidaUriAsync(uri, _entityService)))
        {
            throw new Exception("Penhora: URI inválida");
        }

        try
        {
            // Se há mensagem de comando de voz, processar via OpenAI
            Filters.FilterPenhora? filtroProcessado = filtro;
            if (message != null && !string.IsNullOrWhiteSpace(message.Message))
            {
                filtro = filtro ?? new Filters.FilterPenhora();
                filtroProcessado = await ProcessFilterVoiceCommandAsync(message, filtro, uri);
            }

            return filtroProcessado ?? new Filters.FilterPenhora();
        }
        catch (Exception ex)
        {
            throw new Exception($"Penhora - error on creating filter voice: {ex.Message}.");
        }
    }

    public async Task<PenhoraResponse?> GetById([FromQuery] int id, [FromRoute, Required] string uri, CancellationToken token)
    {
        ThrowIfDisposed();
        if (id < 1)
        {
            return new PenhoraResponse();
        }

        var connectionStopwatch = PenhoraDatabaseMetrics.StartTimer();
        var queryStopwatch = PenhoraDatabaseMetrics.StartTimer();
        var entryOptions = new HybridCacheEntryOptions
        {
            Expiration = TimeSpan.FromSeconds(BaseConsts.PMaxSecondsCacheId),
            LocalCacheExpiration = TimeSpan.FromSeconds(BaseConsts.PMaxSecondsCacheId)
        };
        using var scope = _connectionService.CreateConnectionScope(uri);
        using var oCnn = scope.Connection ?? throw new DatabaseConnectionException();
        try
        {
            PenhoraDatabaseMetrics.RecordConnectionOpen("GetById", uri, connectionStopwatch);
            PenhoraDatabaseMetrics.IncrementActiveConnections("GetById", uri);
            var keyCache = await reader.ReadStringAuditorAsync(id, uri, oCnn);
            var result = await _cache.GetOrCreateAsync($"{uri}-Penhora-GetById-{id}--{keyCache}", async cancel =>
            {
                var data = await GetDataByIdAsync(id, oCnn, cancel);
                PenhoraDatabaseMetrics.RecordSqlQuery("GetById", "SELECT", uri, queryStopwatch, data != null ? 1 : 0);
                return data;
            }, entryOptions, cancellationToken: token);
            PenhoraDatabaseMetrics.DecrementActiveConnections("GetById", uri);
            return result;
        }
        catch (SqlException ex)
        {
            PenhoraDatabaseMetrics.RecordDatabaseError("GetById", "SqlException", uri);
            PenhoraDatabaseMetrics.DecrementActiveConnections("GetById", uri);
            throw new Exception($"Penhora - SQL error on GetById: {ex.Message}");
        }
        catch (TimeoutException ex)
        {
            PenhoraDatabaseMetrics.RecordDatabaseError("GetById", "Timeout", uri);
            PenhoraDatabaseMetrics.DecrementActiveConnections("GetById", uri);
            throw new Exception($"Penhora - timeout on GetById: {ex.Message}");
        }
        catch (Exception)
        {
            PenhoraDatabaseMetrics.DecrementActiveConnections("GetById", uri);
            throw new Exception($"Penhora - {uri}-: GetById");
        }
    }

    private async Task<PenhoraResponse?> GetDataByIdAsync(int id, MsiSqlConnection? oCnn, CancellationToken token) => await reader.ReadAsync(id, oCnn);
    public async Task<AuditorResponse?> GetAuditor([FromQuery] int id, [FromRoute, Required] string uri, CancellationToken token)
    {
        ThrowIfDisposed();
        AuditorResponse? result = null;
        if (id < 1)
        {
            return result;
        }

        using var scope = _connectionService.CreateConnectionScope(uri);
        using var oCnn = scope.Connection ?? throw new DatabaseConnectionException();
        try
        {
            result = await reader.ReadAuditorAsync(id, uri, oCnn);
            return result;
        }
        catch (Exception)
        {
            throw new Exception($"Penhora - {uri}-: GetAuditor");
        }
    }

    public async Task<PenhoraResponse?> AddAndUpdate([FromBody] Models.Penhora? regPenhora, [FromRoute, Required] string uri)
    {
        ThrowIfDisposed();
        if (regPenhora == null)
        {
            return null;
        }

        if (!(await Uris.ValidaUriAsync(uri, _entityService)))
        {
            throw new Exception("Penhora: URI inválida");
        }

        var connectionStopwatch = PenhoraDatabaseMetrics.StartTimer();
        var queryStopwatch = PenhoraDatabaseMetrics.StartTimer();
        using var scope = _connectionService.CreateConnectionScopeRw(uri);
        using var oCnn = scope.Connection ?? throw new DatabaseConnectionException();
        if (oCnn == null)
        {
            return null;
        }

        try
        {
            PenhoraDatabaseMetrics.RecordConnectionOpen("AddAndUpdate", uri, connectionStopwatch);
            PenhoraDatabaseMetrics.IncrementActiveConnections("AddAndUpdate", uri);
            var validade = await validation.ValidateReg(regPenhora, this, penhorastatusReader, uri, oCnn);
            if (!validade)
            {
                throw new Exception("Erro inesperado ao validar 0x0!");
            }
        }
        catch (SGValidationException ex)
        {
            PenhoraDatabaseMetrics.DecrementActiveConnections("AddAndUpdate", uri);
            throw new Exception(ex.Message);
        }
        catch (Exception)
        {
            PenhoraDatabaseMetrics.DecrementActiveConnections("AddAndUpdate", uri);
            throw new Exception("Erro inesperado ao validar 0x1!");
        }

        int operadorId = UserTools.GetAuthenticatedUserId(_httpContextAccessor);
        try
        {
            using var saved = await writer.WriteAsync(regPenhora, operadorId, oCnn);
            string tipoQuery = regPenhora.Id.IsEmptyIDNumber() ? "INSERT" : "UPDATE";
            PenhoraDatabaseMetrics.RecordSqlQuery("AddAndUpdate", tipoQuery, uri, queryStopwatch, 1);
            var result = reader.Read(saved, oCnn);
            PenhoraDatabaseMetrics.DecrementActiveConnections("AddAndUpdate", uri);
            return result;
        }
        catch (Exception)
        {
            PenhoraDatabaseMetrics.RecordDatabaseError("AddAndUpdate", "SqlException", uri);
            PenhoraDatabaseMetrics.DecrementActiveConnections("AddAndUpdate", uri);
            throw;
        }
    }

    public async Task<PenhoraResponse?> Validation([FromBody] Models.Penhora? regPenhora, [FromRoute, Required] string uri)
    {
        ThrowIfDisposed();
        if (regPenhora == null)
        {
            return null;
        }

        if (!(await Uris.ValidaUriAsync(uri, _entityService)))
        {
            throw new Exception("Penhora: URI inválida");
        }

        var connectionStopwatch = PenhoraDatabaseMetrics.StartTimer();
        var queryStopwatch = PenhoraDatabaseMetrics.StartTimer();
        using var scope = _connectionService.CreateConnectionScopeRw(uri);
        using var oCnn = scope.Connection ?? throw new DatabaseConnectionException();
        if (oCnn == null)
        {
            return null;
        }

        try
        {
            PenhoraDatabaseMetrics.RecordConnectionOpen("Validation", uri, connectionStopwatch);
            PenhoraDatabaseMetrics.IncrementActiveConnections("Validation", uri);
            var validade = await validation.ValidateReg(regPenhora, this, penhorastatusReader, uri, oCnn);
            if (!validade)
            {
                throw new Exception("Erro inesperado ao validar 0x0!");
            }
        }
        catch (SGValidationException ex)
        {
            PenhoraDatabaseMetrics.DecrementActiveConnections("Validation", uri);
            throw new Exception(ex.Message);
        }
        catch (Exception)
        {
            PenhoraDatabaseMetrics.DecrementActiveConnections("Validation", uri);
            throw new Exception("Erro inesperado ao validar 0x1!");
        }

        if (regPenhora.Id.IsEmptyIDNumber())
        {
            return new PenhoraResponse();
        }

        return await reader.ReadAsync(regPenhora.Id, oCnn);
    }

    public async Task<PenhoraResponse?> Delete([FromQuery] int? id, [FromRoute, Required] string uri)
    {
        if (id == null || id.IsEmptyIDNumber())
        {
            return null;
        }

        ThrowIfDisposed();
        if (!(await Uris.ValidaUriAsync(uri, _entityService)))
        {
            throw new Exception("Penhora: URI inválida");
        }

        var nOperador = UserTools.GetAuthenticatedUserId(_httpContextAccessor);
        using var scope = _connectionService.CreateConnectionScopeRw(uri);
        using var oCnn = scope.Connection ?? throw new DatabaseConnectionException();
        var connectionStopwatch = PenhoraDatabaseMetrics.StartTimer();
        var queryStopwatch = PenhoraDatabaseMetrics.StartTimer();
        if (oCnn == null)
        {
            return null;
        }

        try
        {
            PenhoraDatabaseMetrics.RecordConnectionOpen("Delete", uri, connectionStopwatch);
            PenhoraDatabaseMetrics.IncrementActiveConnections("Delete", uri);
            var deleteValidation = await validation.CanDelete(id, this, uri, oCnn);
            if (!deleteValidation)
            {
                throw new Exception("Erro inesperado ao validar 0x0!");
            }
        }
        catch (SGValidationException ex)
        {
            PenhoraDatabaseMetrics.DecrementActiveConnections("Delete", uri);
            throw new Exception(ex.Message);
        }
        catch (Exception)
        {
            PenhoraDatabaseMetrics.DecrementActiveConnections("Delete", uri);
            throw new Exception("Erro inesperado ao validar 0x1!");
        }

        var penhora = await reader.ReadAsync(id ?? default, oCnn);
        try
        {
            if (penhora != null)
            {
                await writer.DeleteAsync(penhora, nOperador, oCnn);
                PenhoraDatabaseMetrics.RecordSqlQuery("Delete", "DELETE", uri, queryStopwatch, 1);
                if (_memoryCache is MemoryCache memCache)
                {
                    memCache.Compact(1.0);
                }
            }

            PenhoraDatabaseMetrics.DecrementActiveConnections("Delete", uri);
            return penhora;
        }
        catch (Exception ex)
        {
            PenhoraDatabaseMetrics.RecordDatabaseError("Delete", "SqlException", uri);
            PenhoraDatabaseMetrics.DecrementActiveConnections("Delete", uri);
            throw new Exception(ex.Message);
        }
    }

    public virtual void Dispose()
    {
        Dispose(true);
        GC.SuppressFinalize(this);
    }

    protected virtual void Dispose(bool disposing)
    {
        if (_disposed)
            return;
        if (disposing)
        {
        //_cache?.Dispose();
        }

        _disposed = true;
    }

    private void ThrowIfDisposed()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
    }
}