// 100% auto-generated by Source Genesys WebApi Front & Back Creator
// copyright © 2000-2025 Menphis - Sistemas Inteligentes
// This file is part of the Source Genesys project                     
// 100% auto-generated by Source Genesys WebApi Front & Back Creator
// copyright © 2000-2025 Menphis - Sistemas Inteligentes
// This file is part of the Source Genesys project                     
using MenphisSI.GerAdv.Models.Response.All;
using MenphisSI.GerAdv.Readers;
using System.Data;

namespace MenphisSI.GerAdv.Tests.Readers;
/// <summary>
/// Comprehensive unit tests for EscritoriosReader class
/// Tests all public methods including async operations, data reading, and data transformation
/// </summary>
public class EscritoriosReaderTests : IDisposable
{
    private readonly Mock<IFEscritoriosFactory> _mockEscritoriosFactory;
    private readonly Mock<MsiSqlConnection> _mockConnection;
    private readonly Mock<IDataRecord> _mockDataRecord;
    private readonly EscritoriosReader _escritoriosReader;
    public EscritoriosReaderTests()
    {
        _mockEscritoriosFactory = new Mock<IFEscritoriosFactory>();
        _mockConnection = new Mock<MsiSqlConnection>();
        _mockDataRecord = new Mock<IDataRecord>();
        _escritoriosReader = new EscritoriosReader(_mockEscritoriosFactory.Object);
    }

#region Constructor Tests
    [Fact]
    public void Constructor_WithValidFactory_ShouldInitializeReader()
    {
        // Act & Assert
        _escritoriosReader.Should().NotBeNull();
    }

    [Fact]
    public void Constructor_WithNullFactory_ShouldThrowArgumentNullException()
    {
        // Act & Assert
        Assert.Throws<ArgumentNullException>(() => new EscritoriosReader(null !));
    }

#endregion
#region ListarN Tests
    [Fact]
    public async Task ListarN_WithValidParameters_ShouldCallDevourerSqlData()
    {
        // Arrange
        var max = 10;
        var uri = "valid-uri"; // This would need to be a valid URI in actual implementation
        var cWhere = "escCodigo > 0";
        var parameters = new List<SqlParameter>();
        var order = "escnome";
        // Act & Assert
        // Since this calls static methods and external dependencies,
        // we expect it to throw an exception with our test setup
        await Assert.ThrowsAsync<Exception>(() => _escritoriosReader.ListarN(max, uri, cWhere, parameters, order));
    }

    [Fact]
    public async Task ListarN_WithEmptyParameters_ShouldThrowException()
    {
        // Arrange
        var max = 0;
        var uri = string.Empty; // Empty URI should cause an exception
        var cWhere = string.Empty;
        var parameters = new List<SqlParameter>();
        var order = string.Empty;
        // Act & Assert
        await Assert.ThrowsAsync<Exception>(() => _escritoriosReader.ListarN(max, uri, cWhere, parameters, order));
    }

#endregion
#region Listar Tests
    [Fact]
    public async Task Listar_WithValidParameters_ShouldCallListarTabela()
    {
        // Arrange
        var max = 10;
        var uri = "valid-uri"; // This would need to be a valid URI in actual implementation
        var cWhere = "escCodigo > 0";
        var parameters = new List<SqlParameter>();
        var order = "carNome";
        var cancellationToken = CancellationToken.None;
        // Act & Assert
        // Since this calls external dependencies and database connections,
        // we expect it to throw an exception with our test setup
        await Assert.ThrowsAsync<Exception>(() => _escritoriosReader.Listar(max, uri, cWhere, parameters, order, cancellationToken));
    }

    [Fact]
    public async Task Listar_WithCancellationToken_ShouldRespectCancellation()
    {
        // Arrange
        var max = 10;
        var uri = "test-uri";
        var cWhere = "escCodigo > 0";
        var parameters = new List<SqlParameter>();
        var order = "carNome";
        var cancellationToken = new CancellationToken(true); // Already cancelled
        // Act & Assert
        // Even with cancellation, this should throw an exception due to invalid URI
        await Assert.ThrowsAsync<Exception>(() => _escritoriosReader.Listar(max, uri, cWhere, parameters, order, cancellationToken));
    }

#endregion
#region Read Tests with ID and Connection
    [Fact]
    public async Task Read_WithValidId_ShouldReturnEscritoriosResponse()
    {
        // Arrange
        var id = 123;
        var expectedEscritorios = new FEscritorios
        {
            ID = id,
            FNome = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        };
        _mockEscritoriosFactory.Setup(x => x.CreateFromIdAsync(id, _mockConnection.Object)).ReturnsAsync(expectedEscritorios);
        // Act
        var result = await _escritoriosReader.Read(id, _mockConnection.Object);
        // Assert
        result.Should().NotBeNull();
        result?.Id.Should().Be(id);
        result?.Nome.Should().Be("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA");
    }

    [Fact]
    public async Task Read_WithEmptyId_ShouldReturnNull()
    {
        // Arrange
        var id = 0; // Empty ID
        var emptyFEscritorios = new FEscritorios
        {
            ID = 0
        };
        _mockEscritoriosFactory.Setup(x => x.CreateFromIdAsync(id, _mockConnection.Object)).ReturnsAsync(emptyFEscritorios);
        // Act
        var result = await _escritoriosReader.Read(id, _mockConnection.Object);
        // Assert
        result.Should().BeNull();
    }

    [Fact]
    public async Task Read_WithNegativeId_ShouldReturnNull()
    {
        // Arrange
        var id = -1;
        var emptyFEscritorios = new FEscritorios
        {
            ID = 0
        };
        _mockEscritoriosFactory.Setup(x => x.CreateFromIdAsync(id, _mockConnection.Object)).ReturnsAsync(emptyFEscritorios);
        // Act
        var result = await _escritoriosReader.Read(id, _mockConnection.Object);
        // Assert
        result.Should().BeNull();
    }

#endregion
#region ReadM Tests
    [Fact]
    public async Task ReadM_WithValidId_ShouldReturnEscritoriosModel()
    {
        // Arrange
        var id = 123;
        var expectedFEscritorios = new FEscritorios
        {
            ID = id,
            FNome = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        };
        _mockEscritoriosFactory.Setup(x => x.CreateFromIdAsync(id, _mockConnection.Object)).ReturnsAsync(expectedFEscritorios);
        // Act
        var result = await _escritoriosReader.ReadM(id, _mockConnection.Object);
        // Assert
        result.Should().NotBeNull();
        result?.Id.Should().Be(id);
        result?.Nome.Should().Be("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA");
    }

    [Fact]
    public async Task ReadM_WithEmptyId_ShouldReturnModelWithDefaults()
    {
        // Arrange
        var id = 0;
        var emptyFEscritorios = new FEscritorios
        {
            ID = 0,
            FNome = null
        };
        _mockEscritoriosFactory.Setup(x => x.CreateFromIdAsync(id, _mockConnection.Object)).ReturnsAsync(emptyFEscritorios);
        // Act
        var result = await _escritoriosReader.ReadM(id, _mockConnection.Object);
        // Assert
        result.Should().NotBeNull();
        result?.Id.Should().Be(0);
        result?.Nome.Should().Be(string.Empty);
    }

#endregion
#region Read with FEscritorios and Connection Tests
    [Fact]
    public void Read_WithValidFEscritoriosAndConnection_ShouldReturnEscritoriosResponse()
    {
        // Arrange
        var dbRec = new FEscritorios
        {
            ID = 123,
            FNome = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        };
        // Act
        var result = _escritoriosReader.Read(dbRec, _mockConnection.Object);
        // Assert
        result.Should().NotBeNull();
        result?.Id.Should().Be(123);
        result?.Nome.Should().Be("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA");
    }

    [Fact]
    public void Read_WithNullFEscritoriosAndConnection_ShouldReturnNull()
    {
        // Arrange
        FEscritorios? dbRec = null;
        // Act
        var result = _escritoriosReader.Read(dbRec, _mockConnection.Object);
        // Assert
        result.Should().BeNull();
    }

#endregion
#region Read with Where and Parameters Tests
    [Fact]
    public void Read_WithWhereAndParameters_ShouldReturnEscritoriosResponse()
    {
        // Arrange
        var where = "escCodigo = @id";
        var parameters = new List<SqlParameter>
        {
            new("@id", 123)
        };
        var expectedFEscritorios = new FEscritorios
        {
            ID = 123,
            FNome = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        };
        _mockEscritoriosFactory.Setup(x => x.CreateFromParameters(parameters, _mockConnection.Object, "", "", where, "")).Returns(expectedFEscritorios);
        // Act
        var result = _escritoriosReader.Read(where, parameters, _mockConnection.Object);
        // Assert
        result.Should().NotBeNull();
        result?.Id.Should().Be(123);
        result?.Nome.Should().Be("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA");
    }

    [Fact]
    public void Read_WithWhereAndParameters_WhenRecordNotFound_ShouldReturnNull()
    {
        // Arrange
        var where = "escCodigo = @id";
        var parameters = new List<SqlParameter>
        {
            new("@id", 999)
        };
        var emptyFEscritorios = new FEscritorios
        {
            ID = 0
        };
        _mockEscritoriosFactory.Setup(x => x.CreateFromParameters(parameters, _mockConnection.Object, "", "", where, "")).Returns(emptyFEscritorios);
        // Act
        var result = _escritoriosReader.Read(where, parameters, _mockConnection.Object);
        // Assert
        result.Should().BeNull();
    }

#endregion
#region Read with FEscritorios Tests
    [Fact]
    public void Read_WithValidFEscritorios_ShouldReturnEscritoriosResponse()
    {
        // Arrange
        var dbRec = new FEscritorios
        {
            ID = 123,
            FNome = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        };
        // Act
        var result = _escritoriosReader.Read(dbRec);
        // Assert
        result.Should().NotBeNull();
        result?.Id.Should().Be(123);
        result?.Nome.Should().Be("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA");
    }

    [Fact]
    public void Read_WithNullFEscritorios_ShouldReturnNull()
    {
        // Arrange
        FEscritorios? dbRec = null;
        // Act
        var result = _escritoriosReader.Read(dbRec);
        // Assert
        result.Should().BeNull();
    }

    [Fact]
    public void Read_WithFEscritoriosNullNome_ShouldReturnEmptyStringForNome()
    {
        // Arrange
        var dbRec = new FEscritorios
        {
            ID = 123,
            FNome = null
        };
        // Act
        var result = _escritoriosReader.Read(dbRec);
        // Assert
        result.Should().NotBeNull();
        result?.Id.Should().Be(123);
        result?.Nome.Should().Be(string.Empty);
    }

#endregion
#region Read with DBEscritorios Tests
    [Fact]
    public void Read_WithValidSGDBEscritorios_ShouldReturnEscritoriosResponse()
    {
        // Arrange
        var dbRec = new DBEscritorios
        {
            ID = 123,
            FNome = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        };
        // Act
        var result = _escritoriosReader.Read(dbRec);
        // Assert
        result.Should().NotBeNull();
        result?.Id.Should().Be(123);
        result?.Nome.Should().Be("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA");
    }

    [Fact]
    public void Read_WithNullSGDBEscritorios_ShouldReturnNull()
    {
        // Arrange
        DBEscritorios? dbRec = null;
        // Act
        var result = _escritoriosReader.Read(dbRec);
        // Assert
        result.Should().BeNull();
    }

    [Fact]
    public void Read_WithSGDBEscritoriosNullNome_ShouldReturnEmptyStringForNome()
    {
        // Arrange
        var dbRec = new DBEscritorios
        {
            ID = 123,
            FNome = null // This should result in empty string in response
        };
        // Act
        var result = _escritoriosReader.Read(dbRec);
        // Assert
        result.Should().NotBeNull();
        result?.Id.Should().Be(123);
        result?.Nome.Should().Be(string.Empty);
    }

#endregion
#region ReadAll with FEscritorios and IDataRecord Tests
    [Fact]
    public void ReadAll_WithValidFEscritoriosAndDataRecord_ShouldReturnEscritoriosResponseAll()
    {
        // Arrange
        var dbRec = new FEscritorios
        {
            ID = 123,
            FNome = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        };
        // Act
        var result = _escritoriosReader.ReadAll(dbRec, _mockDataRecord.Object);
        // Assert
        result.Should().NotBeNull();
        result?.Id.Should().Be(123);
        result?.Nome.Should().Be("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA");
    }

    [Fact]
    public void ReadAll_WithNullFEscritoriosAndDataRecord_ShouldReturnNull()
    {
        // Arrange
        FEscritorios? dbRec = null;
        // Act
        var result = _escritoriosReader.ReadAll(dbRec, _mockDataRecord.Object);
        // Assert
        result.Should().BeNull();
    }

    [Fact]
    public void ReadAll_WithFEscritoriosNullNomeAndDataRecord_ShouldReturnEmptyStringForNome()
    {
        // Arrange
        var dbRec = new FEscritorios
        {
            ID = 123,
            FNome = null
        };
        // Act
        var result = _escritoriosReader.ReadAll(dbRec, _mockDataRecord.Object);
        // Assert
        result.Should().NotBeNull();
        result?.Id.Should().Be(123);
        result?.Nome.Should().Be(string.Empty);
    }

#endregion
#region ReadAll with DBEscritorios and DataRow Tests
    [Fact]
    public void ReadAll_WithValidSGDBEscritoriosAndDataRow_ShouldReturnEscritoriosResponseAll()
    {
        // Arrange
        var dbRec = new DBEscritorios
        {
            ID = 123,
            FNome = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        };
        // Act
        var result = _escritoriosReader.ReadAll(dbRec, null);
        // Assert
        result.Should().NotBeNull();
        result?.Id.Should().Be(123);
        result?.Nome.Should().Be("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA");
    }

    [Fact]
    public void ReadAll_WithNullSGDBEscritoriosAndDataRow_ShouldReturnNull()
    {
        // Arrange
        DBEscritorios? dbRec = null;
        // Act
        var result = _escritoriosReader.ReadAll(dbRec, null);
        // Assert
        result.Should().BeNull();
    }

    [Fact]
    public void ReadAll_WithSGDBEscritoriosNullNomeAndDataRow_ShouldReturnEmptyStringForNome()
    {
        // Arrange
        var dbRec = new DBEscritorios
        {
            ID = 123,
            FNome = null // This should result in empty string in response
        };
        // Act
        var result = _escritoriosReader.ReadAll(dbRec, null);
        // Assert
        result.Should().NotBeNull();
        result?.Id.Should().Be(123);
        result?.Nome.Should().Be(string.Empty);
    }

#endregion
#region Edge Cases and Error Handling Tests
    [Fact]
    public async Task Read_WithFactoryException_ShouldPropagateException()
    {
        // Arrange
        var id = 123;
        var expectedException = new InvalidOperationException("Factory error");
        _mockEscritoriosFactory.Setup(x => x.CreateFromIdAsync(id, _mockConnection.Object)).ThrowsAsync(expectedException);
        // Act & Assert
        var exception = await Assert.ThrowsAsync<InvalidOperationException>(() => _escritoriosReader.Read(id, _mockConnection.Object));
        exception.Should().Be(expectedException);
    }

    [Fact]
    public async Task ReadM_WithFactoryException_ShouldPropagateException()
    {
        // Arrange
        var id = 123;
        var expectedException = new InvalidOperationException("Factory error");
        _mockEscritoriosFactory.Setup(x => x.CreateFromIdAsync(id, _mockConnection.Object)).ThrowsAsync(expectedException);
        // Act & Assert
        var exception = await Assert.ThrowsAsync<InvalidOperationException>(() => _escritoriosReader.ReadM(id, _mockConnection.Object));
        exception.Should().Be(expectedException);
    }

    [Fact]
    public void Read_WithWhereParameters_WhenFactoryThrowsException_ShouldPropagateException()
    {
        // Arrange
        var where = "escCodigo = @id";
        var parameters = new List<SqlParameter>
        {
            new("@id", 123)
        };
        var expectedException = new InvalidOperationException("Factory error");
        _mockEscritoriosFactory.Setup(x => x.CreateFromParameters(parameters, _mockConnection.Object, "", "", where, "")).Throws(expectedException);
        // Act & Assert
        var exception = Assert.Throws<InvalidOperationException>(() => _escritoriosReader.Read(where, parameters, _mockConnection.Object));
        exception.Should().Be(expectedException);
    }

#endregion
#region Data Consistency Tests
    [Theory]
    [InlineData(1, "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA")]
    [InlineData(999, "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB")]
    [InlineData(0, "")]
    public void Read_WithVariousData_ShouldMaintainConsistency(int id, string nome)
    {
        // Arrange
        var dbRec = new FEscritorios
        {
            ID = id,
            FNome = nome
        };
        // Act
        var result = _escritoriosReader.Read(dbRec);
        // Assert
        if (id == 0)
        {
            result.Should().NotBeNull();
            result?.Id.Should().Be(id);
        }
        else
        {
            result.Should().NotBeNull();
            result?.Id.Should().Be(id);
            result?.Nome.Should().Be(nome);
        }
    }

    [Theory]
    [InlineData(1, "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA")]
    [InlineData(999, "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB")]
    [InlineData(0, "")]
    public void ReadAll_WithVariousData_ShouldMaintainConsistency(int id, string nome)
    {
        // Arrange
        var dbRec = new FEscritorios
        {
            ID = id,
            FNome = nome
        };
        // Act
        var result = _escritoriosReader.ReadAll(dbRec, _mockDataRecord.Object);
        // Assert
        result.Should().NotBeNull();
        result?.Id.Should().Be(id);
        result?.Nome.Should().Be(nome);
    }

#endregion
#region Async Behavior Tests
    [Fact]
    public async Task AsyncMethods_ShouldCompleteWithoutBlocking()
    {
        // Arrange
        var id = 123;
        var expectedFEscritorios = new FEscritorios
        {
            ID = id,
            FNome = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        };
        _mockEscritoriosFactory.Setup(x => x.CreateFromIdAsync(id, _mockConnection.Object)).ReturnsAsync(expectedFEscritorios);
        // Act & Assert
        // Test only the methods that don't depend on external URI connections
        var readTask = _escritoriosReader.Read(id, _mockConnection.Object);
        var readMTask = _escritoriosReader.ReadM(id, _mockConnection.Object);
        await Task.WhenAll(readTask, readMTask);
        // If we reach here, async methods completed without deadlock
        Assert.True(true);
    }

    [Fact]
    public async Task ListarN_WithInvalidUri_ShouldThrowException()
    {
        // Arrange
        var max = 10;
        var uri = "test-uri"; // Invalid URI
        var cWhere = "";
        var parameters = new List<SqlParameter>();
        var order = "";
        // Act & Assert
        // This should throw an exception because the URI is invalid
        await Assert.ThrowsAsync<Exception>(() => _escritoriosReader.ListarN(max, uri, cWhere, parameters, order));
    }

    [Fact]
    public async Task Listar_WithInvalidUri_ShouldThrowException()
    {
        // Arrange
        var max = 10;
        var uri = "test-uri"; // Invalid URI
        var cWhere = "";
        var parameters = new List<SqlParameter>();
        var order = "";
        var cancellationToken = CancellationToken.None;
        // Act & Assert
        // This should throw an exception because the URI is invalid
        await Assert.ThrowsAsync<Exception>(() => _escritoriosReader.Listar(max, uri, cWhere, parameters, order, cancellationToken));
    }

#endregion
#region Parameter Validation Tests
    [Fact]
    public async Task Read_WithNullConnection_ShouldHandleGracefully()
    {
        // Arrange
        var id = 123;
        // Act & Assert
        // This would typically throw an exception or handle gracefully
        // depending on the implementation
        try
        {
            await _escritoriosReader.Read(id, null !);
        }
        catch (Exception ex)
        {
            ex.Should().NotBeNull();
        }
    }

    [Fact]
    public async Task ReadM_WithNullConnection_ShouldHandleGracefully()
    {
        // Arrange
        var id = 123;
        // Act & Assert
        try
        {
            await _escritoriosReader.ReadM(id, null !);
        }
        catch (Exception ex)
        {
            ex.Should().NotBeNull();
        }
    }

    [Fact]
    public void Read_WithNullParametersList_ShouldHandleGracefully()
    {
        // Arrange
        var where = "escCodigo = @id";
        // Act & Assert
        try
        {
            _escritoriosReader.Read(where, null !, _mockConnection.Object);
        }
        catch (Exception ex)
        {
            ex.Should().NotBeNull();
        }
    }

#endregion
#region Integration-like Tests
    [Fact]
    public void Read_FEscritorios_ShouldMapAllPropertiesCorrectly()
    {
        // Arrange
        var testId = 456;
        var testNome = "MA";
        var dbRec = new FEscritorios
        {
            ID = testId,
            FNome = testNome
        };
        // Act
        var result = _escritoriosReader.Read(dbRec);
        // Assert
        result.Should().NotBeNull();
        result.Should().BeOfType<EscritoriosResponse>();
        result!.Id.Should().Be(testId);
        result.Nome.Should().Be(testNome);
    }

    [Fact]
    public void ReadAll_FEscritorios_ShouldMapAllPropertiesCorrectly()
    {
        // Arrange
        var testId = 789;
        var testNome = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
        var dbRec = new FEscritorios
        {
            ID = testId,
            FNome = testNome
        };
        // Act
        var result = _escritoriosReader.ReadAll(dbRec, _mockDataRecord.Object);
        // Assert
        result.Should().NotBeNull();
        result.Should().BeOfType<EscritoriosResponseAll>();
        result!.Id.Should().Be(testId);
        result.Nome.Should().Be(testNome);
    }

#endregion
#region Dispose
    public virtual void Dispose()
    {
        // Clean up any resources if needed
        GC.SuppressFinalize(this);
    }
#endregion
}