export enum FieldsAgendaSemana
{	funcionario = `Funcionario`,
	advogado = `Advogado`,
	tipocompromisso = `TipoCompromisso`,
	cliente = `Cliente`,
	paranome = `ParaNome`,
	data = `Data`,
	hora = `Hora`,
	compromisso = `Compromisso`,
	concluido = `Concluido`,
	liberado = `Liberado`,
	importante = `Importante`,
	horafinal = `HoraFinal`,
	nome = `Nome`,
	nomecliente = `NomeCliente`,
	tipo = `Tipo`,
}
