export enum FieldsAgendaRecords
{	agenda = `Agenda`,
	clientessocios = `ClientesSocios`,
	colaborador = `Colaborador`,
	foro = `Foro`,
	julgador = `Julgador`,
	perito = `Perito`,
	aviso1 = `Aviso1`,
	aviso2 = `Aviso2`,
	aviso3 = `Aviso3`,
	crmaviso1 = `CrmAviso1`,
	crmaviso2 = `CrmAviso2`,
	crmaviso3 = `CrmAviso3`,
	dataaviso1 = `DataAviso1`,
	dataaviso2 = `DataAviso2`,
	dataaviso3 = `DataAviso3`,
}
