export enum FieldsAgendaRepetir
{	advogado = `Advogado`,
	cliente = `Cliente`,
	funcionario = `Funcionario`,
	processo = `Processo`,
	datafinal = `DataFinal`,
	horafinal = `HoraFinal`,
	pessoal = `Pessoal`,
	frequencia = `Frequencia`,
	dia = `Dia`,
	mes = `Mes`,
	hora = `Hora`,
	idquem = `IDQuem`,
	idquem2 = `IDQuem2`,
	mensagem = `Mensagem`,
	idtipo = `IDTipo`,
	id1 = `ID1`,
	id2 = `ID2`,
	id3 = `ID3`,
	id4 = `ID4`,
	segunda = `Segunda`,
	quarta = `Quarta`,
	quinta = `Quinta`,
	sexta = `Sexta`,
	sabado = `Sabado`,
	domingo = `Domingo`,
	terca = `Terca`,
}
