export enum FieldsAlarmSMS
{	operador = `Operador`,
	agenda = `Agenda`,
	recado = `Recado`,
	descricao = `Descricao`,
	hora = `Hora`,
	minuto = `Minuto`,
	d1 = `D1`,
	d2 = `D2`,
	d3 = `D3`,
	d4 = `D4`,
	d5 = `D5`,
	d6 = `D6`,
	d7 = `D7`,
	email = `EMail`,
	desativar = `Desativar`,
	today = `Today`,
	excetodiasfelizes = `ExcetoDiasFelizes`,
	desktop = `Desktop`,
	alertardatahora = `AlertarDataHora`,
	guidexo = `GuidExo`,
	emocao = `Emocao`,
	guid = `GUID`,
}
