export enum FieldsColaboradores
{	cargo = `Cargo`,
	cliente = `Cliente`,
	cidade = `Cidade`,
	sexo = `Sexo`,
	nome = `Nome`,
	cpf = `CPF`,
	rg = `RG`,
	dtnasc = `DtNasc`,
	idade = `Idade`,
	endereco = `Endereco`,
	bairro = `Bairro`,
	cep = `CEP`,
	fone = `Fone`,
	observacao = `Observacao`,
	email = `EMail`,
	cnh = `CNH`,
	class = `Class`,
	etiqueta = `Etiqueta`,
	ani = `Ani`,
	bold = `Bold`,
}
