export enum FieldsContaCorrente
{	processo = `Processo`,
	cliente = `Cliente`,
	ciacordo = `CIAcordo`,
	quitado = `Quitado`,
	idcontrato = `IDContrato`,
	quitadoid = `QuitadoID`,
	debitoid = `DebitoID`,
	livrocaixaid = `LivroCaixaID`,
	sucumbencia = `Sucumbencia`,
	distregra = `DistRegra`,
	dtoriginal = `DtOriginal`,
	parcelax = `ParcelaX`,
	valor = `Valor`,
	data = `Data`,
	historico = `Historico`,
	contrato = `Contrato`,
	pago = `Pago`,
	distribuir = `Distribuir`,
	lc = `LC`,
	idhtrab = `IDHTrab`,
	nroparcelas = `NroParcelas`,
	valorprincipal = `ValorPrincipal`,
	parcelaprincipalid = `ParcelaPrincipalID`,
	hide = `Hide`,
	datapgto = `DataPgto`,
}
