export enum FieldsDivisaoTribunal
{	justica = `Justica`,
	area = `Area`,
	cidade = `Cidade`,
	foro = `Foro`,
	tribunal = `Tribunal`,
	numcodigo = `NumCodigo`,
	nomeespecial = `NomeEspecial`,
	codigodiv = `CodigoDiv`,
	endereco = `Endereco`,
	fone = `Fone`,
	fax = `Fax`,
	cep = `CEP`,
	obs = `Obs`,
	email = `EMail`,
	andar = `Andar`,
	etiqueta = `Etiqueta`,
	bold = `Bold`,
	guid = `GUID`,
}
