export enum FieldsEnderecoSistema
{	tipoenderecosistema = `TipoEnderecoSistema`,
	processo = `Processo`,
	cidade = `Cidade`,
	cadastro = `Cadastro`,
	cadastroexcod = `CadastroExCod`,
	motivo = `Motivo`,
	contatonolocal = `ContatoNoLocal`,
	endereco = `Endereco`,
	bairro = `Bairro`,
	cep = `CEP`,
	fone = `Fone`,
	fax = `Fax`,
	observacao = `Observacao`,
}
