export enum FieldsEnderecos
{	cidade = `Cidade`,
	topindex = `TopIndex`,
	descricao = `Descricao`,
	contato = `Contato`,
	dtnasc = `DtNasc`,
	endereco = `Endereco`,
	bairro = `Bairro`,
	privativo = `Privativo`,
	addcontato = `AddContato`,
	cep = `CEP`,
	oab = `OAB`,
	obs = `OBS`,
	fone = `Fone`,
	fax = `Fax`,
	tratamento = `Tratamento`,
	site = `Site`,
	email = `EMail`,
	quem = `Quem`,
	quemindicou = `QuemIndicou`,
	reportecbonly = `ReportECBOnly`,
	etiqueta = `Etiqueta`,
	ani = `Ani`,
	bold = `Bold`,
	guid = `GUID`,
}
