export enum FieldsEscritorios
{	cidade = `Cidade`,
	cnpj = `CNPJ`,
	casa = `Casa`,
	parceria = `Parceria`,
	nome = `Nome`,
	oab = `OAB`,
	endereco = `Endereco`,
	bairro = `Bairro`,
	cep = `CEP`,
	fone = `Fone`,
	fax = `Fax`,
	site = `Site`,
	email = `EMail`,
	obs = `OBS`,
	advresponsavel = `AdvResponsavel`,
	secretaria = `Secretaria`,
	inscest = `InscEst`,
	correspondente = `Correspondente`,
	top = `Top`,
	etiqueta = `Etiqueta`,
	bold = `Bold`,
	guid = `GUID`,
}
