export enum FieldsFornecedores
{	cidade = `Cidade`,
	grupo = `Grupo`,
	nome = `Nome`,
	subgrupo = `SubGrupo`,
	tipo = `Tipo`,
	sexo = `Sexo`,
	cnpj = `CNPJ`,
	inscest = `InscEst`,
	cpf = `CPF`,
	rg = `RG`,
	endereco = `Endereco`,
	bairro = `Bairro`,
	cep = `CEP`,
	fone = `Fone`,
	fax = `Fax`,
	email = `Email`,
	site = `Site`,
	obs = `Obs`,
	produtos = `Produtos`,
	contatos = `Contatos`,
	etiqueta = `Etiqueta`,
	bold = `Bold`,
	guid = `GUID`,
}
