export enum FieldsHistorico
{	processo = `Processo`,
	precatoria = `Precatoria`,
	apenso = `Apenso`,
	fase = `Fase`,
	statusandamento = `StatusAndamento`,
	extraid = `ExtraID`,
	idne = `IDNE`,
	extraguid = `ExtraGUID`,
	liminarorigem = `LiminarOrigem`,
	naopublicavel = `NaoPublicavel`,
	idinstprocesso = `IDInstProcesso`,
	data = `Data`,
	observacao = `Observacao`,
	agendado = `Agendado`,
	concluido = `Concluido`,
	mesmaagenda = `MesmaAgenda`,
	sad = `SAD`,
	resumido = `Resumido`,
	top = `Top`,
	guid = `GUID`,
}
