export enum FieldsHorasTrab
{	cliente = `Cliente`,
	processo = `Processo`,
	advogado = `Advogado`,
	funcionario = `Funcionario`,
	servico = `Servico`,
	idcontatocrm = `IDContatoCRM`,
	honorario = `Honorario`,
	idagenda = `IDAgenda`,
	data = `Data`,
	status = `Status`,
	hrini = `HrIni`,
	hrfim = `HrFim`,
	tempo = `Tempo`,
	valor = `Valor`,
	obs = `OBS`,
	anexo = `Anexo`,
	anexocomp = `AnexoComp`,
	anexounc = `AnexoUNC`,
}
