export enum FieldsModelosDocumentos
{	tipomodelodocumento = `TipoModeloDocumento`,
	nome = `Nome`,
	remuneracao = `Remuneracao`,
	assinatura = `Assinatura`,
	header = `Header`,
	footer = `Footer`,
	extra1 = `Extra1`,
	extra2 = `Extra2`,
	extra3 = `Extra3`,
	outorgante = `Outorgante`,
	outorgados = `Outorgados`,
	poderes = `Poderes`,
	objeto = `Objeto`,
	titulo = `Titulo`,
	testemunhas = `Testemunhas`,
	css = `CSS`,
	guid = `GUID`,
}
