export enum FieldsOutrasPartesCliente
{	cidade = `Cidade`,
	nome = `Nome`,
	terceirizado = `Terceirizado`,
	clienteprincipal = `ClientePrincipal`,
	tipo = `Tipo`,
	sexo = `Sexo`,
	dtnasc = `DtNasc`,
	cpf = `CPF`,
	rg = `RG`,
	cnpj = `CNPJ`,
	inscest = `InscEst`,
	nomefantasia = `NomeFantasia`,
	endereco = `Endereco`,
	cep = `CEP`,
	bairro = `Bairro`,
	fone = `Fone`,
	fax = `Fax`,
	email = `EMail`,
	site = `Site`,
	class = `Class`,
	etiqueta = `Etiqueta`,
	ani = `Ani`,
	bold = `Bold`,
}
