export enum FieldsProDespesas
{	cliente = `Cliente`,
	processo = `Processo`,
	ligacaoid = `LigacaoID`,
	corrigido = `Corrigido`,
	data = `Data`,
	valororiginal = `ValorOriginal`,
	quitado = `Quitado`,
	datacorrecao = `DataCorrecao`,
	valor = `Valor`,
	tipo = `Tipo`,
	historico = `Historico`,
	livrocaixa = `LivroCaixa`,
	guid = `GUID`,
}
