// 100% auto-generated by Source Genesys WebApi Front & Back Creator
// copyright © 2000-2025 Menphis - Sistemas Inteligentes
// This file is part of the Source Genesys project                     
#pragma warning disable IDE0130 // Namespace does not match folder structure

namespace MenphisSI.GerAdv.Services;
#pragma warning restore IDE0130 // Namespace does not match folder structure

public partial class NEPalavrasChavesService(IOptions<AppSettings> appSettings, IFNEPalavrasChavesFactory nepalavraschavesFactory, INEPalavrasChavesReader reader, INEPalavrasChavesValidation validation, INEPalavrasChavesWriter writer, IHttpContextAccessor httpContextAccessor, IHybridCache cache, IMemoryCache memory, IConnectionService connectionService, IGenericVoiceFilterService<Filters.FilterNEPalavrasChaves> voiceFilterService, IServicesFilter serviceFilter, IEntityService entityService) : INEPalavrasChavesService, IDisposable
{
    private readonly IHttpContextAccessor _httpContextAccessor = httpContextAccessor;
    private readonly IOptions<AppSettings> _appSettings = appSettings;
    private readonly IHybridCache _cache = cache;
    private readonly IMemoryCache _memoryCache = memory ?? throw new ArgumentNullException(nameof(memory));
    private readonly IConnectionService _connectionService = connectionService ?? throw new ArgumentNullException(nameof(connectionService));
    private readonly IGenericVoiceFilterService<Filters.FilterNEPalavrasChaves> _voiceFilterService = voiceFilterService ?? throw new ArgumentNullException(nameof(voiceFilterService));
    private readonly IServicesFilter servicesFilter = serviceFilter ?? throw new ArgumentNullException(nameof(serviceFilter));
    private bool _disposed;
    private readonly IEntityService _entityService = entityService;
    private readonly IFNEPalavrasChavesFactory nepalavraschavesFactory = nepalavraschavesFactory;
    private readonly INEPalavrasChavesReader reader = reader;
    private readonly INEPalavrasChavesValidation validation = validation;
    private readonly INEPalavrasChavesWriter writer = writer;
    public async Task<IEnumerable<NEPalavrasChavesResponseAll>> Filter([FromQuery] int max, [FromBody] Filters.FilterNEPalavrasChaves filtro, [FromRoute, Required] string uri)
    {
        ThrowIfDisposed();
        if (!(await Uris.ValidaUriAsync(uri, _entityService)))
        {
            throw new Exception("NEPalavrasChaves: URI inválida");
        }

        using var scope = _connectionService.CreateConnectionScope(uri);
        using var oCnn = scope.Connection ?? throw new DatabaseConnectionException();
        if (max <= 0)
        {
            max = BaseConsts.PMaxItens;
        }

#pragma warning disable CS0168 // Variable is declared but never used

        try
        {
            var filtroResult = filtro == null ? null : servicesFilter.WFiltroNEPalavrasChaves(filtro!);
            string where = filtroResult?.where ?? string.Empty;
            List<SqlParameter>? parameters = filtroResult?.parametros ?? [];
            var filterHash = GenericVoiceFilterService<Filters.FilterNEPalavrasChaves>.GetFilterHash(filtro);
            var keyCache = await reader.ReadStringAuditorAsync(max, uri, where, parameters, oCnn);
            var cacheKey = $"{uri}-{max}NEPalavrasChaves-Filter-{where.GetHashCode2()}{filterHash}{keyCache}";
            var entryOptions = new HybridCacheEntryOptions
            {
                Expiration = TimeSpan.FromSeconds(BaseConsts.PMaxGetListSecondsCacheId),
                LocalCacheExpiration = TimeSpan.FromSeconds(BaseConsts.PMaxGetListSecondsCacheId)
            };
            var result = await _cache.GetOrCreateAsync(cacheKey, async cancel => await GetDataAllAsync(max, string.IsNullOrEmpty(where) ? string.Empty : TSql.Where + where, parameters, uri, cancel), entryOptions, cancellationToken: CancellationToken.None);
            return result;
        }
        catch (Exception ex)
        {
            // _logger.Error(ex, ex.Message); // TODO
            throw new Exception($"NEPalavrasChaves - error on filtering.");
        }
#pragma warning restore CS0168 // Variable is declared but never used

    }

    public async Task<Filters.FilterNEPalavrasChaves> FilterVoice([FromBody] Filters.FilterNEPalavrasChaves filtro, [FromBody] CommandSpeakerRequest? message, [FromRoute, Required] string uri)
    {
        ThrowIfDisposed();
        if (!(await Uris.ValidaUriAsync(uri, _entityService)))
        {
            throw new Exception("NEPalavrasChaves: URI inválida");
        }

        try
        {
            // Se há mensagem de comando de voz, processar via OpenAI
            Filters.FilterNEPalavrasChaves? filtroProcessado = filtro;
            if (message != null && !string.IsNullOrWhiteSpace(message.Message))
            {
                filtro = filtro ?? new Filters.FilterNEPalavrasChaves();
                filtroProcessado = await ProcessFilterVoiceCommandAsync(message, filtro, uri);
            }

            return filtroProcessado ?? new Filters.FilterNEPalavrasChaves();
        }
        catch (Exception)
        {
            // _logger.Error(ex, ex.Message); // TODO
            throw new Exception($"NEPalavrasChaves - error on creating filter.");
        }
    }

    public async Task<NEPalavrasChavesResponse?> GetById([FromQuery] int id, [FromRoute, Required] string uri, CancellationToken token)
    {
        ThrowIfDisposed();
        if (id < 1)
        {
            return new NEPalavrasChavesResponse();
        }

        var entryOptions = new HybridCacheEntryOptions
        {
            Expiration = TimeSpan.FromSeconds(BaseConsts.PMaxSecondsCacheId),
            LocalCacheExpiration = TimeSpan.FromSeconds(BaseConsts.PMaxSecondsCacheId)
        };
        using var scope = _connectionService.CreateConnectionScope(uri);
        using var oCnn = scope.Connection ?? throw new DatabaseConnectionException();
        try
        {
            var keyCache = await reader.ReadStringAuditorAsync(id, uri, oCnn);
            var result = await _cache.GetOrCreateAsync($"{uri}-NEPalavrasChaves-GetById-{id}-{keyCache}", async cancel => await GetDataByIdAsync(id, oCnn, cancel), entryOptions, cancellationToken: token);
            return result;
        }
        catch (Exception)
        {
            throw new Exception($"NEPalavrasChaves - {uri}-: GetById");
        }
    }

    private async Task<NEPalavrasChavesResponse?> GetDataByIdAsync(int id, MsiSqlConnection? oCnn, CancellationToken token) => await reader.ReadAsync(id, oCnn);
    public async Task<AuditorResponse?> GetAuditor([FromQuery] int id, [FromRoute, Required] string uri, CancellationToken token)
    {
        ThrowIfDisposed();
        AuditorResponse? result = null;
        if (id < 1)
        {
            return result;
        }

        using var scope = _connectionService.CreateConnectionScope(uri);
        using var oCnn = scope.Connection ?? throw new DatabaseConnectionException();
        try
        {
            result = await reader.ReadAuditorAsync(id, uri, oCnn);
            return result;
        }
        catch (Exception)
        {
            throw new Exception($"NEPalavrasChaves - {uri}-: GetAuditor");
        }
    }

    public async Task<NEPalavrasChavesResponse?> AddAndUpdate([FromBody] Models.NEPalavrasChaves? regNEPalavrasChaves, [FromRoute, Required] string uri)
    {
        ThrowIfDisposed();
        if (regNEPalavrasChaves == null)
        {
            return null;
        }

        if (!(await Uris.ValidaUriAsync(uri, _entityService)))
        {
            throw new Exception("NEPalavrasChaves: URI inválida");
        }

        using var scope = _connectionService.CreateConnectionScopeRw(uri);
        using var oCnn = scope.Connection ?? throw new DatabaseConnectionException();
        if (oCnn == null)
        {
            return null;
        }

        try
        {
            var validade = await validation.ValidateReg(regNEPalavrasChaves, this, uri, oCnn);
            if (!validade)
            {
                throw new Exception("Erro inesperado ao validar 0x0!");
            }
        }
        catch (SGValidationException ex)
        {
            throw new Exception(ex.Message);
        }
        catch (Exception)
        {
            throw new Exception("Erro inesperado ao validar 0x1!");
        }

        int operadorId = UserTools.GetAuthenticatedUserId(_httpContextAccessor);
        using var saved = await writer.WriteAsync(regNEPalavrasChaves, operadorId, oCnn);
        return reader.Read(saved, oCnn);
    }

    public async Task<NEPalavrasChavesResponse?> Validation([FromBody] Models.NEPalavrasChaves? regNEPalavrasChaves, [FromRoute, Required] string uri)
    {
        ThrowIfDisposed();
        if (regNEPalavrasChaves == null)
        {
            return null;
        }

        if (!(await Uris.ValidaUriAsync(uri, _entityService)))
        {
            throw new Exception("NEPalavrasChaves: URI inválida");
        }

        using var scope = _connectionService.CreateConnectionScopeRw(uri);
        using var oCnn = scope.Connection ?? throw new DatabaseConnectionException();
        if (oCnn == null)
        {
            return null;
        }

        try
        {
            var validade = await validation.ValidateReg(regNEPalavrasChaves, this, uri, oCnn);
            if (!validade)
            {
                throw new Exception("Erro inesperado ao validar 0x0!");
            }
        }
        catch (SGValidationException ex)
        {
            throw new Exception(ex.Message);
        }
        catch (Exception)
        {
            throw new Exception("Erro inesperado ao validar 0x1!");
        }

        if (regNEPalavrasChaves.Id.IsEmptyIDNumber())
        {
            return new NEPalavrasChavesResponse();
        }

        return await reader.ReadAsync(regNEPalavrasChaves.Id, oCnn);
    }

    public async Task<NEPalavrasChavesResponse?> Delete([FromQuery] int? id, [FromRoute, Required] string uri)
    {
        if (id == null || id.IsEmptyIDNumber())
        {
            return null;
        }

        ThrowIfDisposed();
        if (!(await Uris.ValidaUriAsync(uri, _entityService)))
        {
            throw new Exception("NEPalavrasChaves: URI inválida");
        }

        var nOperador = UserTools.GetAuthenticatedUserId(_httpContextAccessor);
        using var scope = _connectionService.CreateConnectionScopeRw(uri);
        using var oCnn = scope.Connection ?? throw new DatabaseConnectionException();
        if (oCnn == null)
        {
            return null;
        }

        try
        {
            var deleteValidation = await validation.CanDelete(id, this, uri, oCnn);
            if (!deleteValidation)
            {
                throw new Exception("Erro inesperado ao validar 0x0!");
            }
        }
        catch (SGValidationException ex)
        {
            throw new Exception(ex.Message);
        }
        catch (Exception)
        {
            throw new Exception("Erro inesperado ao validar 0x1!");
        }

        var nepalavraschaves = await reader.ReadAsync(id ?? default, oCnn);
        try
        {
            if (nepalavraschaves != null)
            {
                await writer.DeleteAsync(nepalavraschaves, nOperador, oCnn);
                if (_memoryCache is MemoryCache memCache)
                {
                    memCache.Compact(1.0);
                }
            }
        }
        catch (Exception ex)
        {
            throw new Exception(ex.Message);
        }

        return nepalavraschaves;
    }

    public virtual void Dispose()
    {
        Dispose(true);
        GC.SuppressFinalize(this);
    }

    protected virtual void Dispose(bool disposing)
    {
        if (_disposed)
            return;
        if (disposing)
        {
        //_cache?.Dispose();
        }

        _disposed = true;
    }

    private void ThrowIfDisposed()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
    }
}