// 100% auto-generated by Source Genesys WebApi Front & Back Creator
// copyright © 2000-2025 Menphis - Sistemas Inteligentes
// This file is part of the Source Genesys project                     
'use client';
import { INavigator } from '@/app/interfaces/INavigator';
import SituacaoInc from '../Crud/Inc/Situacao';
import { getParamFromUrl } from '@/app/tools/helpers';
interface SituacaoIncContainerProps {
  id: number;
  navigator: INavigator;
  onSuccess: (registro?: any) => void;
}
const SituacaoIncContainer: React.FC<SituacaoIncContainerProps> = ({ id, navigator, onSuccess }) => {
  const handleClose = () => {};
  const handleError = () => {};
  return (
  <SituacaoInc
  id={id}
  onClose={handleClose}
  onSuccess={onSuccess}
  onError={handleError}
  />
);
};
export default SituacaoIncContainer;