// 100% auto-generated by Source Genesys WebApi Front & Back Creator
// copyright © 2000-2026 Menphis - Sistemas Inteligentes
// This file is part of the Source Genesys project
// Tabela:Objetos
// Fonte:ValidationsGenerator
namespace MenphisSI.GerAdv.Validations;
public partial interface IObjetosValidation
{
    Task<bool> ValidateReg(Models.Objetos reg, IObjetosService service, IJusticaReader justicaReader, IAreaReader areaReader, [FromRoute, Required] string uri, MsiSqlConnection? oCnn);
    Task<bool> CanDelete(int? id, IObjetosService service, [FromRoute, Required] string uri, MsiSqlConnection? oCnn);
}

public class ObjetosValidation : IObjetosValidation
{
    public async Task<bool> CanDelete(int? id, IObjetosService service, [FromRoute, Required] string uri, MsiSqlConnection? oCnn)
    {
        if (id == null || id <= 0)
            throw new SGValidationException("Id inválido");
        var reg = await service.GetById(id ?? default, uri, default);
        if (reg == null)
            throw new SGValidationException($"Registro com id {id} não encontrado.");
        return true;
    }

    private bool ValidSizes(Models.Objetos reg)
    {
        if (reg.Nome != null && reg.Nome.Length > DBObjetosDicInfo.OjtNome.FTamanho)
            throw new SGValidationException($"Nome deve ter no máximo {DBObjetosDicInfo.OjtNome.FTamanho} caracteres.");
        return true;
    }

    public async Task<bool> ValidateReg(Models.Objetos reg, IObjetosService service, IJusticaReader justicaReader, IAreaReader areaReader, [FromRoute, Required] string uri, MsiSqlConnection? oCnn)
    {
        if (reg == null)
            throw new SGValidationException("Objeto está nulo");
        if (string.IsNullOrWhiteSpace(reg.Nome))
            throw new SGValidationException("Nome é obrigatório");
        if (reg.Nome.Contains("%"))
            throw new SGValidationException("Nome possui caracter inválido (%)");
        var validSizes = ValidSizes(reg);
        if (!validSizes)
            return false;
        // Justica
        if (!reg.Justica.IsEmptyIDNumber())
        {
            var regJustica = await justicaReader.ReadAsync(reg.Justica, oCnn);
            if (regJustica == null || regJustica.Id != reg.Justica)
            {
                throw new SGValidationException($"Justiça não encontrado ({regJustica?.Id}).");
            }
        }

        // Area
        if (!reg.Area.IsEmptyIDNumber())
        {
            var regArea = await areaReader.ReadAsync(reg.Area, oCnn);
            if (regArea == null || regArea.Id != reg.Area)
            {
                throw new SGValidationException($"Área não encontrado ({regArea?.Id}).");
            }
        }

        return true;
    }
}