// 100% auto-generated by Source Genesys WebApi Front & Back Creator
// copyright © 2000-2025 Menphis - Sistemas Inteligentes
// This file is part of the Source Genesys project                     
using Xunit;
using FluentAssertions;
using Moq;
using System;
using System.Threading.Tasks;
using MenphisSI.GerAdv.Writers;
using MenphisSI.GerAdv.Models;

namespace MenphisSI.GerAdv.Tests.Writers;
public class ProCDAWriterTests
{
    private readonly Mock<IFProCDAFactory> _mockProCDAFactory;
    private readonly Mock<FProCDA> _mockFProCDA;
    private readonly Mock<MsiSqlConnection> _mockConnection;
    private readonly ProCDAWriter _procdaWriter;
    public ProCDAWriterTests()
    {
        _mockProCDAFactory = new Mock<IFProCDAFactory>();
        _mockFProCDA = new Mock<FProCDA>();
        _mockConnection = new Mock<MsiSqlConnection>();
        _procdaWriter = new ProCDAWriter(_mockProCDAFactory.Object);
    }

#region WriteAsync Tests
    [Fact]
    public async Task WriteAsync_WithNewClient_ShouldCreateNewRecord()
    {
        // Arrange
        var procda = CreateValidProCDAModel();
        procda.Id = 0; // ID vazio para novo registro
        var auditorQuem = 123;
        _mockProCDAFactory.Setup(x => x.CreateAsync()).ReturnsAsync(_mockFProCDA.Object);
        _mockFProCDA.Setup(x => x.UpdateAsync(It.IsAny<MsiSqlConnection>(), It.IsAny<int>(), It.IsAny<CancellationToken>(), It.IsAny<int>())).ReturnsAsync(0);
        // Act
        var result = await _procdaWriter.WriteAsync(procda, auditorQuem, _mockConnection.Object);
        // Assert
        result.Should().Be(_mockFProCDA.Object);
        _mockProCDAFactory.Verify(x => x.CreateAsync(), Times.Once);
        _mockProCDAFactory.Verify(x => x.CreateFromIdAsync(It.IsAny<int>(), It.IsAny<MsiSqlConnection>()), Times.Never);
        _mockFProCDA.Verify(x => x.UpdateAsync(It.IsAny<MsiSqlConnection>(), It.IsAny<int>(), It.IsAny<CancellationToken>(), It.IsAny<int>()), Times.Once);
    }

    [Fact]
    public async Task WriteAsync_WithExistingClient_ShouldLoadExistingRecord()
    {
        // Arrange
        var procda = CreateValidProCDAModel();
        procda.Id = 456; // ID existente
        var auditorQuem = 123;
        _mockProCDAFactory.Setup(x => x.CreateFromIdAsync(procda.Id, _mockConnection.Object)).ReturnsAsync(_mockFProCDA.Object);
        _mockFProCDA.Setup(x => x.UpdateAsync(It.IsAny<MsiSqlConnection>(), It.IsAny<int>(), It.IsAny<CancellationToken>(), It.IsAny<int>())).ReturnsAsync(0);
        ;
        // Act
        var result = await _procdaWriter.WriteAsync(procda, auditorQuem, _mockConnection.Object);
        // Assert
        result.Should().Be(_mockFProCDA.Object);
        _mockProCDAFactory.Verify(x => x.CreateFromIdAsync(procda.Id, _mockConnection.Object), Times.Once);
        _mockProCDAFactory.Verify(x => x.CreateAsync(), Times.Never);
        _mockFProCDA.Verify(x => x.UpdateAsync(It.IsAny<MsiSqlConnection>(), It.IsAny<int>(), It.IsAny<CancellationToken>(), It.IsAny<int>()), Times.Once);
    }

    [Fact]
    public async Task WriteAsync_ShouldMapAllPropertiesCorrectly()
    {
        // Arrange
        var procda = CreateValidProCDAModel();
        var auditorQuem = 99;
        _mockProCDAFactory.Setup(x => x.CreateAsync()).ReturnsAsync(_mockFProCDA.Object);
        _mockFProCDA.Setup(x => x.UpdateAsync(It.IsAny<MsiSqlConnection>(), It.IsAny<int>(), It.IsAny<CancellationToken>(), It.IsAny<int>())).ReturnsAsync(0);
        // Act
        var result = await _procdaWriter.WriteAsync(procda, auditorQuem, _mockConnection.Object);
        // Assert
        result.Should().Be(_mockFProCDA.Object);
        _mockFProCDA.VerifySet(x => x.FProcesso = procda.Processo, Times.Once);
        _mockFProCDA.VerifySet(x => x.FNome = procda.Nome, Times.Once);
        _mockFProCDA.VerifySet(x => x.FNroInterno = procda.NroInterno, Times.Once);
        _mockFProCDA.VerifySet(x => x.FGUID = procda.GUID, Times.Once);
        _mockFProCDA.VerifySet(x => x.AuditorQuem = auditorQuem, Times.Once);
    }

    [Fact]
    public async Task WriteAsync_WhenFactoryThrowsException_ShouldPropagateException()
    {
        // Arrange
        var procda = CreateValidProCDAModel();
        var auditorQuem = 123;
        var expectedException = new InvalidOperationException("Factory error");
        _mockProCDAFactory.Setup(x => x.CreateAsync()).ThrowsAsync(expectedException);
        // Act & Assert
        var exception = await Assert.ThrowsAsync<InvalidOperationException>(() => _procdaWriter.WriteAsync(procda, auditorQuem, _mockConnection.Object));
        exception.Should().Be(expectedException);
    }

    [Fact]
    public async Task WriteAsync_WhenUpdateAsyncFails_ShouldPropagateException()
    {
        // Arrange
        var procda = CreateValidProCDAModel();
        var auditorQuem = 123;
        var expectedException = new InvalidOperationException("Factory error");
        _mockProCDAFactory.Setup(x => x.CreateAsync()).ReturnsAsync(_mockFProCDA.Object);
        _mockFProCDA.Setup(x => x.UpdateAsync(It.IsAny<MsiSqlConnection>(), It.IsAny<int>(), It.IsAny<CancellationToken>(), It.IsAny<int>())).ThrowsAsync(expectedException);
        // Act & Assert
        var exception = await Assert.ThrowsAsync<InvalidOperationException>(() => _procdaWriter.WriteAsync(procda, auditorQuem, _mockConnection.Object));
        exception.Should().Be(expectedException);
    }

#endregion
#region Delete Tests
    [Fact]
    public async Task Delete_ShouldCallFactoryDeleteAsync()
    {
        // Arrange
        var procdaResponse = new ProCDAResponse
        {
            Id = 123
        };
        var operadorId = 456;
        _mockProCDAFactory.Setup(x => x.DeleteAsync(operadorId, procdaResponse.Id, _mockConnection.Object)).Returns(Task.CompletedTask);
        // Act
        await _procdaWriter.Delete(procdaResponse, operadorId, _mockConnection.Object);
        // Assert
        _mockProCDAFactory.Verify(x => x.DeleteAsync(operadorId, procdaResponse.Id, _mockConnection.Object), Times.Once);
    }

    [Fact]
    public async Task Delete_WithValidParameters_ShouldCompleteSuccessfully()
    {
        // Arrange
        var procdaResponse = new ProCDAResponse
        {
            Id = 999
        };
        var operadorId = 111;
        _mockProCDAFactory.Setup(x => x.DeleteAsync(operadorId, procdaResponse.Id, _mockConnection.Object)).Returns(Task.CompletedTask);
        // Act
        Func<Task> act = async () => await _procdaWriter.Delete(procdaResponse, operadorId, _mockConnection.Object);
        // Assert
        await act.Should().NotThrowAsync();
    }

    [Fact]
    public async Task Delete_WhenFactoryDeleteAsyncFails_ShouldPropagateException()
    {
        // Arrange
        var procdaResponse = new ProCDAResponse
        {
            Id = 123
        };
        var operadorId = 456;
        var expectedException = new InvalidOperationException("Delete failed");
        _mockProCDAFactory.Setup(x => x.DeleteAsync(operadorId, procdaResponse.Id, _mockConnection.Object)).ThrowsAsync(expectedException);
        // Act & Assert
        var exception = await Assert.ThrowsAsync<InvalidOperationException>(() => _procdaWriter.Delete(procdaResponse, operadorId, _mockConnection.Object));
        exception.Should().Be(expectedException);
    }

#endregion
#region Constructor Tests
    [Fact]
    public void Constructor_WithValidFactory_ShouldCreateInstance()
    {
        // Act
        var writer = new ProCDAWriter(_mockProCDAFactory.Object);
        // Assert
        writer.Should().NotBeNull();
    }

    [Fact]
    public void Constructor_WithNullFactory_ShouldThrowArgumentNullException()
    {
        // Act & Assert
        Action act = () => new ProCDAWriter(null);
        act.Should().Throw<ArgumentNullException>();
    }

#endregion
#region Helper Methods
    private static Models.ProCDA CreateValidProCDAModel()
    {
        return new Models.ProCDA
        {
            Id = 0,
            Processo = 1,
            Nome = "João",
            NroInterno = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
            GUID = Guid.NewGuid().ToString()
        };
    }
#endregion
}