// 100% auto-generated by Source Genesys WebApi Front & Back Creator
// copyright © 2000-2025 Menphis - Sistemas Inteligentes
// This file is part of the Source Genesys project                     
'use client';
import { useState, useEffect, useCallback, useRef, useMemo } from 'react';
import { IProDespesasService } from '../Services/ProDespesas.service';
import { NotifySystemActions, subscribeToNotifications } from '@/app/tools/NotifySystem';
import { IProDespesas } from '../Interfaces/interface.ProDespesas';
import { FilterProDespesas } from '../Filters/ProDespesas';
import { isValidDate } from '@/app/tools/datetime';
import { ProDespesasApi } from '../Apis/ApiProDespesas';

export const useProDespesasForm = (
  initialProDespesas: IProDespesas,
  dataService: IProDespesasService
) => {
  const [data, setData] = useState<IProDespesas>(initialProDespesas);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleChange = useCallback((e: any) => {
    const { name, value, type, checked } = e.target;
    setData((prev) => ({
      ...prev,
      [name]: type === 'checkbox' ? checked : value,
    }));    
  }, []);

  const loadProDespesas = useCallback(async (id: number) => {
    if (!id || id === 0) {
      setData(initialProDespesas);
      return;
    }

    setLoading(true);
    setError(null);
    
    try {
      const dados = await dataService.fetchProDespesasById(id);
      setData(dados);
    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : 'Erro ao carregar Pro Despesas';
      setError(errorMessage);
      //console.log('Erro ao carregar Pro Despesas');
    } finally {
      setLoading(false);
    }
  }, [dataService, initialProDespesas]);

  const resetForm = useCallback(() => {
    setData(initialProDespesas);
    setError(null);
  }, [initialProDespesas]);

  const returnValue = useMemo(() => ({
    data,
    loading,
    error,
    handleChange,
    loadProDespesas,
    resetForm,
    setData
  }), [data, loading, error, handleChange, loadProDespesas, resetForm]);
  return returnValue;
};


export const useProDespesasNotifications = (
  onUpdate?: (entity: any) => void,
  onDelete?: (entity: any) => void,
  onAdd?: (entity: any) => void
) => {
  const callbacksRef = useRef({ onUpdate, onDelete, onAdd });
  
  useEffect(() => {
    callbacksRef.current = { onUpdate, onDelete, onAdd };
  }, [onUpdate, onDelete, onAdd]);

  useEffect(() => {
    const unsubscribe = subscribeToNotifications('ProDespesas', (entity) => {
      try {
        const { onUpdate, onDelete, onAdd } = callbacksRef.current;
        
        switch (entity.action) {
          case NotifySystemActions.DELETE:
            onDelete?.(entity);
            break;
          case NotifySystemActions.UPDATE:
            onUpdate?.(entity);
            break;
          case NotifySystemActions.ADD:
            onAdd?.(entity);
            break;
        }
      } catch (err) {
        //console.log("Erro no listener de notificações.");
      }
    });

    return () => {
      unsubscribe();
    };
  }, []);
};


export const useProDespesasList = (dataService: IProDespesasService, currentFilter?: FilterProDespesas | undefined | null) => {
  const [data, setData] = useState<IProDespesas[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null); 
  const currentFilterRef = useRef<FilterProDespesas | undefined | null>(currentFilter);

  useEffect(() => {
    currentFilterRef.current = currentFilter;
  }, [currentFilter]);

  const fetchData = useCallback(async (filtro?: FilterProDespesas | undefined | null) => {
   
    setLoading(true);
    setError(null);
    
    try {
      const result = await dataService.getAll(filtro ?? {} as FilterProDespesas);
      setData(result);
    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : 'Erro ao carregar prodespesas';
      setError(errorMessage);
      //console.log('Erro ao carregar prodespesas');
    } finally {
      setLoading(false);
    }
  }, [dataService]);   

 const refreshData = useCallback(() => {
     fetchData(currentFilterRef.current);
  }, [fetchData]);
  
  useProDespesasNotifications(
    refreshData, // onUpdate
    refreshData, // onDelete  
    refreshData  // onAdd
  );
   

  return {
    data,
    loading,
    error,
    fetchData,
    refreshData
  };
};


export function useValidationsProDespesas() {

  async function runValidation(data: IProDespesas, uri?: string, token?: string): Promise<{ isValid: boolean; message: string } | null> {

    const prodespesasApi = new ProDespesasApi(uri ?? '', token ?? '');

    const result = await prodespesasApi.validation(data);

    return result;
  }

  function validate(data: IProDespesas): { isValid: boolean; message: string } {
    if (!data) return { isValid: false, message: 'Dados não informados.' };
    
      try {
   
        if (data.data.length <= 0) { 
                                             return { isValid: false, message: 'O campo Data não pode ficar vazio.' };
                                         } 
if (data.historico.length > 100) { 
                                             return { isValid: false, message: 'O campo Historico não pode ter mais de 100 caracteres.' };
                                         } 



        return { isValid: true, message: '' };

         } catch (error) {
          return { isValid: true, message: 'Erro ao validar os dados.' };
    }

  }

 return { validate, runValidation };
}