// 100% auto-generated by Source Genesys WebApi Front & Back Creator
// copyright © 2000-2025 Menphis - Sistemas Inteligentes
// This file is part of the Source Genesys project                     
#pragma warning disable IDE0130 // Namespace does not match folder structure

namespace MenphisSI.GerAdv.Services;
#pragma warning restore IDE0130 // Namespace does not match folder structure

public partial class TipoEMailService(IOptions<AppSettings> appSettings, IFTipoEMailFactory tipoemailFactory, ITipoEMailReader reader, ITipoEMailValidation validation, ITipoEMailWriter writer, ISMSAliceService smsaliceService, HybridCache cache, IMemoryCache memory) : ITipoEMailService, IDisposable
{
    private readonly IOptions<AppSettings> _appSettings = appSettings;
    private readonly HybridCache _cache = cache;
    private readonly IMemoryCache _memoryCache = memory;
    private bool _disposed;
    private readonly IFTipoEMailFactory tipoemailFactory = tipoemailFactory;
    private readonly ITipoEMailReader reader = reader;
    private readonly ITipoEMailValidation validation = validation;
    private readonly ITipoEMailWriter writer = writer;
    private readonly ISMSAliceService smsaliceService = smsaliceService;
    public async Task<IEnumerable<TipoEMailResponseAll>> GetAll(int max, [FromRoute, Required] string uri, CancellationToken token = default)
    {
        max = Math.Min(Math.Max(max, 1), BaseConsts.PMaxItens);
        ThrowIfDisposed();
        if (!Uris.ValidaUri(uri, _appSettings))
        {
            throw new Exception("TipoEMail: URI inválida");
        }

        var entryOptions = new HybridCacheEntryOptions
        {
            Expiration = TimeSpan.FromMinutes(BaseConsts.PMaxMinutesCache),
            LocalCacheExpiration = TimeSpan.FromMinutes(BaseConsts.PMaxMinutesCache)
        };
        var cacheKey = $"{uri}-TipoEMail-GetAll-{max}";
        var result = await _cache.GetOrCreateAsync(cacheKey, async cancel => await GetDataAllAsync(max, string.Empty, [], uri, cancel), entryOptions, cancellationToken: token);
        return result;
    }

    public async Task<IEnumerable<TipoEMailResponseAll>> Filter([FromQuery] int max, [FromBody] Filters.FilterTipoEMail filtro, [FromRoute, Required] string uri)
    {
        ThrowIfDisposed();
        using var oCnn = Configuracoes.GetConnectionByUri(uri);
        if (oCnn == null)
        {
            throw new DatabaseConnectionException();
        }

        if (max <= 0)
        {
            max = BaseConsts.PMaxItens;
        }

        var filtroResult = filtro == null ? null : WFiltro(filtro!);
        string where = filtroResult?.where ?? string.Empty;
        List<SqlParameter> parameters = filtroResult?.parametros ?? [];
        var filterHash = GetFilterHash(filtro);
        var cacheKey = $"{uri}-{max}-TipoEMail-Filter-{where.GetHashCode2()}{filterHash}";
        var entryOptions = new HybridCacheEntryOptions
        {
            Expiration = TimeSpan.FromSeconds(BaseConsts.PMaxGetListSecondsCacheId),
            LocalCacheExpiration = TimeSpan.FromSeconds(BaseConsts.PMaxGetListSecondsCacheId)
        };
        var result = await _cache.GetOrCreateAsync(cacheKey, async cancel => await GetDataAllAsync(max, string.IsNullOrEmpty(where) ? string.Empty : TSql.Where + where, parameters, uri, cancel), entryOptions, cancellationToken: new());
        return result;
    }

    public async Task<TipoEMailResponse?> GetById([FromQuery] int id, [FromRoute, Required] string uri, CancellationToken token)
    {
        ThrowIfDisposed();
        if (id < 1)
        {
            return new TipoEMailResponse();
        }

        var entryOptions = new HybridCacheEntryOptions
        {
            Expiration = TimeSpan.FromSeconds(BaseConsts.PMaxSecondsCacheId),
            LocalCacheExpiration = TimeSpan.FromSeconds(BaseConsts.PMaxSecondsCacheId)
        };
        using var oCnn = Configuracoes.GetConnectionByUri(uri);
        try
        {
            var result = await _cache.GetOrCreateAsync($"{uri}-TipoEMail-GetById-{id}", async cancel => await GetDataByIdAsync(id, oCnn, cancel), entryOptions, cancellationToken: token);
            return result;
        }
        catch (Exception)
        {
            throw new Exception($"TipoEMail - {uri}-: GetById");
        }
    }

    private async Task<TipoEMailResponse?> GetDataByIdAsync(int id, MsiSqlConnection? oCnn, CancellationToken token) => await reader.Read(id, oCnn);
    public async Task<TipoEMailResponse?> AddAndUpdate([FromBody] Models.TipoEMail? regTipoEMail, [FromRoute, Required] string uri)
    {
        ThrowIfDisposed();
        if (regTipoEMail == null)
        {
            return null;
        }

        if (!Uris.ValidaUri(uri, _appSettings))
        {
            throw new Exception("TipoEMail: URI inválida");
        }

        using var oCnn = Configuracoes.GetConnectionByUriRw(uri);
        if (oCnn == null)
        {
            return null;
        }

        try
        {
            var validade = await validation.ValidateReg(regTipoEMail, this, uri, oCnn);
            if (!validade)
            {
                throw new Exception("Erro inesperado ao validar 0x0!");
            }
        }
        catch (SGValidationException ex)
        {
            throw new Exception(ex.Message);
        }
        catch (Exception)
        {
            throw new Exception("Erro inesperado ao validar 0x1!");
        }

        using var saved = await writer.WriteAsync(regTipoEMail, oCnn);
        return reader.Read(saved, oCnn);
    }

    public async Task<TipoEMailResponse?> Validation([FromBody] Models.TipoEMail? regTipoEMail, [FromRoute, Required] string uri)
    {
        ThrowIfDisposed();
        if (regTipoEMail == null)
        {
            return null;
        }

        if (!Uris.ValidaUri(uri, _appSettings))
        {
            throw new Exception("TipoEMail: URI inválida");
        }

        using var oCnn = Configuracoes.GetConnectionByUriRw(uri);
        if (oCnn == null)
        {
            return null;
        }

        try
        {
            var validade = await validation.ValidateReg(regTipoEMail, this, uri, oCnn);
            if (!validade)
            {
                throw new Exception("Erro inesperado ao validar 0x0!");
            }
        }
        catch (SGValidationException ex)
        {
            throw new Exception(ex.Message);
        }
        catch (Exception)
        {
            throw new Exception("Erro inesperado ao validar 0x1!");
        }

        if (regTipoEMail.Id.IsEmptyIDNumber())
        {
            return new TipoEMailResponse();
        }

        return await reader.Read(regTipoEMail.Id, oCnn);
    }

    public async Task<TipoEMailResponse?> Delete([FromQuery] int? id, [FromRoute, Required] string uri)
    {
        if (id == null || id.IsEmptyIDNumber())
        {
            return null;
        }

        ThrowIfDisposed();
        if (!Uris.ValidaUri(uri, _appSettings))
        {
            throw new Exception("TipoEMail: URI inválida");
        }

        using var oCnn = Configuracoes.GetConnectionByUriRw(uri);
        if (oCnn == null)
        {
            return null;
        }

        try
        {
            var deleteValidation = await validation.CanDelete(id, this, smsaliceService, uri, oCnn);
            if (!deleteValidation)
            {
                throw new Exception("Erro inesperado ao validar 0x0!");
            }
        }
        catch (SGValidationException ex)
        {
            throw new Exception(ex.Message);
        }
        catch (Exception)
        {
            throw new Exception("Erro inesperado ao validar 0x1!");
        }

        var tipoemail = await reader.Read(id ?? default, oCnn);
        try
        {
            if (tipoemail != null)
            {
                await writer.Delete(tipoemail, 0, oCnn);
                if (_memoryCache is MemoryCache memCache)
                {
                    memCache.Compact(1.0);
                }
            }
        }
        catch (Exception ex)
        {
            throw new Exception(ex.Message);
        }

        return tipoemail;
    }

    public virtual void Dispose()
    {
        Dispose(true);
        GC.SuppressFinalize(this);
    }

    protected virtual void Dispose(bool disposing)
    {
        if (_disposed)
            return;
        if (disposing)
        {
        //_cache?.Dispose();
        }

        _disposed = true;
    }

    private void ThrowIfDisposed()
    {
        if (_disposed)
        {
            throw new ObjectDisposedException(GetType().Name);
        }
    }
}