// 100% auto-generated by Source Genesys WebApi Front & Back Creator
// copyright © 2000-2025 Menphis - Sistemas Inteligentes
// This file is part of the Source Genesys project                     
// CrudWindow.tsx
'use client';
import React, { useEffect } from 'react';
import { EditWindow } from '@/app/components/Cruds/EditWindow';
import OperadorInc from '../Inc/Operador';
import { IOperador } from '../../Interfaces/interface.Operador';
import { useIsMobile } from '@/app/context/MobileContext';
import { OperadorEmpty } from '@/app/GerAdv_TS/Models/Operador';
import { useWindow } from '@/app/hooks/useWindows';
interface OperadorWindowProps {
  isOpen: boolean;
  onClose: () => void;
  dimensions?: { width: number; height: number };
  selectedOperador?: IOperador;
  onSuccess: (registro?: any) => void;
  onError: () => void;
}
const OperadorWindow: React.FC<OperadorWindowProps> = ({
  isOpen, 
  onClose, 
  dimensions, 
  selectedOperador, 
  onSuccess, 
  onError, 
}) => {

const isMobile = useIsMobile();
const dimensionsEmpty = useWindow();
if (!isOpen)
  return null;
  return (
  <>

  <EditWindow
  tableTitle='Operador'
  isOpen={isOpen}
  onClose={onClose}
  dimensions={dimensions ?? dimensionsEmpty}
  newHeight={594}
  newWidth={1250}
  mobile={isMobile}
  id={(selectedOperador?.id ?? 0).toString()}
>
<OperadorInc
id={selectedOperador?.id ?? 0}
onClose={onClose}
onSuccess={onSuccess}
onError={onError}
/>
</EditWindow>

</>
);
};
export const NewWindowOperador: React.FC<OperadorWindowProps> = ({
  isOpen, 
  onClose, 
}) => {
const dimensions = useWindow();
return (
<OperadorWindow
isOpen={isOpen}
onClose={onClose}
dimensions={dimensions}
onSuccess={onClose}
onError={onClose}
selectedOperador={OperadorEmpty()}>
</OperadorWindow>
)
};
export default OperadorWindow;