// 100% auto-generated by Source Genesys WebApi Front & Back Creator
                     // copyright © 2000-2025 Menphis - Sistemas Inteligentes
                     // This file is part of the Source Genesys project                     
                    import { IAgendaFinanceiro } from '../AgendaFinanceiro/Interfaces/interface.AgendaFinanceiro';
export interface AgendaFinanceiro
{
    id: number;
	cidade : number;
	advogado : number;
	funcionario : number;
	tipocompromisso : number;
	cliente : number;
	area : number;
	justica : number;
	processo : number;
	usuario : number;
	preposto : number;
	idcob : number;
	idne : number;
	prazoprovisionado : number;
	oculto : number;
	cartaprecatoria : number;
	repetirdias : number;
	hrfinal : string;
	hrfinal_date? : Date;
	repetir : number;
	eventogerador : number;
	eventodata : string;
	eventodata_date? : Date;
	data : string;
	eventoprazo : number;
	hora : string;
	hora_date? : Date;
	compromisso : string;
	ddias : string;
	ddias_date? : Date;
	dias : number;
	liberado : boolean;
	importante : boolean;
	concluido : boolean;
	idhistorico : number;
	idinsprocesso : number;
	quemid : number;
	quemcodigo : number;
	status : string;
	valor : number;
	compromissohtml : string;
	decisao : string;
	revisar : boolean;
	revisarp2 : boolean;
	sempre : number;
	prazodias : number;
	protocolointegrado : number;
	datainicioprazo : string;
	datainicioprazo_date? : Date;
	usuariociente : boolean;
	nomecidade?: string;
	nomeadvogados?: string;
	nomefuncionarios?: string;
	descricaotipocompromisso?: string;
	nomeclientes?: string;
	descricaoarea?: string;
	nomejustica?: string;
	nropastaprocessos?: string;
	nomeoperador?: string;
	nomeprepostos?: string;

}


export function AgendaFinanceiroEmpty(): IAgendaFinanceiro {
// 20250604
    
    return {
        id: 0,
		cidade: 0,
		advogado: 0,
		funcionario: 0,
		tipocompromisso: 0,
		cliente: 0,
		area: 0,
		justica: 0,
		processo: 0,
		usuario: 0,
		preposto: 0,
		idcob: 0,
		idne: 0,
		prazoprovisionado: 0,
		oculto: 0,
		cartaprecatoria: 0,
		repetirdias: 0,
		hrfinal: '',
		repetir: 0,
		eventogerador: 0,
		eventodata: '',
		data: '',
		eventoprazo: 0,
		hora: '',
		compromisso: '',
		ddias: '',
		dias: 0,
		liberado: false,
		importante: false,
		concluido: false,
		idhistorico: 0,
		idinsprocesso: 0,
		quemid: 0,
		quemcodigo: 0,
		status: '',
		valor: 0,
		compromissohtml: '',
		decisao: '',
		revisar: false,
		revisarp2: false,
		sempre: 0,
		prazodias: 0,
		protocolointegrado: 0,
		datainicioprazo: '',
		usuariociente: false,
    };
}

export function AgendaFinanceiroTestEmpty(): IAgendaFinanceiro {
// 20250604
    
    return {
        id: 1,
		cidade: 1,
		advogado: 1,
		funcionario: 1,
		tipocompromisso: 1,
		cliente: 1,
		area: 1,
		justica: 1,
		processo: 1,
		usuario: 1,
		preposto: 1,
		idcob: 1,
		idne: 1,
		prazoprovisionado: 1,
		oculto: 1,
		cartaprecatoria: 1,
		repetirdias: 1,
		hrfinal: 'X',
		repetir: 1,
		eventogerador: 1,
		eventodata: 'X',
		data: 'X',
		eventoprazo: 1,
		hora: 'X',
		compromisso: 'X',
		ddias: 'X',
		dias: 1,
		liberado: true,
		importante: true,
		concluido: true,
		idhistorico: 1,
		idinsprocesso: 1,
		quemid: 1,
		quemcodigo: 1,
		status: 'X',
		valor: 1,
		compromissohtml: 'X',
		decisao: 'X',
		revisar: true,
		revisarp2: true,
		sempre: 1,
		prazodias: 1,
		protocolointegrado: 1,
		datainicioprazo: 'X',
		usuariociente: true,
    };
}


