// 100% auto-generated by Source Genesys WebApi Front & Back Creator
// copyright © 2000-2026 Menphis - Sistemas Inteligentes
// This file is part of the Source Genesys project
// Fonte:ReadersGenerator
namespace MenphisSI.GerAdv.Readers;
public partial class EnquadramentoEmpresaReader(IFEnquadramentoEmpresaFactory enquadramentoempresaFactory) : IEnquadramentoEmpresaReader
{
    private readonly IFEnquadramentoEmpresaFactory _enquadramentoempresaFactory = enquadramentoempresaFactory ?? throw new ArgumentNullException();
    public async Task<IEnumerable<DBNomeID>?> ListarNAsync(int max, string uri, string cWhere, List<SqlParameter>? parameters, string order) => await DevourerSqlData.ListarNomeID(BuildSqlQuery("eqeCodigo, eqeNome", cWhere, order, max), parameters, uri, caching: false, max: max);
    public async Task<IEnumerable<EnquadramentoEmpresaResponseAll>> ListarAsync(MsiSqlConnection oCnn, int max, string uri, string cWhere, List<SqlParameter>? parameters, string order, CancellationToken cancellationToken)
    {
        var stopwatch = EnquadramentoEmpresaDatabaseMetrics.StartTimer();
        var connStopwatch = EnquadramentoEmpresaDatabaseMetrics.StartTimer();
        try
        {
            EnquadramentoEmpresaDatabaseMetrics.IncrementActiveConnections("ListarAsync", oCnn?.Uri);
            EnquadramentoEmpresaDatabaseMetrics.RecordConnectionOpen("ListarAsync", oCnn?.Uri, connStopwatch);
            var result = await ListarTabelaAsync(oCnn, BuildSqlQuery(DBEnquadramentoEmpresa.CamposSqlX, cWhere, order, max), parameters, uri, caching: false, max: max, cancellationToken: cancellationToken);
            EnquadramentoEmpresaDatabaseMetrics.RecordSqlQuery("ListarAsync", "SELECT", oCnn?.Uri, stopwatch, result.Count());
            return result;
        }
        catch (SqlException)
        {
            EnquadramentoEmpresaDatabaseMetrics.RecordDatabaseError("ListarAsync", "SqlException", oCnn?.Uri);
            throw;
        }
        catch (TimeoutException)
        {
            EnquadramentoEmpresaDatabaseMetrics.RecordDatabaseError("ListarAsync", "Timeout", oCnn?.Uri);
            throw;
        }
        finally
        {
            EnquadramentoEmpresaDatabaseMetrics.DecrementActiveConnections("ListarAsync", oCnn?.Uri);
        }
    }

    private async Task<IEnumerable<EnquadramentoEmpresaResponseAll>> ListarTabelaAsync(MsiSqlConnection? oCnn, string sql, List<SqlParameter>? parameters, string uri, bool caching = false, int max = 200, CancellationToken cancellationToken = default)
    {
        var stopwatch = EnquadramentoEmpresaDatabaseMetrics.StartTimer();
        var result = new List<EnquadramentoEmpresaResponseAll>(max);
        try
        {
            await using var cmd = new SqlCommand(cmdText: ConfiguracoesDBT.CmdSql(sql), connection: oCnn?.InnerConnection)
            {
                CommandTimeout = 120
            };
            if (parameters != null && parameters.Count > 0)
                foreach (var param in parameters)
                {
                    if (!cmd.Parameters.Contains(param.ParameterName))
                    {
                        var newParam = new SqlParameter(param.ParameterName, param.Value)
                        {
                            SqlDbType = param.SqlDbType,
                            Direction = param.Direction,
                            Size = param.Size,
                            Precision = param.Precision,
                            Scale = param.Scale
                        };
                        cmd.Parameters.Add(newParam);
                    }
                }

            await using var reader = await cmd.ExecuteReaderAsync(CommandBehavior.Default, cancellationToken);
            while (await reader.ReadAsync(cancellationToken))
            {
                if (cancellationToken.IsCancellationRequested)
                    return result;
                result.Add(ReadAll(_enquadramentoempresaFactory.CreateFromReader(reader), reader)!);
            }

            EnquadramentoEmpresaDatabaseMetrics.RecordSqlQuery("ListarTabelaAsync", "SELECT", oCnn?.Uri, stopwatch, result.Count);
            return result;
        }
        catch (SqlException)
        {
            EnquadramentoEmpresaDatabaseMetrics.RecordDatabaseError("ListarTabelaAsync", "SqlException", oCnn?.Uri);
            throw;
        }
        catch (TimeoutException)
        {
            EnquadramentoEmpresaDatabaseMetrics.RecordDatabaseError("ListarTabelaAsync", "Timeout", oCnn?.Uri);
            throw;
        }
    }

    public async Task<EnquadramentoEmpresaResponse?> ReadAsync(int id, MsiSqlConnection? oCnn)
    {
        var stopwatch = EnquadramentoEmpresaDatabaseMetrics.StartTimer();
        try
        {
            EnquadramentoEmpresaDatabaseMetrics.IncrementActiveConnections("ReadAsync", oCnn?.Uri);
            using var dbRec = await _enquadramentoempresaFactory.CreateFromIdAsync(id, oCnn);
            var result = dbRec == null || dbRec.ID.IsEmptyIDNumber() ? null : Read(dbRec);
            EnquadramentoEmpresaDatabaseMetrics.RecordSqlQuery("ReadAsync", "SELECT", oCnn?.Uri, stopwatch, result != null ? 1 : 0);
            return result;
        }
        catch (SqlException)
        {
            EnquadramentoEmpresaDatabaseMetrics.RecordDatabaseError("ReadAsync", "SqlException", oCnn?.Uri);
            throw;
        }
        catch (TimeoutException)
        {
            EnquadramentoEmpresaDatabaseMetrics.RecordDatabaseError("ReadAsync", "Timeout", oCnn?.Uri);
            throw;
        }
        finally
        {
        // Ignore
        }
    }

    public async Task<Models.EnquadramentoEmpresa?> ReadMAsync(int id, MsiSqlConnection? oCnn)
    {
        using var dbRec = await _enquadramentoempresaFactory.CreateFromIdAsync(id, oCnn);
        var enquadramentoempresa = new Models.EnquadramentoEmpresa
        {
            Id = dbRec.ID,
            Nome = dbRec.FNome ?? string.Empty,
            Guid = dbRec.FGuid ?? string.Empty,
        };
        return enquadramentoempresa;
    }

    public EnquadramentoEmpresaResponse? Read(FEnquadramentoEmpresa dbRec, MsiSqlConnection? oCnn)
    {
        return Read(dbRec);
    }

    public EnquadramentoEmpresaResponse? Read(string where, List<SqlParameter>? parameters, MsiSqlConnection? oCnn)
    {
        using var dbRec = _enquadramentoempresaFactory.CreateFromParameters(parameters, oCnn, sqlWhere: where);
        return dbRec is null || dbRec.ID.IsEmptyIDNumber() ? null : Read(dbRec);
    }

    public EnquadramentoEmpresaResponse? Read(FEnquadramentoEmpresa dbRec) // Track 001.16072025
    {
        if (dbRec == null)
        {
            return null;
        }

        var enquadramentoempresa = new EnquadramentoEmpresaResponse
        {
            Id = dbRec.ID,
            Nome = dbRec.FNome ?? string.Empty,
            Guid = dbRec.FGuid ?? string.Empty,
        };
        return enquadramentoempresa;
    }

    public EnquadramentoEmpresaResponse? Read(SG.GerAdv.DBEnquadramentoEmpresa dbRec) // Track 002.16072025
    {
        if (dbRec == null)
        {
            return null;
        }

        var enquadramentoempresa = new EnquadramentoEmpresaResponse
        {
            Id = dbRec.ID,
            Nome = dbRec.FNome ?? string.Empty,
            Guid = dbRec.FGuid ?? string.Empty,
        };
        return enquadramentoempresa;
    }

    public EnquadramentoEmpresaResponseAll? ReadAll(FEnquadramentoEmpresa dbRec, IDataRecord dr)
    {
        if (dbRec == null)
        {
            return null;
        }

        var enquadramentoempresa = new EnquadramentoEmpresaResponseAll
        {
            Id = dbRec.ID,
            Nome = dbRec.FNome ?? string.Empty,
            Guid = dbRec.FGuid ?? string.Empty,
        };
        return enquadramentoempresa;
    }

    public EnquadramentoEmpresaResponseAll? ReadAll(SG.GerAdv.DBEnquadramentoEmpresa dbRec, DataRow dr)
    {
        if (dbRec == null)
        {
            return null;
        }

        var enquadramentoempresa = new EnquadramentoEmpresaResponseAll
        {
            Id = dbRec.ID,
            Nome = dbRec.FNome ?? string.Empty,
            Guid = dbRec.FGuid ?? string.Empty,
        };
        return enquadramentoempresa;
    }
}