// 100% auto-generated by Source Genesys WebApi Front & Back Creator
// copyright © 2000-2026 Menphis - Sistemas Inteligentes
// This file is part of the Source Genesys project
// Entity:Rito
// Source:ModelsGenerator
namespace MenphisSI.GerAdv.Models.Response
{
    [Serializable]
    public partial record RitoResponse
    {
        [JsonPropertyName("id")]
        public int Id { get; set; }

        /// <summary>
        /// Descrições - ritDescricao - tamanho máximo: 20 
        /// </summary>
        [JsonPropertyName("descricao")]
        public string Descricao { get; set; } = "";

        /// <summary>
        /// Top - ritTop  
        /// </summary>
        [JsonPropertyName("top")]
        public bool Top { get; set; }

        /// <summary>
        /// Bold - ritBold  
        /// </summary>
        [JsonPropertyName("bold")]
        public bool Bold { get; set; }

        /// <summary>
        /// GUID - ritGuid - tamanho máximo: 100 
        /// </summary>
        [JsonPropertyName("guid")]
        public string Guid { get; set; } = "";
    }
}

namespace MenphisSI.GerAdv.Models.Response.All
{
    [Serializable]
    public partial record RitoResponseAll
    {
        [JsonPropertyName("id")]
        public int Id { get; set; }

        /// <summary>
        /// Descrições - ritDescricao - tamanho máximo: 20 
        /// </summary>
        [JsonPropertyName("descricao")]
        public string Descricao { get; set; } = "";

        /// <summary>
        /// Top - ritTop  
        /// </summary>
        [JsonPropertyName("top")]
        public bool Top { get; set; }

        /// <summary>
        /// Bold - ritBold  
        /// </summary>
        [JsonPropertyName("bold")]
        public bool Bold { get; set; }

        /// <summary>
        /// GUID - ritGuid - tamanho máximo: 100 
        /// </summary>
        [JsonPropertyName("guid")]
        public string Guid { get; set; } = "";
    }
}