// 100% auto-generated by Source Genesys WebApi Front & Back Creator
// copyright © 2000-2025 Menphis - Sistemas Inteligentes
// This file is part of the Source Genesys project                     
namespace MenphisSI.GerAdv.Tests;
public class PontoVirtualAcessosValidationTests : IDisposable
{
    private readonly PontoVirtualAcessosValidation _validation;
    private readonly Mock<IPontoVirtualAcessosService> _mockPontoVirtualAcessosService;
    private readonly Mock<MsiSqlConnection> _mockConnection;
    private readonly Mock<IOperadorReader> _mockOperadorReader;
    private readonly PontoVirtualAcessosService _service;
    private readonly string _validUri = "test-uri";
    public PontoVirtualAcessosValidationTests()
    {
        _validation = new PontoVirtualAcessosValidation();
        _mockPontoVirtualAcessosService = new Mock<IPontoVirtualAcessosService>();
        _mockConnection = new Mock<MsiSqlConnection>();
        _mockOperadorReader = new Mock<IOperadorReader>();
    }

#region Class Structure Tests
    [Fact]
    public void PontoVirtualAcessosValidation_ShouldImplementInterface()
    {
        // Assert
        _validation.Should().BeAssignableTo<IPontoVirtualAcessosValidation>();
    }

    [Fact]
    public void PontoVirtualAcessosValidation_ShouldBePublicClass()
    {
        // Arrange
        var type = typeof(PontoVirtualAcessosValidation);
        // Assert
        type.IsPublic.Should().BeTrue();
        type.IsClass.Should().BeTrue();
        type.IsAbstract.Should().BeFalse();
        type.IsSealed.Should().BeFalse();
    }

    [Fact]
    public void PontoVirtualAcessosValidation_ShouldHaveParameterlessConstructor()
    {
        // Arrange
        var type = typeof(PontoVirtualAcessosValidation);
        var constructors = type.GetConstructors();
        // Assert
        constructors.Should().ContainSingle();
        constructors[0].GetParameters().Should().BeEmpty();
        constructors[0].IsPublic.Should().BeTrue();
    }

    private static Models.PontoVirtualAcessos CreateValidPontoVirtualAcessos()
    {
        return new Models.PontoVirtualAcessos
        {
            Id = 1,
            Operador = 1,
            DataHora = "27/05/2022",
            Tipo = false,
            Origem = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        };
    }

    private void SetupValidMocks()
    {
        // Setup default valid responses for all mocks
        _mockPontoVirtualAcessosService.Setup(x => x.Filter(It.IsAny<int>(), It.IsAny<FilterPontoVirtualAcessos>(), It.IsAny<string>())).ReturnsAsync([]);
        // Setup other mocks but don't override the PontoVirtualAcessoss service mock
        _ = _mockOperadorReader.Setup(x => x.Read(It.IsAny<int>(), It.IsAny<MsiSqlConnection>())).Returns<int, MsiSqlConnection>(valueFunction: static (id, conn) => Task.FromResult(new OperadorResponse { Id = id }));
    }

    private void SetupValidMocksInvalid()
    {
        // Setup default valid responses for all mocks
        _mockPontoVirtualAcessosService.Setup(x => x.Filter(It.IsAny<int>(), It.IsAny<FilterPontoVirtualAcessos>(), It.IsAny<string>())).ReturnsAsync([]);
        // Setup other mocks but don't override the PontoVirtualAcessoss service mock
        _ = _mockOperadorReader.Setup(x => x.Read(It.IsAny<int>(), It.IsAny<MsiSqlConnection>())).Returns<int, MsiSqlConnection>(valueFunction: static (id, conn) => Task.FromResult(new OperadorResponse { Id = 0 }));
    }

    [Fact]
    public async Task ValidateReg_WithNullStringFields_ShouldNotThrow()
    {
        // Arrange
        var pontovirtualacessos = new Models.PontoVirtualAcessos
        {
            Id = 1,
            Operador = 1,
            DataHora = "27/05/2022",
            Tipo = false,
            Origem = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        };
        SetupValidMocks();
        // Act
        var result = await _validation.ValidateReg(pontovirtualacessos, _mockPontoVirtualAcessosService.Object, _mockOperadorReader.Object, _validUri, _mockConnection.Object);
        // Assert
        result.Should().BeTrue();
    }

#endregion
    [Fact]
    public async Task ValidateReg_WithNullInput_ShouldThrowSGValidationException()
    {
        // Act & Assert
        var exception = await Assert.ThrowsAsync<SGValidationException>(() => _validation.ValidateReg(null, _mockPontoVirtualAcessosService.Object, _mockOperadorReader.Object, _validUri, _mockConnection.Object));
        exception.Message.Should().Be("Objeto está nulo");
    }

#region ValidateReg Required DataHora Method Tests 
    [Fact]
    public async Task ValidateReg_WithEmptyDataHora_ShouldThrowSGValidationException()
    {
        // Arrange
        var pontovirtualacessos = CreateValidPontoVirtualAcessos();
        pontovirtualacessos.DataHora = "";
        // Act & Assert
        var exception = await Assert.ThrowsAsync<SGValidationException>(() => _validation.ValidateReg(pontovirtualacessos, _mockPontoVirtualAcessosService.Object, _mockOperadorReader.Object, _validUri, _mockConnection.Object));
        exception.Message.Should().Contain("é obrigatório");
    }

    [Fact]
    public async Task ValidateReg_WithNullDataHora_ShouldThrowSGValidationException()
    {
        // Arrange
        var pontovirtualacessos = CreateValidPontoVirtualAcessos();
        pontovirtualacessos.DataHora = null;
        // Act & Assert
        var exception = await Assert.ThrowsAsync<SGValidationException>(() => _validation.ValidateReg(pontovirtualacessos, _mockPontoVirtualAcessosService.Object, _mockOperadorReader.Object, _validUri, _mockConnection.Object));
        exception.Message.Should().Contain("é obrigatório");
    }

    [Fact]
    public async Task ValidateReg_WithValidDataDataHora_ShouldReturnTrue()
    {
        // Arrange
        var pontovirtualacessos = CreateValidPontoVirtualAcessos();
        SetupValidMocks();
        // Act
        var result = await _validation.ValidateReg(pontovirtualacessos, _mockPontoVirtualAcessosService.Object, _mockOperadorReader.Object, _validUri, _mockConnection.Object);
        // Assert
        result.Should().BeTrue();
    }

    [Fact]
    public async Task ValidateReg_WithWhitespaceDataHora_ShouldThrowSGValidationException()
    {
        // Arrange
        var pontovirtualacessos = CreateValidPontoVirtualAcessos();
        pontovirtualacessos.DataHora = "   ";
        // Act & Assert
        var exception = await Assert.ThrowsAsync<SGValidationException>(() => _validation.ValidateReg(pontovirtualacessos, _mockPontoVirtualAcessosService.Object, _mockOperadorReader.Object, _validUri, _mockConnection.Object));
        exception.Message.Should().Contain("é obrigatório");
    }

#endregion
#region ValidateReg Required Origem Method Tests 
    [Fact]
    public async Task ValidateReg_WithEmptyOrigem_ShouldThrowSGValidationException()
    {
        // Arrange
        var pontovirtualacessos = CreateValidPontoVirtualAcessos();
        pontovirtualacessos.Origem = "";
        // Act & Assert
        var exception = await Assert.ThrowsAsync<SGValidationException>(() => _validation.ValidateReg(pontovirtualacessos, _mockPontoVirtualAcessosService.Object, _mockOperadorReader.Object, _validUri, _mockConnection.Object));
        exception.Message.Should().Contain("é obrigatório");
    }

    [Fact]
    public async Task ValidateReg_WithNullOrigem_ShouldThrowSGValidationException()
    {
        // Arrange
        var pontovirtualacessos = CreateValidPontoVirtualAcessos();
        pontovirtualacessos.Origem = null;
        // Act & Assert
        var exception = await Assert.ThrowsAsync<SGValidationException>(() => _validation.ValidateReg(pontovirtualacessos, _mockPontoVirtualAcessosService.Object, _mockOperadorReader.Object, _validUri, _mockConnection.Object));
        exception.Message.Should().Contain("é obrigatório");
    }

    [Fact]
    public async Task ValidateReg_WithValidDataOrigem_ShouldReturnTrue()
    {
        // Arrange
        var pontovirtualacessos = CreateValidPontoVirtualAcessos();
        SetupValidMocks();
        // Act
        var result = await _validation.ValidateReg(pontovirtualacessos, _mockPontoVirtualAcessosService.Object, _mockOperadorReader.Object, _validUri, _mockConnection.Object);
        // Assert
        result.Should().BeTrue();
    }

    [Fact]
    public async Task ValidateReg_WithWhitespaceOrigem_ShouldThrowSGValidationException()
    {
        // Arrange
        var pontovirtualacessos = CreateValidPontoVirtualAcessos();
        pontovirtualacessos.Origem = "   ";
        // Act & Assert
        var exception = await Assert.ThrowsAsync<SGValidationException>(() => _validation.ValidateReg(pontovirtualacessos, _mockPontoVirtualAcessosService.Object, _mockOperadorReader.Object, _validUri, _mockConnection.Object));
        exception.Message.Should().Contain("é obrigatório");
    }

#endregion
#region Foreign Key Validation Tests - Operador
    [Fact]
    public async Task ValidateReg_WithInvalidOperador_ShouldThrowSGValidationException()
    {
        // Arrange
        var pontovirtualacessos = CreateValidPontoVirtualAcessos();
        pontovirtualacessos.Operador = 999;
        _mockOperadorReader.Setup(x => x.Read(999, _mockConnection.Object)).Returns(Task.FromResult<Models.Response.OperadorResponse>(null));
        SetupValidMocksInvalid();
        // Act & Assert
        var exception = await Assert.ThrowsAsync<SGValidationException>(() => _validation.ValidateReg(pontovirtualacessos, _mockPontoVirtualAcessosService.Object, _mockOperadorReader.Object, _validUri, _mockConnection.Object));
        exception.Message.Should().Contain("não encontrado");
    }

    [Fact]
    public async Task ValidateReg_WithMismatchedOperadorId_ShouldThrowSGValidationException()
    {
        // Arrange
        var pontovirtualacessos = CreateValidPontoVirtualAcessos();
        pontovirtualacessos.Operador = 999;
        var reg888 = new Models.Response.OperadorResponse
        {
            Id = 888
        }; // Different ID
        _mockOperadorReader.Setup(x => x.Read(999, _mockConnection.Object)).Returns(Task.FromResult(reg888));
        SetupValidMocksInvalid();
        // Act & Assert
        var exception = await Assert.ThrowsAsync<SGValidationException>(() => _validation.ValidateReg(pontovirtualacessos, _mockPontoVirtualAcessosService.Object, _mockOperadorReader.Object, _validUri, _mockConnection.Object));
        exception.Message.Should().Contain("não encontrado");
    }

    [Fact]
    public async Task ValidateReg_WithValidOperador_ShouldPass()
    {
        // Arrange
        var pontovirtualacessos = CreateValidPontoVirtualAcessos();
        pontovirtualacessos.Operador = 123;
        var reg123 = new Models.Response.OperadorResponse
        {
            Id = 123
        };
        _mockOperadorReader.Setup(x => x.Read(123, _mockConnection.Object)).Returns(Task.FromResult(reg123));
        SetupValidMocks();
        // Act
        var result = await _validation.ValidateReg(pontovirtualacessos, _mockPontoVirtualAcessosService.Object, _mockOperadorReader.Object, _validUri, _mockConnection.Object);
        // Assert
        result.Should().BeTrue();
    }

#endregion
    public virtual void Dispose()
    {
        _service?.Dispose();
    }
}