// 100% auto-generated by Source Genesys Core
// copyright © 2000-2025 Menphis - Sistemas Inteligentes
// This file is part of the Source Genesys project                     
// ReSharper disable once CheckNamespace
namespace MenphisSI.SG.GerAdv.DicInfo;
[Serializable]
public partial class DBGUTAtividadesMatrizODicInfo : IODicInfo
{
    public ImmutableArray<DBInfoSystem> IListFields() => List;
    public ImmutableArray<DBInfoSystem> IFieldsRaw() => ListWithoutAuditor;
    public ImmutableArray<DBInfoSystem> IPkFields() => ListPk();
    public ImmutableArray<DBInfoSystem> IPkIndexFields() => ListPkIndices();
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public string ITabelaNome() => DBGUTAtividadesMatrizDicInfo.TabelaNome;
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public string IFieldId() => DBGUTAtividadesMatrizDicInfo.CampoCodigo;
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public string ITypeFieldCode() => "int";
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public string IPrefix() => DBGUTAtividadesMatrizDicInfo.TablePrefix;
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public bool IdIsIdentity() => false;
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public bool HasAuditor() => true;
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public bool HasGuid() => true;
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public bool HasNameId() => false;
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public bool IsStoredProcedureOrView() => false;
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public bool IsView() => false;
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public string IFieldNameDescription() => DBGUTAtividadesMatrizDicInfo.CampoNome;
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public string NameSpace() => nameof(GerAdv);
    private static readonly FrozenDictionary<string, DBInfoSystem> _fieldLookup = List.ToFrozenDictionary(f => f.FNome, StringComparer.OrdinalIgnoreCase);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public DBInfoSystem? GetInfoSystemByNameField(string campo) => _fieldLookup.GetValueOrDefault(campo);
    public static string TCampoCodigo => DBGUTAtividadesMatrizDicInfo.CampoCodigo;
    public static string TCampoNome => DBGUTAtividadesMatrizDicInfo.CampoNome;
    public static string TTabelaNome => DBGUTAtividadesMatrizDicInfo.TabelaNome;
    public static string TTablePrefix => DBGUTAtividadesMatrizDicInfo.TablePrefix;
    public static ImmutableArray<DBInfoSystem> List => [DBGUTAtividadesMatrizDicInfo.AmgGUTMatriz, DBGUTAtividadesMatrizDicInfo.AmgGUTAtividade, DBGUTAtividadesMatrizDicInfo.AmgGuid, DBGUTAtividadesMatrizDicInfo.AmgQuemCad, DBGUTAtividadesMatrizDicInfo.AmgDtCad, DBGUTAtividadesMatrizDicInfo.AmgQuemAtu, DBGUTAtividadesMatrizDicInfo.AmgDtAtu, DBGUTAtividadesMatrizDicInfo.AmgVisto];
    public static ImmutableArray<DBInfoSystem> ListWithoutAuditor => [DBGUTAtividadesMatrizDicInfo.AmgGUTMatriz, DBGUTAtividadesMatrizDicInfo.AmgGUTAtividade, DBGUTAtividadesMatrizDicInfo.AmgGuid];

    public static ImmutableArray<DBInfoSystem> ListPk()
    {
        ImmutableArray<string> campos = ImmutableArray.CreateRange(["amgGUTAtividade", "amgGUTMatriz"]);
        var result = campos.Where(campo => !campo.Equals(DBGUTAtividadesMatrizDicInfo.CampoCodigo)).Select(campo => List.FirstOrDefault(t => t.FNome == campo)).Where(item => item != null).Cast<DBInfoSystem>().Distinct().ToList();
        return result.Count > 0 ? [..result] : [];
    }

    public static ImmutableArray<DBInfoSystem> ListPkIndices()
    {
        ImmutableArray<string> campos = ImmutableArray.CreateRange(["amgCodigo", "amgGUTAtividade", "amgGUTMatriz"]);
        var result = campos.Where(campo => !campo.Equals(DBGUTAtividadesMatrizDicInfo.CampoCodigo)).Select(campo => List.FirstOrDefault(t => t.FNome == campo)).Where(item => item != null).Cast<DBInfoSystem>().Distinct().ToList();
        return result.Count > 0 ? [..result] : [];
    }
}