// 100% auto-generated by Source Genesys WebApi Front & Back Creator
// copyright © 2000-2025 Menphis - Sistemas Inteligentes
// This file is part of the Source Genesys project                     
// Tracking: CrudInc.tsx.txt
'use client';
import React, { useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { EndTitApi } from '../../Apis/ApiEndTit';
import { useIsMobile } from '@/app/context/MobileContext';
import { useSystemContext } from '@/app/context/SystemContext';
import { NotificationService } from '@/app/services/notification.service';
import { NotificationComponent } from '@/app/components/Cruds/NotificationComponent';
import { IEndTitFormProps } from '../../Interfaces/interface.EndTit';
import { EndTitService } from '../../Services/EndTit.service';
import { useEndTitForm, useValidationsEndTit } from '../../Hooks/hookEndTit';
import { EndTitEmpty } from '../../../Models/EndTit';
import { EndTitForm } from '../Forms/EndTit';

const EndTitInc: React.FC<IEndTitFormProps> = ({ id, onClose, onError, onSuccess }) => {
  const { systemContext } = useSystemContext();
  const isMobile = useIsMobile();
  const router = useRouter();
  const endtitService = new EndTitService(
  new EndTitApi(systemContext?.Uri ?? '', systemContext?.Token ?? '')
);
const notificationService = new NotificationService();
const { data, handleChange, loadEndTit } = useEndTitForm(
EndTitEmpty(), 
endtitService
);
useEffect(() => {
  loadEndTit(id);
}, [id]);

const handleSubmit = async (e: React.FormEvent) => {
  e.preventDefault();
  try {
    const savedEndTit = await endtitService.saveEndTit(data);
    if (savedEndTit.id) {
      notificationService.showNotification('Registro salvo com sucesso!', 'success');
      const PDelayApiWrite = 333;
      setTimeout(() => {
        if (onSuccess) {
          onSuccess(savedEndTit);
        }
      }, PDelayApiWrite);
    } else {
    if (onError) {
      onError();
    }
    notificationService.showNotification('Error salvando registro.', 'error');
  }
} catch (error) {
if (onError) {
  onError();
}
notificationService.showNotification('Error salvando registro.', 'error');
}
};
const handleReload = () => {
  loadEndTit(id);
};
return (
<>
<NotificationComponent notificationService={notificationService} />
<EndTitForm
endtitData={data}
onChange={handleChange}
onSubmit={handleSubmit}
onClose={onClose}
onError={onError}
onReload={handleReload}
onSuccess={onSuccess}
/>
</>
);
};
export default EndTitInc;