// 100% auto-generated by Source Genesys WebApi Front & Back Creator
// copyright © 2000-2026 Menphis - Sistemas Inteligentes
// This file is part of the Source Genesys project
// Source:ReadersGenerator
namespace MenphisSI.GerAdv.Interface.Readers;
public partial interface ITipoRecursoReader
{
    Task<TipoRecursoResponse?> ReadAsync(int id, MsiSqlConnection? oCnn);
    Task<Models.TipoRecurso?> ReadMAsync(int id, MsiSqlConnection? oCnn);
    TipoRecursoResponse? Read(FTipoRecurso dbRec, MsiSqlConnection? oCnn);
    TipoRecursoResponse? Read(string where, List<SqlParameter>? parameters, MsiSqlConnection? oCnn);
    TipoRecursoResponse? Read(FTipoRecurso dbRec);
    Task<string> ReadStringAuditorAsync(int id, string uri, MsiSqlConnection? oCnn);
    Task<AuditorResponse?> ReadAuditorAsync(int id, string uri, MsiSqlConnection? oCnn);
    Task<string> ReadStringAuditorAsync(string uri, MsiSqlConnection? oCnn, IHybridCache cache);
    TipoRecursoResponseAll? ReadAll(FTipoRecurso dbRec, IDataRecord dr);
    TipoRecursoResponseAll? ReadAll(SG.GerAdv.DBTipoRecurso dbRec, DataRow dr);
    Task<IEnumerable<DBNomeID>?> ListarNAsync(int max, string uri, string cWhere, List<SqlParameter>? parameters, string order);
    Task<IEnumerable<TipoRecursoResponseAll>> ListarAsync(MsiSqlConnection oCnn, int max, string uri, string cWhere, List<SqlParameter>? parameters, string order, CancellationToken cancellationToken);
}