// 100% auto-generated by Source Genesys WebApi Front & Back Creator
// copyright © 2000-2025 Menphis - Sistemas Inteligentes
// This file is part of the Source Genesys project                     
namespace MenphisSI.GerAdv.Factory
{
    /// <summary>
    /// Factory interface for creating FViaRecebimento instances in a DI-compatible way
    /// </summary>
    public interface IFViaRecebimentoFactory
    {
        /// <summary>
        /// Creates a new FViaRecebimento instance
        /// </summary>
        FViaRecebimento Create();
        /// <summary>
        /// Creates a FViaRecebimento instance from SqlDataReader
        /// </summary>
        FViaRecebimento CreateFromReader(SqlDataReader? dbRec);
        /// <summary>
        /// Creates a FViaRecebimento instance from DataRow
        /// </summary>
        FViaRecebimento CreateFromDataRow(DataRow? dbRec);
        /// <summary>
        /// Creates a FViaRecebimento instance with parameters
        /// </summary>
        FViaRecebimento CreateFromParameters(List<SqlParameter>? parameters, MsiSqlConnection? oCnn, in string? cNome = "", string? fullSql = "", string sqlWhere = "", in string join = "");
        Task<FViaRecebimento> CreateAsync();
        Task<FViaRecebimento> CreateFromIdAsync(int id, MsiSqlConnection? oCnn);
        Task DeleteAsync(int operadorId, int id, MsiSqlConnection? oCnn);
    }
}