// 100% auto-generated by Source Genesys WebApi Front & Back Creator
// copyright © 2000-2025 Menphis - Sistemas Inteligentes
// This file is part of the Source Genesys project                     
#pragma warning disable IDE0130 // Namespace does not match folder structure

namespace MenphisSI.GerAdv.Services;
#pragma warning restore IDE0130 // Namespace does not match folder structure

public partial class ObjetosService(IOptions<AppSettings> appSettings, IFObjetosFactory objetosFactory, IObjetosReader reader, IObjetosValidation validation, IObjetosWriter writer, IJusticaReader justicaReader, IAreaReader areaReader, IHttpContextAccessor httpContextAccessor, IHybridCache cache, IMemoryCache memory, IConnectionService connectionService, IGenericVoiceFilterService<Filters.FilterObjetos> voiceFilterService, IServicesFilter serviceFilter, IEntityService entityService) : IObjetosService, IDisposable
{
    private readonly IHttpContextAccessor _httpContextAccessor = httpContextAccessor;
    private readonly IOptions<AppSettings> _appSettings = appSettings;
    private readonly IHybridCache _cache = cache;
    private readonly IMemoryCache _memoryCache = memory ?? throw new ArgumentNullException(nameof(memory));
    private readonly IConnectionService _connectionService = connectionService ?? throw new ArgumentNullException(nameof(connectionService));
    private readonly IGenericVoiceFilterService<Filters.FilterObjetos> _voiceFilterService = voiceFilterService ?? throw new ArgumentNullException(nameof(voiceFilterService));
    private readonly IServicesFilter servicesFilter = serviceFilter ?? throw new ArgumentNullException(nameof(serviceFilter));
    private bool _disposed;
    private readonly IEntityService _entityService = entityService;
    private readonly IFObjetosFactory objetosFactory = objetosFactory;
    private readonly IObjetosReader reader = reader;
    private readonly IObjetosValidation validation = validation;
    private readonly IObjetosWriter writer = writer;
    private readonly IJusticaReader justicaReader = justicaReader;
    private readonly IAreaReader areaReader = areaReader;
    public async Task<IEnumerable<ObjetosResponseAll>> Filter([FromQuery] int max, [FromBody] Filters.FilterObjetos filtro, [FromRoute, Required] string uri)
    {
        ThrowIfDisposed();
        if (!(await Uris.ValidaUriAsync(uri, _entityService)))
        {
            throw new Exception("Objetos: URI inválida");
        }

        using var scope = _connectionService.CreateConnectionScope(uri);
        using var oCnn = scope.Connection ?? throw new DatabaseConnectionException();
        if (max <= 0)
        {
            max = BaseConsts.PMaxItens;
        }

#pragma warning disable CS0168 // Variable is declared but never used

        try
        {
            var filtroResult = filtro == null ? null : servicesFilter.WFiltroObjetos(filtro!);
            string where = filtroResult?.where ?? string.Empty;
            List<SqlParameter>? parameters = filtroResult?.parametros ?? [];
            var filterHash = GenericVoiceFilterService<Filters.FilterObjetos>.GetFilterHash(filtro);
            var keyCache = await reader.ReadStringAuditorAsync(max, uri, where, parameters, oCnn);
            var cacheKey = $"{uri}-{max}Objetos-Filter-{where.GetHashCode2()}{filterHash}{keyCache}";
            var entryOptions = new HybridCacheEntryOptions
            {
                Expiration = TimeSpan.FromSeconds(BaseConsts.PMaxGetListSecondsCacheId),
                LocalCacheExpiration = TimeSpan.FromSeconds(BaseConsts.PMaxGetListSecondsCacheId)
            };
            var result = await _cache.GetOrCreateAsync(cacheKey, async cancel => await GetDataAllAsync(max, string.IsNullOrEmpty(where) ? string.Empty : TSql.Where + where, parameters, uri, cancel), entryOptions, cancellationToken: CancellationToken.None);
            return result;
        }
        catch (Exception ex)
        {
            // _logger.Error(ex, ex.Message); // TODO
            throw new Exception($"Objetos - error on filtering.");
        }
#pragma warning restore CS0168 // Variable is declared but never used

    }

    public async Task<Filters.FilterObjetos> FilterVoice([FromBody] Filters.FilterObjetos filtro, [FromBody] CommandSpeakerRequest? message, [FromRoute, Required] string uri)
    {
        ThrowIfDisposed();
        if (!(await Uris.ValidaUriAsync(uri, _entityService)))
        {
            throw new Exception("Objetos: URI inválida");
        }

        try
        {
            // Se há mensagem de comando de voz, processar via OpenAI
            Filters.FilterObjetos? filtroProcessado = filtro;
            if (message != null && !string.IsNullOrWhiteSpace(message.Message))
            {
                filtro = filtro ?? new Filters.FilterObjetos();
                filtroProcessado = await ProcessFilterVoiceCommandAsync(message, filtro, uri);
            }

            return filtroProcessado ?? new Filters.FilterObjetos();
        }
        catch (Exception)
        {
            // _logger.Error(ex, ex.Message); // TODO
            throw new Exception($"Objetos - error on creating filter.");
        }
    }

    public async Task<ObjetosResponse?> GetById([FromQuery] int id, [FromRoute, Required] string uri, CancellationToken token)
    {
        ThrowIfDisposed();
        if (id < 1)
        {
            return new ObjetosResponse();
        }

        var entryOptions = new HybridCacheEntryOptions
        {
            Expiration = TimeSpan.FromSeconds(BaseConsts.PMaxSecondsCacheId),
            LocalCacheExpiration = TimeSpan.FromSeconds(BaseConsts.PMaxSecondsCacheId)
        };
        using var scope = _connectionService.CreateConnectionScope(uri);
        using var oCnn = scope.Connection ?? throw new DatabaseConnectionException();
        try
        {
            var keyCache = await reader.ReadStringAuditorAsync(id, uri, oCnn);
            var result = await _cache.GetOrCreateAsync($"{uri}-Objetos-GetById-{id}-{keyCache}", async cancel => await GetDataByIdAsync(id, oCnn, cancel), entryOptions, cancellationToken: token);
            return result;
        }
        catch (Exception)
        {
            throw new Exception($"Objetos - {uri}-: GetById");
        }
    }

    private async Task<ObjetosResponse?> GetDataByIdAsync(int id, MsiSqlConnection? oCnn, CancellationToken token) => await reader.ReadAsync(id, oCnn);
    public async Task<AuditorResponse?> GetAuditor([FromQuery] int id, [FromRoute, Required] string uri, CancellationToken token)
    {
        ThrowIfDisposed();
        AuditorResponse? result = null;
        if (id < 1)
        {
            return result;
        }

        using var scope = _connectionService.CreateConnectionScope(uri);
        using var oCnn = scope.Connection ?? throw new DatabaseConnectionException();
        try
        {
            result = await reader.ReadAuditorAsync(id, uri, oCnn);
            return result;
        }
        catch (Exception)
        {
            throw new Exception($"Objetos - {uri}-: GetAuditor");
        }
    }

    public async Task<ObjetosResponse?> AddAndUpdate([FromBody] Models.Objetos? regObjetos, [FromRoute, Required] string uri)
    {
        ThrowIfDisposed();
        if (regObjetos == null)
        {
            return null;
        }

        if (!(await Uris.ValidaUriAsync(uri, _entityService)))
        {
            throw new Exception("Objetos: URI inválida");
        }

        using var scope = _connectionService.CreateConnectionScopeRw(uri);
        using var oCnn = scope.Connection ?? throw new DatabaseConnectionException();
        if (oCnn == null)
        {
            return null;
        }

        try
        {
            var validade = await validation.ValidateReg(regObjetos, this, justicaReader, areaReader, uri, oCnn);
            if (!validade)
            {
                throw new Exception("Erro inesperado ao validar 0x0!");
            }
        }
        catch (SGValidationException ex)
        {
            throw new Exception(ex.Message);
        }
        catch (Exception)
        {
            throw new Exception("Erro inesperado ao validar 0x1!");
        }

        int operadorId = UserTools.GetAuthenticatedUserId(_httpContextAccessor);
        using var saved = await writer.WriteAsync(regObjetos, operadorId, oCnn);
        return reader.Read(saved, oCnn);
    }

    public async Task<ObjetosResponse?> Validation([FromBody] Models.Objetos? regObjetos, [FromRoute, Required] string uri)
    {
        ThrowIfDisposed();
        if (regObjetos == null)
        {
            return null;
        }

        if (!(await Uris.ValidaUriAsync(uri, _entityService)))
        {
            throw new Exception("Objetos: URI inválida");
        }

        using var scope = _connectionService.CreateConnectionScopeRw(uri);
        using var oCnn = scope.Connection ?? throw new DatabaseConnectionException();
        if (oCnn == null)
        {
            return null;
        }

        try
        {
            var validade = await validation.ValidateReg(regObjetos, this, justicaReader, areaReader, uri, oCnn);
            if (!validade)
            {
                throw new Exception("Erro inesperado ao validar 0x0!");
            }
        }
        catch (SGValidationException ex)
        {
            throw new Exception(ex.Message);
        }
        catch (Exception)
        {
            throw new Exception("Erro inesperado ao validar 0x1!");
        }

        if (regObjetos.Id.IsEmptyIDNumber())
        {
            return new ObjetosResponse();
        }

        return await reader.ReadAsync(regObjetos.Id, oCnn);
    }

    public async Task<ObjetosResponse?> Delete([FromQuery] int? id, [FromRoute, Required] string uri)
    {
        if (id == null || id.IsEmptyIDNumber())
        {
            return null;
        }

        ThrowIfDisposed();
        if (!(await Uris.ValidaUriAsync(uri, _entityService)))
        {
            throw new Exception("Objetos: URI inválida");
        }

        var nOperador = UserTools.GetAuthenticatedUserId(_httpContextAccessor);
        using var scope = _connectionService.CreateConnectionScopeRw(uri);
        using var oCnn = scope.Connection ?? throw new DatabaseConnectionException();
        if (oCnn == null)
        {
            return null;
        }

        try
        {
            var deleteValidation = await validation.CanDelete(id, this, uri, oCnn);
            if (!deleteValidation)
            {
                throw new Exception("Erro inesperado ao validar 0x0!");
            }
        }
        catch (SGValidationException ex)
        {
            throw new Exception(ex.Message);
        }
        catch (Exception)
        {
            throw new Exception("Erro inesperado ao validar 0x1!");
        }

        var objetos = await reader.ReadAsync(id ?? default, oCnn);
        try
        {
            if (objetos != null)
            {
                await writer.DeleteAsync(objetos, nOperador, oCnn);
                if (_memoryCache is MemoryCache memCache)
                {
                    memCache.Compact(1.0);
                }
            }
        }
        catch (Exception ex)
        {
            throw new Exception(ex.Message);
        }

        return objetos;
    }

    public virtual void Dispose()
    {
        Dispose(true);
        GC.SuppressFinalize(this);
    }

    protected virtual void Dispose(bool disposing)
    {
        if (_disposed)
            return;
        if (disposing)
        {
        //_cache?.Dispose();
        }

        _disposed = true;
    }

    private void ThrowIfDisposed()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
    }
}