// 100% auto-generated by Source Genesys Core
// copyright © 2000-2026 Menphis - Sistemas Inteligentes
// This file is part of the Source Genesys project                     
namespace MenphisSI.SG.GerAdv;
// ReSharper disable once InconsistentNaming 1
public partial class DBPreClientes
{
    public DBPreClientes(DataRow? dbRec)
    {
        if (dbRec is null)
            return;
        InitFromRecord(name =>
        {
            try
            {
                return dbRec[name];
            }
            catch
            {
                return DBNull.Value;
            }
        });
    }

    public DBPreClientes(SqlDataReader? dbRec)
    {
        if (dbRec is null)
            return;
        try
        {
            InitFromRecord(name =>
            {
                try
                {
                    return dbRec[name];
                }
                catch
                {
                    return DBNull.Value;
                }
            });
        }
        catch (Exception ex)
        {
            throw new Exception($"Erro ao carregar dados do PreClientes: {ex.Message}", ex);
        }
    }

    private void InitFromRecord(Func<string, object?> getValue)
    {
        if (DBNull.Value.Equals(getValue(CampoCodigo)))
            return;
        ID = Convert.ToInt32(getValue(CampoCodigo));
        // Checkpoint Carregar 
        try
        {
            FAssCPF = getValue(DBPreClientesDicInfo.AssCPF)?.ToString() ?? string.Empty;
        }
        catch
        {
        }

        try
        {
            FAssEndereco = getValue(DBPreClientesDicInfo.AssEndereco)?.ToString() ?? string.Empty;
        }
        catch
        {
        }

        try
        {
            FAssistido = getValue(DBPreClientesDicInfo.Assistido)?.ToString() ?? string.Empty;
        }
        catch
        {
        }

        try
        {
            FAssRG = getValue(DBPreClientesDicInfo.AssRG)?.ToString() ?? string.Empty;
        }
        catch
        {
        }

        try
        {
            FBairro = getValue(DBPreClientesDicInfo.Bairro)?.ToString() ?? string.Empty;
        }
        catch
        {
        }

        try
        {
            FCEP = getValue(DBPreClientesDicInfo.CEP)?.ToString() ?? string.Empty;
        }
        catch
        {
        }

        try
        {
            FClass = getValue(DBPreClientesDicInfo.Class)?.ToString() ?? string.Empty;
        }
        catch
        {
        }

        try
        {
            FCNH = getValue(DBPreClientesDicInfo.CNH)?.ToString() ?? string.Empty;
        }
        catch
        {
        }

        try
        {
            FCNPJ = getValue(DBPreClientesDicInfo.CNPJ)?.ToString() ?? string.Empty;
        }
        catch
        {
        }

        try
        {
            FCPF = getValue(DBPreClientesDicInfo.CPF)?.ToString() ?? string.Empty;
        }
        catch
        {
        }

        try
        {
            FEMail = getValue(DBPreClientesDicInfo.EMail)?.ToString() ?? string.Empty;
        }
        catch
        {
        }

        try
        {
            FEndereco = getValue(DBPreClientesDicInfo.Endereco)?.ToString() ?? string.Empty;
        }
        catch
        {
        }

        try
        {
            FFax = getValue(DBPreClientesDicInfo.Fax)?.ToString() ?? string.Empty;
        }
        catch
        {
        }

        try
        {
            FFone = getValue(DBPreClientesDicInfo.Fone)?.ToString() ?? string.Empty;
        }
        catch
        {
        }

        try
        {
            FHomePage = getValue(DBPreClientesDicInfo.HomePage)?.ToString() ?? string.Empty;
        }
        catch
        {
        }

        try
        {
            FInscEst = getValue(DBPreClientesDicInfo.InscEst)?.ToString() ?? string.Empty;
        }
        catch
        {
        }

        try
        {
            FNome = getValue(DBPreClientesDicInfo.Nome)?.ToString() ?? string.Empty;
        }
        catch
        {
        }

        try
        {
            FNomeFantasia = getValue(DBPreClientesDicInfo.NomeFantasia)?.ToString() ?? string.Empty;
        }
        catch
        {
        }

        try
        {
            FObservacao = getValue(DBPreClientesDicInfo.Observacao)?.ToString() ?? string.Empty;
        }
        catch
        {
        }

        try
        {
            FQualificacao = getValue(DBPreClientesDicInfo.Qualificacao)?.ToString() ?? string.Empty;
        }
        catch
        {
        }

        try
        {
            FQuemIndicou = getValue(DBPreClientesDicInfo.QuemIndicou)?.ToString() ?? string.Empty;
        }
        catch
        {
        }

        try
        {
            FRG = getValue(DBPreClientesDicInfo.RG)?.ToString() ?? string.Empty;
        }
        catch
        {
        }

        try
        {
            if (!DBNull.Value.Equals(getValue(DBPreClientesDicInfo.Adv)))
                FAdv = Convert.ToInt32(getValue(DBPreClientesDicInfo.Adv));
        }
        catch
        {
        }

        try
        {
            if (!DBNull.Value.Equals(getValue(DBPreClientesDicInfo.Ani)))
                FAni = Convert.ToBoolean(getValue(DBPreClientesDicInfo.Ani));
        }
        catch
        {
        }

        try
        {
            if (!DBNull.Value.Equals(getValue(DBPreClientesDicInfo.Bold)))
                FBold = Convert.ToBoolean(getValue(DBPreClientesDicInfo.Bold));
        }
        catch
        {
        }

        try
        {
            if (!DBNull.Value.Equals(getValue(DBPreClientesDicInfo.Cidade)))
                FCidade = Convert.ToInt32(getValue(DBPreClientesDicInfo.Cidade));
        }
        catch
        {
        }

        try
        {
            if (!DBNull.Value.Equals(getValue(DBPreClientesDicInfo.Data)))
                FData = DateOnly.FromDateTime(Convert.ToDateTime(getValue(DBPreClientesDicInfo.Data)));
        }
        catch
        {
        }

        try
        {
            if (!DBNull.Value.Equals(getValue(DBPreClientesDicInfo.DtAtu)))
                m_FDtAtu = Convert.ToDateTime(getValue(DBPreClientesDicInfo.DtAtu));
        }
        catch
        {
        }

        try
        {
            if (!DBNull.Value.Equals(getValue(DBPreClientesDicInfo.DtCad)))
                m_FDtCad = Convert.ToDateTime(getValue(DBPreClientesDicInfo.DtCad));
        }
        catch
        {
        }

        try
        {
            if (!DBNull.Value.Equals(getValue(DBPreClientesDicInfo.DtNasc)))
                FDtNasc = DateOnly.FromDateTime(Convert.ToDateTime(getValue(DBPreClientesDicInfo.DtNasc)));
        }
        catch
        {
        }

        try
        {
            if (!DBNull.Value.Equals(getValue(DBPreClientesDicInfo.Etiqueta)))
                FEtiqueta = Convert.ToBoolean(getValue(DBPreClientesDicInfo.Etiqueta));
        }
        catch
        {
        }

        try
        {
            if (!DBNull.Value.Equals(getValue(DBPreClientesDicInfo.Idade)))
                FIdade = Convert.ToInt32(getValue(DBPreClientesDicInfo.Idade));
        }
        catch
        {
        }

        try
        {
            if (!DBNull.Value.Equals(getValue(DBPreClientesDicInfo.IDRep)))
                FIDRep = Convert.ToInt32(getValue(DBPreClientesDicInfo.IDRep));
        }
        catch
        {
        }

        try
        {
            if (!DBNull.Value.Equals(getValue(DBPreClientesDicInfo.Inativo)))
                FInativo = Convert.ToBoolean(getValue(DBPreClientesDicInfo.Inativo));
        }
        catch
        {
        }

        try
        {
            if (!DBNull.Value.Equals(getValue(DBPreClientesDicInfo.Juridica)))
                FJuridica = Convert.ToBoolean(getValue(DBPreClientesDicInfo.Juridica));
        }
        catch
        {
        }

        try
        {
            if (!DBNull.Value.Equals(getValue(DBPreClientesDicInfo.QuemAtu)))
                FQuemAtu = Convert.ToInt32(getValue(DBPreClientesDicInfo.QuemAtu));
        }
        catch
        {
        }

        try
        {
            if (!DBNull.Value.Equals(getValue(DBPreClientesDicInfo.QuemCad)))
                FQuemCad = Convert.ToInt32(getValue(DBPreClientesDicInfo.QuemCad));
        }
        catch
        {
        }

        try
        {
            if (!DBNull.Value.Equals(getValue(DBPreClientesDicInfo.Sexo)))
                FSexo = Convert.ToBoolean(getValue(DBPreClientesDicInfo.Sexo));
        }
        catch
        {
        }

        try
        {
            if (!DBNull.Value.Equals(getValue(DBPreClientesDicInfo.Tipo)))
                FTipo = Convert.ToBoolean(getValue(DBPreClientesDicInfo.Tipo));
        }
        catch
        {
        }

        try
        {
            if (!DBNull.Value.Equals(getValue(DBPreClientesDicInfo.TipoCaptacao)))
                FTipoCaptacao = Convert.ToBoolean(getValue(DBPreClientesDicInfo.TipoCaptacao));
        }
        catch
        {
        }

        try
        {
            if (!DBNull.Value.Equals(getValue(DBPreClientesDicInfo.Visto)))
                FVisto = Convert.ToBoolean(getValue(DBPreClientesDicInfo.Visto));
        }
        catch
        {
        }
    }

    public void LoadDataBd(DataRow? dbRec)
    {
        if (dbRec is null)
            return;
        try
        {
            InitFromRecord(name =>
            {
                try
                {
                    return dbRec[name];
                }
                catch
                {
                    return DBNull.Value;
                }
            });
        }
        catch (Exception ex)
        {
            throw new Exception($"Erro ao carregar dados do PreClientes: {ex.Message}", ex);
        }
    }

    public void LoadDataBd(SqlDataReader? dbRec)
    {
        if (dbRec is null)
            return;
        try
        {
            InitFromRecord(name =>
            {
                try
                {
                    return dbRec[name];
                }
                catch
                {
                    return DBNull.Value;
                }
            });
        }
        catch (Exception ex)
        {
            throw new Exception($"Erro ao carregar dados do PreClientes: {ex.Message}", ex);
        }
    }
}