// 100% auto-generated by Source Genesys WebApi Front & Back Creator
// copyright © 2000-2025 Menphis - Sistemas Inteligentes
// This file is part of the Source Genesys project                     
#pragma warning disable IDE0130 // Namespace does not match folder structure

namespace MenphisSI.GerAdv.Wheres;
#pragma warning restore IDE0130 // Namespace does not match folder structure

public partial interface IAgendaSemanaWhere
{
    AgendaSemanaResponse Read(string where, List<SqlParameter>? parameters, MsiSqlConnection? oCnn);
}

public partial class AgendaSemanaWhere(IFAgendaSemanaFactory agendasemanaFactory) : IAgendaSemanaWhere
{
    private readonly IFAgendaSemanaFactory _agendasemanaFactory = agendasemanaFactory ?? throw new ArgumentNullException(nameof(agendasemanaFactory));
    public AgendaSemanaResponse Read(string where, List<SqlParameter>? parameters, MsiSqlConnection? oCnn)
    {
        using var dbRec = _agendasemanaFactory.CreateFromParameters(parameters, oCnn, sqlWhere: where);
        var agendasemana = new AgendaSemanaResponse
        {
            Id = dbRec.ID,
            ParaNome = dbRec.FParaNome ?? string.Empty,
            Data = dbRec.FData ?? string.Empty,
            Funcionario = dbRec.FFuncionario,
            Advogado = dbRec.FAdvogado,
            Hora = dbRec.FHora ?? string.Empty,
            TipoCompromisso = dbRec.FTipoCompromisso,
            Compromisso = dbRec.FCompromisso ?? string.Empty,
            Concluido = dbRec.FConcluido,
            Liberado = dbRec.FLiberado,
            Importante = dbRec.FImportante,
            HoraFinal = dbRec.FHoraFinal ?? string.Empty,
            Nome = dbRec.FNome ?? string.Empty,
            Cliente = dbRec.FCliente,
            NomeCliente = dbRec.FNomeCliente ?? string.Empty,
            Tipo = dbRec.FTipo ?? string.Empty,
        };
        return agendasemana;
    }
}