// 100% auto-generated by Source Genesys WebApi Front & Back Creator
// copyright © 2000-2025 Menphis - Sistemas Inteligentes
// This file is part of the Source Genesys project                     
#pragma warning disable IDE0130 // Namespace does not match folder structure

namespace MenphisSI.GerAdv.Validations;
#pragma warning restore IDE0130 // Namespace does not match folder structure

public partial interface IPaisesValidation
{
    Task<bool> ValidateReg(Models.Paises reg, IPaisesService service, [FromRoute, Required] string uri, MsiSqlConnection oCnn);
    Task<bool> CanDelete(int id, IPaisesService service, IUFService ufService, [FromRoute, Required] string uri, MsiSqlConnection oCnn);
}

public class PaisesValidation : IPaisesValidation
{
    public async Task<bool> CanDelete(int id, IPaisesService service, IUFService ufService, [FromRoute, Required] string uri, MsiSqlConnection oCnn)
    {
        if (id <= 0)
            throw new SGValidationException("Id inválido");
        var reg = await service.GetById(id, uri, default);
        if (reg == null)
            throw new SGValidationException($"Registro com id {id} não encontrado.");
        var ufExists0 = await ufService.Filter(new Filters.FilterUF { Pais = id }, uri);
        if (ufExists0 != null && ufExists0.Any())
            throw new SGValidationException("Não é possível excluir o registro, pois existem registros da tabela UF associados a ele.");
        return true;
    }

    private bool ValidSizes(Models.Paises reg)
    {
        if (reg.Nome.Length > 80)
            throw new SGValidationException($"Nome deve ter no máximo 80 caracteres.");
        if (reg.GUID.Length > 100)
            throw new SGValidationException($"GUID deve ter no máximo 100 caracteres.");
        return true;
    }

    public async Task<bool> ValidateReg(Models.Paises reg, IPaisesService service, [FromRoute, Required] string uri, MsiSqlConnection oCnn)
    {
        if (reg == null)
            throw new SGValidationException("Objeto está nulo");
        if (string.IsNullOrWhiteSpace(reg.Nome))
            throw new SGValidationException("Nome é obrigatório");
        var validSizes = ValidSizes(reg);
        if (!validSizes)
            return false;
        await Task.Delay(0);
        return true;
    }
}