// 100% auto-generated by Source Genesys WebApi Front & Back Creator
// copyright © 2000-2025 Menphis - Sistemas Inteligentes
// This file is part of the Source Genesys project                     
#pragma warning disable IDE0130 // Namespace does not match folder structure

namespace MenphisSI.GerAdv.Models.Response
{
#pragma warning restore IDE0130 // Namespace does not match folder structure

    [Serializable]
    public record OperadoresResponse
    {
        [JsonPropertyName("id")]
        public int Id { get; set; }

        /// <summary>
        /// Cliente - operCliente  
        /// </summary>
        [JsonPropertyName("cliente")]
        public int Cliente { get; set; }

        /// <summary>
        /// Enviado - operEnviado  
        /// </summary>
        [JsonPropertyName("enviado")]
        public bool Enviado { get; set; }

        /// <summary>
        /// Casa - operCasa  
        /// </summary>
        [JsonPropertyName("casa")]
        public bool Casa { get; set; }

        /// <summary>
        /// CasaID - operCasaID  
        /// </summary>
        [JsonPropertyName("casaid")]
        public int CasaID { get; set; }

        /// <summary>
        /// CasaCodigo - operCasaCodigo  
        /// </summary>
        [JsonPropertyName("casacodigo")]
        public int CasaCodigo { get; set; }

        /// <summary>
        /// IsNovo - operIsNovo  
        /// </summary>
        [JsonPropertyName("isnovo")]
        public bool IsNovo { get; set; }

        /// <summary>
        /// Grupo - operGrupo  
        /// </summary>
        [JsonPropertyName("grupo")]
        public int Grupo { get; set; }

        /// <summary>
        /// Nome - operNome - tamanho máximo: 50 
        /// </summary>
        [JsonPropertyName("nome")]
        public string Nome { get; set; } = "";

        /// <summary>
        /// EMail - operEMail - tamanho máximo: 150 
        /// </summary>
        [JsonPropertyName("email")]
        public string EMail { get; set; } = "";

        /// <summary>
        /// Ativado - operAtivado  
        /// </summary>
        [JsonPropertyName("ativado")]
        public bool Ativado { get; set; }

        /// <summary>
        /// SuporteMaxAge - operSuporteMaxAge  
        /// </summary>
        [JsonPropertyName("suportemaxage")]
        public string SuporteMaxAge { get; set; } = "";

        [JsonPropertyName("suportemaxage_date")]
        public DateTime? SuporteMaxAge_date { get; set; }
    }
}

namespace MenphisSI.GerAdv.Models.Response.All
{
    [Serializable]
    public record OperadoresResponseAll
    {
        [JsonPropertyName("id")]
        public int Id { get; set; }

        /// <summary>
        /// Cliente - operCliente  
        /// </summary>
        [JsonPropertyName("cliente")]
        public int Cliente { get; set; }

        /// <summary>
        /// Enviado - operEnviado  
        /// </summary>
        [JsonPropertyName("enviado")]
        public bool Enviado { get; set; }

        /// <summary>
        /// Casa - operCasa  
        /// </summary>
        [JsonPropertyName("casa")]
        public bool Casa { get; set; }

        /// <summary>
        /// CasaID - operCasaID  
        /// </summary>
        [JsonPropertyName("casaid")]
        public int CasaID { get; set; }

        /// <summary>
        /// CasaCodigo - operCasaCodigo  
        /// </summary>
        [JsonPropertyName("casacodigo")]
        public int CasaCodigo { get; set; }

        /// <summary>
        /// IsNovo - operIsNovo  
        /// </summary>
        [JsonPropertyName("isnovo")]
        public bool IsNovo { get; set; }

        /// <summary>
        /// Grupo - operGrupo  
        /// </summary>
        [JsonPropertyName("grupo")]
        public int Grupo { get; set; }

        /// <summary>
        /// Nome - operNome - tamanho máximo: 50 
        /// </summary>
        [JsonPropertyName("nome")]
        public string Nome { get; set; } = "";

        /// <summary>
        /// EMail - operEMail - tamanho máximo: 150 
        /// </summary>
        [JsonPropertyName("email")]
        public string EMail { get; set; } = "";

        /// <summary>
        /// Ativado - operAtivado  
        /// </summary>
        [JsonPropertyName("ativado")]
        public bool Ativado { get; set; }

        /// <summary>
        /// SuporteMaxAge - operSuporteMaxAge  
        /// </summary>
        [JsonPropertyName("suportemaxage")]
        public string SuporteMaxAge { get; set; } = "";

        [JsonPropertyName("suportemaxage_date")]
        public DateTime? SuporteMaxAge_date { get; set; }

        [JsonPropertyName("nomeclientes")]
        public string NomeClientes { get; set; } = string.Empty;
    }
}