// 100% auto-generated by Source Genesys WebApi Front & Back Creator
// copyright © 2000-2025 Menphis - Sistemas Inteligentes
// This file is part of the Source Genesys project

/* istanbul ignore file */

import {
  FilterPosicaoOutrasPartes,
  FilterPosicaoOutrasPartesDefaults,
} from "../../PosicaoOutrasPartes/Filters/PosicaoOutrasPartes";
import {
  FilterCidade,
  FilterCidadeDefaults,
} from "../../Cidade/Filters/Cidade";

export interface FilterTerceiros {
  filterPosicaoOutrasPartes: FilterPosicaoOutrasPartes;
  filterCidade: FilterCidade;

  logicalOperator?: string;
  wildcardChar?: string;
  processo?: number;
  processo_end?: number;
  nome?: string;
  situacao?: number;
  situacao_end?: number;
  cidade?: number;
  cidade_end?: number;
  endereco?: string;
  bairro?: string;
  cep?: string;
  fone?: string;
  fax?: string;
  obs?: string;
  email?: string;
  class?: string;
  varaforocomarca?: string;
  sexo?: number;
  bold?: number;
  guid?: string;
  quemcad?: number;
  quemcad_end?: number;
  dtcad_end?: string;
  dtcad?: string;
  quematu?: number;
  quematu_end?: number;
  dtatu_end?: string;
  dtatu?: string;
  visto?: number;
  codigo_filtro?: number;
  codigo_filtro_end?: number;
}

export class FilterTerceirosDefaults implements FilterTerceiros {
  filterPosicaoOutrasPartes: FilterPosicaoOutrasPartes =
    new FilterPosicaoOutrasPartesDefaults();
  filterCidade: FilterCidade = new FilterCidadeDefaults();

  logicalOperator?: string = " AND ";
  wildcardChar?: string = "%";
  processo?: number = -2147483648;
  processo_end?: number = -2147483648;
  nome?: string = "";
  situacao?: number = -2147483648;
  situacao_end?: number = -2147483648;
  cidade?: number = -2147483648;
  cidade_end?: number = -2147483648;
  endereco?: string = "";
  bairro?: string = "";
  cep?: string = "";
  fone?: string = "";
  fax?: string = "";
  obs?: string = "";
  email?: string = "";
  class?: string = "";
  varaforocomarca?: string = "";
  sexo?: number = -2147483648;
  bold?: number = -2147483648;
  guid?: string = "";
  quemcad?: number = -2147483648;
  quemcad_end?: number = -2147483648;
  dtcad_end?: string = "";
  dtcad?: string = "";
  quematu?: number = -2147483648;
  quematu_end?: number = -2147483648;
  dtatu_end?: string = "";
  dtatu?: string = "";
  visto?: number = -2147483648;
  codigo_filtro?: number = -2147483648;
  codigo_filtro_end?: number = -2147483648;
}
