// 100% auto-generated by Source Genesys WebApi Front & Back Creator
// copyright © 2000-2026 Menphis - Sistemas Inteligentes
// This file is part of the Source Genesys project
// Tabela:PosicaoOutrasPartes
// Fonte:ServiceGenerator
namespace MenphisSI.GerAdv.Services;
public partial class PosicaoOutrasPartesService(IOptions<AppSettings> appSettings, IFPosicaoOutrasPartesFactory posicaooutraspartesFactory, IPosicaoOutrasPartesReader reader, IPosicaoOutrasPartesValidation validation, IPosicaoOutrasPartesWriter writer, ITerceirosService terceirosService, IHttpContextAccessor httpContextAccessor, IHybridCache cache, IMemoryCache memory, IConnectionService connectionService, IGenericVoiceFilterService<Filters.FilterPosicaoOutrasPartes> voiceFilterService, IServicesFilter serviceFilter, IEntityService entityService) : IPosicaoOutrasPartesService, IDisposable
{
    private readonly IHttpContextAccessor _httpContextAccessor = httpContextAccessor;
    private readonly IOptions<AppSettings> _appSettings = appSettings;
    private readonly IHybridCache _cache = cache;
    private readonly IMemoryCache _memoryCache = memory ?? throw new ArgumentNullException(nameof(memory));
    private readonly IConnectionService _connectionService = connectionService ?? throw new ArgumentNullException(nameof(connectionService));
    private readonly IGenericVoiceFilterService<Filters.FilterPosicaoOutrasPartes> _voiceFilterService = voiceFilterService ?? throw new ArgumentNullException(nameof(voiceFilterService));
    private readonly IServicesFilter servicesFilter = serviceFilter ?? throw new ArgumentNullException(nameof(serviceFilter));
    private bool _disposed;
    private readonly IEntityService _entityService = entityService;
    private readonly IFPosicaoOutrasPartesFactory posicaooutraspartesFactory = posicaooutraspartesFactory;
    private readonly IPosicaoOutrasPartesReader reader = reader;
    private readonly IPosicaoOutrasPartesValidation validation = validation;
    private readonly IPosicaoOutrasPartesWriter writer = writer;
    private readonly ITerceirosService terceirosService = terceirosService;
    public async Task<IEnumerable<PosicaoOutrasPartesResponseAll>> Filter([FromQuery] int max, [FromBody] Filters.FilterPosicaoOutrasPartes filtro, [FromRoute, Required] string uri)
    {
        ThrowIfDisposed();
        if (!(await Uris.ValidaUriAsync(uri, _entityService)))
        {
            throw new Exception("PosicaoOutrasPartes: URI inválida");
        }

        if (max <= 0)
        {
            max = BaseConsts.PMaxItens;
        }

        var connectionStopwatch = PosicaoOutrasPartesDatabaseMetrics.StartTimer();
        try
        {
            var filtroResult = filtro == null ? null : servicesFilter.WFiltroPosicaoOutrasPartes(filtro!);
            string where = filtroResult?.where ?? string.Empty;
            List<SqlParameter>? parameters = filtroResult?.parametros ?? [];
            var filterHash = GenericVoiceFilterService<Filters.FilterPosicaoOutrasPartes>.GetFilterHash(filtro);
            using var scope = _connectionService.CreateConnectionScope(uri);
            using var oCnn = scope.Connection ?? throw new DatabaseConnectionException();
            PosicaoOutrasPartesDatabaseMetrics.RecordConnectionOpen("Filter", uri, connectionStopwatch);
            var keyCache = await reader.ReadStringAuditorAsync(uri, oCnn, _cache);
            var cacheKey = $"{uri}-{max}PosicaoOutrasPartes-Filter-{where.GetHashCode2()}{filterHash}{keyCache}";
            var entryOptions = new HybridCacheEntryOptions
            {
                Expiration = TimeSpan.FromSeconds(BaseConsts.PMaxGetListSecondsCacheId),
                LocalCacheExpiration = TimeSpan.FromSeconds(BaseConsts.PMaxGetListSecondsCacheId)
            };
            var result = await _cache.GetOrCreateAsync(cacheKey, async cancel => await GetDataAllAsync(oCnn, max, string.IsNullOrEmpty(where) ? string.Empty : TSql.Where + where, parameters, uri, cancel), entryOptions, cancellationToken: CancellationToken.None);
            return result;
        }
        catch (SqlException ex)
        {
            PosicaoOutrasPartesDatabaseMetrics.RecordDatabaseError("Filter", "SqlException", uri);
            throw new Exception($"PosicaoOutrasPartes - SQL error on filtering {ex.Message}.");
        }
        catch (TimeoutException ex)
        {
            PosicaoOutrasPartesDatabaseMetrics.RecordDatabaseError("Filter", "Timeout", uri);
            throw new Exception($"PosicaoOutrasPartes - timeout on filtering {ex.Message}.");
        }
        catch (Exception ex)
        {
            throw new Exception($"PosicaoOutrasPartes - error on filtering {ex.Message}.");
        }
    }

    public async Task<Filters.FilterPosicaoOutrasPartes> FilterVoice([FromBody] Filters.FilterPosicaoOutrasPartes filtro, [FromBody] CommandSpeakerRequest? message, [FromRoute, Required] string uri)
    {
        ThrowIfDisposed();
        if (!(await Uris.ValidaUriAsync(uri, _entityService)))
        {
            throw new Exception("PosicaoOutrasPartes: URI inválida");
        }

        try
        {
            // Se há mensagem de comando de voz, processar via OpenAI
            Filters.FilterPosicaoOutrasPartes? filtroProcessado = filtro;
            if (message != null && !string.IsNullOrWhiteSpace(message.Message))
            {
                filtro = filtro ?? new Filters.FilterPosicaoOutrasPartes();
                filtroProcessado = await ProcessFilterVoiceCommandAsync(message, filtro, uri);
            }

            return filtroProcessado ?? new Filters.FilterPosicaoOutrasPartes();
        }
        catch (Exception ex)
        {
            throw new Exception($"PosicaoOutrasPartes - error on creating filter voice: {ex.Message}.");
        }
    }

    public async Task<PosicaoOutrasPartesResponse?> GetById([FromQuery] int id, [FromRoute, Required] string uri, CancellationToken token)
    {
        ThrowIfDisposed();
        if (id < 1)
        {
            return new PosicaoOutrasPartesResponse();
        }

        var connectionStopwatch = PosicaoOutrasPartesDatabaseMetrics.StartTimer();
        var queryStopwatch = PosicaoOutrasPartesDatabaseMetrics.StartTimer();
        var entryOptions = new HybridCacheEntryOptions
        {
            Expiration = TimeSpan.FromSeconds(BaseConsts.PMaxSecondsCacheId),
            LocalCacheExpiration = TimeSpan.FromSeconds(BaseConsts.PMaxSecondsCacheId)
        };
        using var scope = _connectionService.CreateConnectionScope(uri);
        using var oCnn = scope.Connection ?? throw new DatabaseConnectionException();
        try
        {
            PosicaoOutrasPartesDatabaseMetrics.RecordConnectionOpen("GetById", uri, connectionStopwatch);
            PosicaoOutrasPartesDatabaseMetrics.IncrementActiveConnections("GetById", uri);
            var keyCache = await reader.ReadStringAuditorAsync(id, uri, oCnn);
            var result = await _cache.GetOrCreateAsync($"{uri}-PosicaoOutrasPartes-GetById-{id}--{keyCache}", async cancel =>
            {
                var data = await GetDataByIdAsync(id, oCnn, cancel);
                PosicaoOutrasPartesDatabaseMetrics.RecordSqlQuery("GetById", "SELECT", uri, queryStopwatch, data != null ? 1 : 0);
                return data;
            }, entryOptions, cancellationToken: token);
            PosicaoOutrasPartesDatabaseMetrics.DecrementActiveConnections("GetById", uri);
            return result;
        }
        catch (SqlException ex)
        {
            PosicaoOutrasPartesDatabaseMetrics.RecordDatabaseError("GetById", "SqlException", uri);
            PosicaoOutrasPartesDatabaseMetrics.DecrementActiveConnections("GetById", uri);
            throw new Exception($"PosicaoOutrasPartes - SQL error on GetById: {ex.Message}");
        }
        catch (TimeoutException ex)
        {
            PosicaoOutrasPartesDatabaseMetrics.RecordDatabaseError("GetById", "Timeout", uri);
            PosicaoOutrasPartesDatabaseMetrics.DecrementActiveConnections("GetById", uri);
            throw new Exception($"PosicaoOutrasPartes - timeout on GetById: {ex.Message}");
        }
        catch (Exception)
        {
            PosicaoOutrasPartesDatabaseMetrics.DecrementActiveConnections("GetById", uri);
            throw new Exception($"PosicaoOutrasPartes - {uri}-: GetById");
        }
    }

    private async Task<PosicaoOutrasPartesResponse?> GetDataByIdAsync(int id, MsiSqlConnection? oCnn, CancellationToken token) => await reader.ReadAsync(id, oCnn);
    public async Task<AuditorResponse?> GetAuditor([FromQuery] int id, [FromRoute, Required] string uri, CancellationToken token)
    {
        ThrowIfDisposed();
        AuditorResponse? result = null;
        if (id < 1)
        {
            return result;
        }

        using var scope = _connectionService.CreateConnectionScope(uri);
        using var oCnn = scope.Connection ?? throw new DatabaseConnectionException();
        try
        {
            result = await reader.ReadAuditorAsync(id, uri, oCnn);
            return result;
        }
        catch (Exception)
        {
            throw new Exception($"PosicaoOutrasPartes - {uri}-: GetAuditor");
        }
    }

    public async Task<PosicaoOutrasPartesResponse?> AddAndUpdate([FromBody] Models.PosicaoOutrasPartes? regPosicaoOutrasPartes, [FromRoute, Required] string uri)
    {
        ThrowIfDisposed();
        if (regPosicaoOutrasPartes == null)
        {
            return null;
        }

        if (!(await Uris.ValidaUriAsync(uri, _entityService)))
        {
            throw new Exception("PosicaoOutrasPartes: URI inválida");
        }

        var connectionStopwatch = PosicaoOutrasPartesDatabaseMetrics.StartTimer();
        var queryStopwatch = PosicaoOutrasPartesDatabaseMetrics.StartTimer();
        using var scope = _connectionService.CreateConnectionScopeRw(uri);
        using var oCnn = scope.Connection ?? throw new DatabaseConnectionException();
        if (oCnn == null)
        {
            return null;
        }

        try
        {
            PosicaoOutrasPartesDatabaseMetrics.RecordConnectionOpen("AddAndUpdate", uri, connectionStopwatch);
            PosicaoOutrasPartesDatabaseMetrics.IncrementActiveConnections("AddAndUpdate", uri);
            var validade = await validation.ValidateReg(regPosicaoOutrasPartes, this, uri, oCnn);
            if (!validade)
            {
                throw new Exception("Erro inesperado ao validar 0x0!");
            }
        }
        catch (SGValidationException ex)
        {
            PosicaoOutrasPartesDatabaseMetrics.DecrementActiveConnections("AddAndUpdate", uri);
            throw new Exception(ex.Message);
        }
        catch (Exception)
        {
            PosicaoOutrasPartesDatabaseMetrics.DecrementActiveConnections("AddAndUpdate", uri);
            throw new Exception("Erro inesperado ao validar 0x1!");
        }

        int operadorId = UserTools.GetAuthenticatedUserId(_httpContextAccessor);
        try
        {
            using var saved = await writer.WriteAsync(regPosicaoOutrasPartes, operadorId, oCnn);
            string tipoQuery = regPosicaoOutrasPartes.Id.IsEmptyIDNumber() ? "INSERT" : "UPDATE";
            PosicaoOutrasPartesDatabaseMetrics.RecordSqlQuery("AddAndUpdate", tipoQuery, uri, queryStopwatch, 1);
            var result = reader.Read(saved, oCnn);
            PosicaoOutrasPartesDatabaseMetrics.DecrementActiveConnections("AddAndUpdate", uri);
            return result;
        }
        catch (Exception)
        {
            PosicaoOutrasPartesDatabaseMetrics.RecordDatabaseError("AddAndUpdate", "SqlException", uri);
            PosicaoOutrasPartesDatabaseMetrics.DecrementActiveConnections("AddAndUpdate", uri);
            throw;
        }
    }

    public async Task<PosicaoOutrasPartesResponse?> Validation([FromBody] Models.PosicaoOutrasPartes? regPosicaoOutrasPartes, [FromRoute, Required] string uri)
    {
        ThrowIfDisposed();
        if (regPosicaoOutrasPartes == null)
        {
            return null;
        }

        if (!(await Uris.ValidaUriAsync(uri, _entityService)))
        {
            throw new Exception("PosicaoOutrasPartes: URI inválida");
        }

        var connectionStopwatch = PosicaoOutrasPartesDatabaseMetrics.StartTimer();
        var queryStopwatch = PosicaoOutrasPartesDatabaseMetrics.StartTimer();
        using var scope = _connectionService.CreateConnectionScopeRw(uri);
        using var oCnn = scope.Connection ?? throw new DatabaseConnectionException();
        if (oCnn == null)
        {
            return null;
        }

        try
        {
            PosicaoOutrasPartesDatabaseMetrics.RecordConnectionOpen("Validation", uri, connectionStopwatch);
            PosicaoOutrasPartesDatabaseMetrics.IncrementActiveConnections("Validation", uri);
            var validade = await validation.ValidateReg(regPosicaoOutrasPartes, this, uri, oCnn);
            if (!validade)
            {
                throw new Exception("Erro inesperado ao validar 0x0!");
            }
        }
        catch (SGValidationException ex)
        {
            PosicaoOutrasPartesDatabaseMetrics.DecrementActiveConnections("Validation", uri);
            throw new Exception(ex.Message);
        }
        catch (Exception)
        {
            PosicaoOutrasPartesDatabaseMetrics.DecrementActiveConnections("Validation", uri);
            throw new Exception("Erro inesperado ao validar 0x1!");
        }

        if (regPosicaoOutrasPartes.Id.IsEmptyIDNumber())
        {
            return new PosicaoOutrasPartesResponse();
        }

        return await reader.ReadAsync(regPosicaoOutrasPartes.Id, oCnn);
    }

    public async Task<PosicaoOutrasPartesResponse?> Delete([FromQuery] int? id, [FromRoute, Required] string uri)
    {
        if (id == null || id.IsEmptyIDNumber())
        {
            return null;
        }

        ThrowIfDisposed();
        if (!(await Uris.ValidaUriAsync(uri, _entityService)))
        {
            throw new Exception("PosicaoOutrasPartes: URI inválida");
        }

        var nOperador = UserTools.GetAuthenticatedUserId(_httpContextAccessor);
        using var scope = _connectionService.CreateConnectionScopeRw(uri);
        using var oCnn = scope.Connection ?? throw new DatabaseConnectionException();
        var connectionStopwatch = PosicaoOutrasPartesDatabaseMetrics.StartTimer();
        var queryStopwatch = PosicaoOutrasPartesDatabaseMetrics.StartTimer();
        if (oCnn == null)
        {
            return null;
        }

        try
        {
            PosicaoOutrasPartesDatabaseMetrics.RecordConnectionOpen("Delete", uri, connectionStopwatch);
            PosicaoOutrasPartesDatabaseMetrics.IncrementActiveConnections("Delete", uri);
            var deleteValidation = await validation.CanDelete(id, this, terceirosService, uri, oCnn);
            if (!deleteValidation)
            {
                throw new Exception("Erro inesperado ao validar 0x0!");
            }
        }
        catch (SGValidationException ex)
        {
            PosicaoOutrasPartesDatabaseMetrics.DecrementActiveConnections("Delete", uri);
            throw new Exception(ex.Message);
        }
        catch (Exception)
        {
            PosicaoOutrasPartesDatabaseMetrics.DecrementActiveConnections("Delete", uri);
            throw new Exception("Erro inesperado ao validar 0x1!");
        }

        var posicaooutraspartes = await reader.ReadAsync(id ?? default, oCnn);
        try
        {
            if (posicaooutraspartes != null)
            {
                await writer.DeleteAsync(posicaooutraspartes, nOperador, oCnn);
                PosicaoOutrasPartesDatabaseMetrics.RecordSqlQuery("Delete", "DELETE", uri, queryStopwatch, 1);
                if (_memoryCache is MemoryCache memCache)
                {
                    memCache.Compact(1.0);
                }
            }

            PosicaoOutrasPartesDatabaseMetrics.DecrementActiveConnections("Delete", uri);
            return posicaooutraspartes;
        }
        catch (Exception ex)
        {
            PosicaoOutrasPartesDatabaseMetrics.RecordDatabaseError("Delete", "SqlException", uri);
            PosicaoOutrasPartesDatabaseMetrics.DecrementActiveConnections("Delete", uri);
            throw new Exception(ex.Message);
        }
    }

    public virtual void Dispose()
    {
        Dispose(true);
        GC.SuppressFinalize(this);
    }

    protected virtual void Dispose(bool disposing)
    {
        if (_disposed)
            return;
        if (disposing)
        {
        //_cache?.Dispose();
        }

        _disposed = true;
    }

    private void ThrowIfDisposed()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
    }
}