using MenphisSI.SG.GerAdv.DicInfo;
using System.Diagnostics.CodeAnalysis;

// ReSharper disable once CheckNamespace
namespace MenphisSI.SG.GerAdv;
[ExcludeFromCodeCoverage]
public class DicionarioDeDadosManagedDatabaseCode
{
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public string NameSpace() => nameof(GerAdv);
    public IODicInfo? GlobalObjectDicInfo(string? tabelaOrIdOrPrefix) => tabelaOrIdOrPrefix switch
    {
        "1" => new DBAcaoODicInfo(),
        DBAcao.PTabelaNome => new DBAcaoODicInfo(),
        "ACAO" => new DBAcaoODicInfo(),
        "2" => new DBAdvogadosODicInfo(),
        DBAdvogados.PTabelaNome => new DBAdvogadosODicInfo(),
        "ADVOGADOS" => new DBAdvogadosODicInfo(),
        "3" => new DBAgendaODicInfo(),
        DBAgenda.PTabelaNome => new DBAgendaODicInfo(),
        "AGENDA" => new DBAgendaODicInfo(),
        "4" => new DBAreaODicInfo(),
        DBArea.PTabelaNome => new DBAreaODicInfo(),
        "AREA" => new DBAreaODicInfo(),
        "5" => new DBCargosODicInfo(),
        DBCargos.PTabelaNome => new DBCargosODicInfo(),
        "CARGOS" => new DBCargosODicInfo(),
        "6" => new DBCidadeODicInfo(),
        DBCidade.PTabelaNome => new DBCidadeODicInfo(),
        "CIDADE" => new DBCidadeODicInfo(),
        "7" => new DBClientesODicInfo(),
        DBClientes.PTabelaNome => new DBClientesODicInfo(),
        "CLIENTES" => new DBClientesODicInfo(),
        "8" => new DBClientesSociosODicInfo(),
        DBClientesSocios.PTabelaNome => new DBClientesSociosODicInfo(),
        "CLIENTESSOCIOS" => new DBClientesSociosODicInfo(),
        "9" => new DBColaboradoresODicInfo(),
        DBColaboradores.PTabelaNome => new DBColaboradoresODicInfo(),
        "COLABORADORES" => new DBColaboradoresODicInfo(),
        "10" => new DBDivisaoTribunalODicInfo(),
        DBDivisaoTribunal.PTabelaNome => new DBDivisaoTribunalODicInfo(),
        "DIVISAOTRIBUNAL" => new DBDivisaoTribunalODicInfo(),
        "11" => new DBEscritoriosODicInfo(),
        DBEscritorios.PTabelaNome => new DBEscritoriosODicInfo(),
        "ESCRITORIOS" => new DBEscritoriosODicInfo(),
        "12" => new DBForoODicInfo(),
        DBForo.PTabelaNome => new DBForoODicInfo(),
        "FORO" => new DBForoODicInfo(),
        "13" => new DBFuncaoODicInfo(),
        DBFuncao.PTabelaNome => new DBFuncaoODicInfo(),
        "FUNCAO" => new DBFuncaoODicInfo(),
        "14" => new DBFuncionariosODicInfo(),
        DBFuncionarios.PTabelaNome => new DBFuncionariosODicInfo(),
        "FUNCIONARIOS" => new DBFuncionariosODicInfo(),
        "15" => new DBInstanciaODicInfo(),
        DBInstancia.PTabelaNome => new DBInstanciaODicInfo(),
        "INSTANCIA" => new DBInstanciaODicInfo(),
        "16" => new DBJusticaODicInfo(),
        DBJustica.PTabelaNome => new DBJusticaODicInfo(),
        "JUSTICA" => new DBJusticaODicInfo(),
        "17" => new DBOperadorODicInfo(),
        DBOperador.PTabelaNome => new DBOperadorODicInfo(),
        "OPERADOR" => new DBOperadorODicInfo(),
        "18" => new DBOponentesODicInfo(),
        DBOponentes.PTabelaNome => new DBOponentesODicInfo(),
        "OPONENTES" => new DBOponentesODicInfo(),
        "19" => new DBPaisesODicInfo(),
        DBPaises.PTabelaNome => new DBPaisesODicInfo(),
        "PAISES" => new DBPaisesODicInfo(),
        "20" => new DBProDespesasODicInfo(),
        DBProDespesas.PTabelaNome => new DBProDespesasODicInfo(),
        "PRODESPESAS" => new DBProDespesasODicInfo(),
        "21" => new DBRitoODicInfo(),
        DBRito.PTabelaNome => new DBRitoODicInfo(),
        "RITO" => new DBRitoODicInfo(),
        "22" => new DBTipoCompromissoODicInfo(),
        DBTipoCompromisso.PTabelaNome => new DBTipoCompromissoODicInfo(),
        "TIPOCOMPROMISSO" => new DBTipoCompromissoODicInfo(),
        "23" => new DBTipoProDespositoODicInfo(),
        DBTipoProDesposito.PTabelaNome => new DBTipoProDespositoODicInfo(),
        "TIPOPRODESPOSITO" => new DBTipoProDespositoODicInfo(),
        "24" => new DBTipoRecursoODicInfo(),
        DBTipoRecurso.PTabelaNome => new DBTipoRecursoODicInfo(),
        "TIPORECURSO" => new DBTipoRecursoODicInfo(),
        "25" => new DBTiposAcaoODicInfo(),
        DBTiposAcao.PTabelaNome => new DBTiposAcaoODicInfo(),
        "TIPOSACAO" => new DBTiposAcaoODicInfo(),
        "26" => new DBTribunalODicInfo(),
        DBTribunal.PTabelaNome => new DBTribunalODicInfo(),
        "TRIBUNAL" => new DBTribunalODicInfo(),
        "27" => new DBUFODicInfo(),
        DBUF.PTabelaNome => new DBUFODicInfo(),
        "28" => new DBAgendaRelatorioODicInfo(),
        DBAgendaRelatorio.PTabelaNome => new DBAgendaRelatorioODicInfo(),
        "AGENDARELATORIO" => new DBAgendaRelatorioODicInfo(),
        "29" => new DBAgendaSemanaODicInfo(),
        DBAgendaSemana.PTabelaNome => new DBAgendaSemanaODicInfo(),
        "AGENDASEMANA" => new DBAgendaSemanaODicInfo(),
        _ => null
    };
}