// 100% auto-generated by Source Genesys WebApi Front & Back Creator
// copyright © 2000-2025 Menphis - Sistemas Inteligentes
// This file is part of the Source Genesys project                     
#pragma warning disable IDE0130 // Namespace does not match folder structure

namespace MenphisSI.GerAdv.Services;
#pragma warning restore IDE0130 // Namespace does not match folder structure

public partial class AdvogadosService
{
    private static (string where, List<SqlParameter> parametros)? WFiltro(Filters.FilterAdvogados filtro)
    {
        var parameters = new List<SqlParameter>();
        if (filtro.Cargo != int.MinValue)
        {
            parameters.Add(new($"@{nameof(DBAdvogadosDicInfo.Cargo)}", filtro.Cargo));
        }

        if (!string.IsNullOrEmpty(filtro.EMailPro))
        {
            parameters.Add(new($"@{nameof(DBAdvogadosDicInfo.EMailPro)}", ApplyWildCard(filtro.WildcardChar, filtro.EMailPro)));
        }

        if (!string.IsNullOrEmpty(filtro.CPF))
        {
            parameters.Add(new($"@{nameof(DBAdvogadosDicInfo.CPF)}", ApplyWildCard(filtro.WildcardChar, filtro.CPF)));
        }

        if (!string.IsNullOrEmpty(filtro.Nome))
        {
            parameters.Add(new($"@{nameof(DBAdvogadosDicInfo.Nome)}", ApplyWildCard(filtro.WildcardChar, filtro.Nome)));
        }

        if (!string.IsNullOrEmpty(filtro.RG))
        {
            parameters.Add(new($"@{nameof(DBAdvogadosDicInfo.RG)}", ApplyWildCard(filtro.WildcardChar, filtro.RG)));
        }

        if (filtro.Casa != int.MinValue)
        {
            parameters.Add(new($"@{nameof(DBAdvogadosDicInfo.Casa)}", filtro.Casa));
        }

        if (!string.IsNullOrEmpty(filtro.NomeMae))
        {
            parameters.Add(new($"@{nameof(DBAdvogadosDicInfo.NomeMae)}", ApplyWildCard(filtro.WildcardChar, filtro.NomeMae)));
        }

        if (filtro.Escritorio != int.MinValue)
        {
            parameters.Add(new($"@{nameof(DBAdvogadosDicInfo.Escritorio)}", filtro.Escritorio));
        }

        if (filtro.Estagiario != int.MinValue)
        {
            parameters.Add(new($"@{nameof(DBAdvogadosDicInfo.Estagiario)}", filtro.Estagiario));
        }

        if (!string.IsNullOrEmpty(filtro.OAB))
        {
            parameters.Add(new($"@{nameof(DBAdvogadosDicInfo.OAB)}", ApplyWildCard(filtro.WildcardChar, filtro.OAB)));
        }

        if (!string.IsNullOrEmpty(filtro.NomeCompleto))
        {
            parameters.Add(new($"@{nameof(DBAdvogadosDicInfo.NomeCompleto)}", ApplyWildCard(filtro.WildcardChar, filtro.NomeCompleto)));
        }

        if (!string.IsNullOrEmpty(filtro.Endereco))
        {
            parameters.Add(new($"@{nameof(DBAdvogadosDicInfo.Endereco)}", ApplyWildCard(filtro.WildcardChar, filtro.Endereco)));
        }

        if (filtro.Cidade != int.MinValue)
        {
            parameters.Add(new($"@{nameof(DBAdvogadosDicInfo.Cidade)}", filtro.Cidade));
        }

        if (!string.IsNullOrEmpty(filtro.CEP))
        {
            parameters.Add(new($"@{nameof(DBAdvogadosDicInfo.CEP)}", ApplyWildCard(filtro.WildcardChar, filtro.CEP)));
        }

        if (filtro.Sexo != int.MinValue)
        {
            parameters.Add(new($"@{nameof(DBAdvogadosDicInfo.Sexo)}", filtro.Sexo));
        }

        if (!string.IsNullOrEmpty(filtro.Bairro))
        {
            parameters.Add(new($"@{nameof(DBAdvogadosDicInfo.Bairro)}", ApplyWildCard(filtro.WildcardChar, filtro.Bairro)));
        }

        if (!string.IsNullOrEmpty(filtro.CTPSSerie))
        {
            parameters.Add(new($"@{nameof(DBAdvogadosDicInfo.CTPSSerie)}", ApplyWildCard(filtro.WildcardChar, filtro.CTPSSerie)));
        }

        if (!string.IsNullOrEmpty(filtro.CTPS))
        {
            parameters.Add(new($"@{nameof(DBAdvogadosDicInfo.CTPS)}", ApplyWildCard(filtro.WildcardChar, filtro.CTPS)));
        }

        if (!string.IsNullOrEmpty(filtro.Fone))
        {
            parameters.Add(new($"@{nameof(DBAdvogadosDicInfo.Fone)}", ApplyWildCard(filtro.WildcardChar, filtro.Fone)));
        }

        if (!string.IsNullOrEmpty(filtro.Fax))
        {
            parameters.Add(new($"@{nameof(DBAdvogadosDicInfo.Fax)}", ApplyWildCard(filtro.WildcardChar, filtro.Fax)));
        }

        if (filtro.Comissao != int.MinValue)
        {
            parameters.Add(new($"@{nameof(DBAdvogadosDicInfo.Comissao)}", filtro.Comissao));
        }

        if (filtro.Comissao_end != int.MinValue)
        {
            parameters.Add(new($"@{nameof(DBAdvogadosDicInfo.Comissao)}_end", filtro.Comissao_end));
        }

        if (!filtro.DtInicio.IsEmpty())
        {
            if (DateTime.TryParse(filtro.DtInicio, out var dataParam))
                parameters.Add(new($"@{nameof(DBAdvogadosDicInfo.DtInicio)}", dataParam));
        }

        if (!filtro.DtInicio_end.IsEmpty())
        {
            if (DateTime.TryParse(filtro.DtInicio_end, out var dataParam))
                parameters.Add(new($"@{nameof(DBAdvogadosDicInfo.DtInicio)}_end", dataParam));
        }

        if (!filtro.DtFim.IsEmpty())
        {
            if (DateTime.TryParse(filtro.DtFim, out var dataParam))
                parameters.Add(new($"@{nameof(DBAdvogadosDicInfo.DtFim)}", dataParam));
        }

        if (!filtro.DtFim_end.IsEmpty())
        {
            if (DateTime.TryParse(filtro.DtFim_end, out var dataParam))
                parameters.Add(new($"@{nameof(DBAdvogadosDicInfo.DtFim)}_end", dataParam));
        }

        if (!filtro.DtNasc.IsEmpty())
        {
            if (DateTime.TryParse(filtro.DtNasc, out var dataParam))
                parameters.Add(new($"@{nameof(DBAdvogadosDicInfo.DtNasc)}", dataParam));
        }

        if (!filtro.DtNasc_end.IsEmpty())
        {
            if (DateTime.TryParse(filtro.DtNasc_end, out var dataParam))
                parameters.Add(new($"@{nameof(DBAdvogadosDicInfo.DtNasc)}_end", dataParam));
        }

        if (filtro.Salario != decimal.MinValue)
        {
            parameters.Add(new($"@{nameof(DBAdvogadosDicInfo.Salario)}", filtro.Salario));
        }

        if (filtro.Salario_end != decimal.MinValue)
        {
            parameters.Add(new($"@{nameof(DBAdvogadosDicInfo.Salario)}_end", filtro.Salario_end));
        }

        if (!string.IsNullOrEmpty(filtro.Secretaria))
        {
            parameters.Add(new($"@{nameof(DBAdvogadosDicInfo.Secretaria)}", ApplyWildCard(filtro.WildcardChar, filtro.Secretaria)));
        }

        if (!string.IsNullOrEmpty(filtro.TextoProcuracao))
        {
            parameters.Add(new($"@{nameof(DBAdvogadosDicInfo.TextoProcuracao)}", ApplyWildCard(filtro.WildcardChar, filtro.TextoProcuracao)));
        }

        if (!string.IsNullOrEmpty(filtro.EMail))
        {
            parameters.Add(new($"@{nameof(DBAdvogadosDicInfo.EMail)}", ApplyWildCard(filtro.WildcardChar, filtro.EMail)));
        }

        if (!string.IsNullOrEmpty(filtro.Especializacao))
        {
            parameters.Add(new($"@{nameof(DBAdvogadosDicInfo.Especializacao)}", ApplyWildCard(filtro.WildcardChar, filtro.Especializacao)));
        }

        if (!string.IsNullOrEmpty(filtro.Pasta))
        {
            parameters.Add(new($"@{nameof(DBAdvogadosDicInfo.Pasta)}", ApplyWildCard(filtro.WildcardChar, filtro.Pasta)));
        }

        if (!string.IsNullOrEmpty(filtro.Observacao))
        {
            parameters.Add(new($"@{nameof(DBAdvogadosDicInfo.Observacao)}", ApplyWildCard(filtro.WildcardChar, filtro.Observacao)));
        }

        if (!string.IsNullOrEmpty(filtro.ContaBancaria))
        {
            parameters.Add(new($"@{nameof(DBAdvogadosDicInfo.ContaBancaria)}", ApplyWildCard(filtro.WildcardChar, filtro.ContaBancaria)));
        }

        if (filtro.ParcTop != int.MinValue)
        {
            parameters.Add(new($"@{nameof(DBAdvogadosDicInfo.ParcTop)}", filtro.ParcTop));
        }

        if (!string.IsNullOrEmpty(filtro.Class))
        {
            parameters.Add(new($"@{nameof(DBAdvogadosDicInfo.Class)}", ApplyWildCard(filtro.WildcardChar, filtro.Class)));
        }

        if (filtro.Top != int.MinValue)
        {
            parameters.Add(new($"@{nameof(DBAdvogadosDicInfo.Top)}", filtro.Top));
        }

        if (!string.IsNullOrEmpty(filtro.GUID))
        {
            parameters.Add(new($"@{nameof(DBAdvogadosDicInfo.GUID)}", ApplyWildCard(filtro.WildcardChar, filtro.GUID)));
        }

        if (filtro.Codigo_filtro != int.MinValue)
        {
            parameters.Add(new($"@{nameof(DBAdvogadosDicInfo.CampoCodigo)}", filtro.Codigo_filtro));
        }

        if (filtro.Codigo_filtro_end != int.MinValue)
        {
            parameters.Add(new($"@{nameof(DBAdvogadosDicInfo.CampoCodigo)}_end", filtro.Codigo_filtro_end));
        }

        if (filtro.LogicalOperator.IsEmpty() || (filtro.LogicalOperator.NotEquals(TSql.And) && filtro.LogicalOperator.NotEquals(TSql.OR)))
        {
            filtro.LogicalOperator = TSql.And;
        }

        var cWhere = new StringBuilder();
        cWhere.Append(filtro.Cargo <= 0 ? string.Empty : (cWhere.Length == 0 ? string.Empty : filtro.LogicalOperator) + $"[{DBAdvogadosDicInfo.PTabelaNome}].[{DBAdvogadosDicInfo.Cargo}] = @{nameof(DBAdvogadosDicInfo.Cargo)}");
        cWhere.Append(filtro.EMailPro.IsEmpty() ? string.Empty : (cWhere.Length == 0 ? string.Empty : filtro.LogicalOperator) + $"[{DBAdvogadosDicInfo.PTabelaNome}].[{DBAdvogadosDicInfo.EMailPro}]  {DevourerConsts.MsiCollate} like @{nameof(DBAdvogadosDicInfo.EMailPro)}");
        cWhere.Append(filtro.CPF.IsEmpty() ? string.Empty : (cWhere.Length == 0 ? string.Empty : filtro.LogicalOperator) + $"[{DBAdvogadosDicInfo.PTabelaNome}].[{DBAdvogadosDicInfo.CPF}]  {DevourerConsts.MsiCollate} like @{nameof(DBAdvogadosDicInfo.CPF)}");
        cWhere.Append(filtro.Nome.IsEmpty() ? string.Empty : (cWhere.Length == 0 ? string.Empty : filtro.LogicalOperator) + $"[{DBAdvogadosDicInfo.PTabelaNome}].[{DBAdvogadosDicInfo.Nome}]  {DevourerConsts.MsiCollate} like @{nameof(DBAdvogadosDicInfo.Nome)}");
        cWhere.Append(filtro.RG.IsEmpty() ? string.Empty : (cWhere.Length == 0 ? string.Empty : filtro.LogicalOperator) + $"[{DBAdvogadosDicInfo.PTabelaNome}].[{DBAdvogadosDicInfo.RG}]  {DevourerConsts.MsiCollate} like @{nameof(DBAdvogadosDicInfo.RG)}");
        cWhere.Append(filtro.Casa == int.MinValue ? string.Empty : (cWhere.Length == 0 ? string.Empty : filtro.LogicalOperator) + $"[{DBAdvogadosDicInfo.PTabelaNome}].[{DBAdvogadosDicInfo.Casa}] = @{nameof(DBAdvogadosDicInfo.Casa)}");
        cWhere.Append(filtro.NomeMae.IsEmpty() ? string.Empty : (cWhere.Length == 0 ? string.Empty : filtro.LogicalOperator) + $"[{DBAdvogadosDicInfo.PTabelaNome}].[{DBAdvogadosDicInfo.NomeMae}]  {DevourerConsts.MsiCollate} like @{nameof(DBAdvogadosDicInfo.NomeMae)}");
        cWhere.Append(filtro.Escritorio <= 0 ? string.Empty : (cWhere.Length == 0 ? string.Empty : filtro.LogicalOperator) + $"[{DBAdvogadosDicInfo.PTabelaNome}].[{DBAdvogadosDicInfo.Escritorio}] = @{nameof(DBAdvogadosDicInfo.Escritorio)}");
        cWhere.Append(filtro.Estagiario == int.MinValue ? string.Empty : (cWhere.Length == 0 ? string.Empty : filtro.LogicalOperator) + $"[{DBAdvogadosDicInfo.PTabelaNome}].[{DBAdvogadosDicInfo.Estagiario}] = @{nameof(DBAdvogadosDicInfo.Estagiario)}");
        cWhere.Append(filtro.OAB.IsEmpty() ? string.Empty : (cWhere.Length == 0 ? string.Empty : filtro.LogicalOperator) + $"[{DBAdvogadosDicInfo.PTabelaNome}].[{DBAdvogadosDicInfo.OAB}]  {DevourerConsts.MsiCollate} like @{nameof(DBAdvogadosDicInfo.OAB)}");
        cWhere.Append(filtro.NomeCompleto.IsEmpty() ? string.Empty : (cWhere.Length == 0 ? string.Empty : filtro.LogicalOperator) + $"[{DBAdvogadosDicInfo.PTabelaNome}].[{DBAdvogadosDicInfo.NomeCompleto}]  {DevourerConsts.MsiCollate} like @{nameof(DBAdvogadosDicInfo.NomeCompleto)}");
        cWhere.Append(filtro.Endereco.IsEmpty() ? string.Empty : (cWhere.Length == 0 ? string.Empty : filtro.LogicalOperator) + $"[{DBAdvogadosDicInfo.PTabelaNome}].[{DBAdvogadosDicInfo.Endereco}]  {DevourerConsts.MsiCollate} like @{nameof(DBAdvogadosDicInfo.Endereco)}");
        cWhere.Append(filtro.Cidade <= 0 ? string.Empty : (cWhere.Length == 0 ? string.Empty : filtro.LogicalOperator) + $"[{DBAdvogadosDicInfo.PTabelaNome}].[{DBAdvogadosDicInfo.Cidade}] = @{nameof(DBAdvogadosDicInfo.Cidade)}");
        cWhere.Append(filtro.CEP.IsEmpty() ? string.Empty : (cWhere.Length == 0 ? string.Empty : filtro.LogicalOperator) + $"[{DBAdvogadosDicInfo.PTabelaNome}].[{DBAdvogadosDicInfo.CEP}]  {DevourerConsts.MsiCollate} like @{nameof(DBAdvogadosDicInfo.CEP)}");
        cWhere.Append(filtro.Sexo == int.MinValue ? string.Empty : (cWhere.Length == 0 ? string.Empty : filtro.LogicalOperator) + $"[{DBAdvogadosDicInfo.PTabelaNome}].[{DBAdvogadosDicInfo.Sexo}] = @{nameof(DBAdvogadosDicInfo.Sexo)}");
        cWhere.Append(filtro.Bairro.IsEmpty() ? string.Empty : (cWhere.Length == 0 ? string.Empty : filtro.LogicalOperator) + $"[{DBAdvogadosDicInfo.PTabelaNome}].[{DBAdvogadosDicInfo.Bairro}]  {DevourerConsts.MsiCollate} like @{nameof(DBAdvogadosDicInfo.Bairro)}");
        cWhere.Append(filtro.CTPSSerie.IsEmpty() ? string.Empty : (cWhere.Length == 0 ? string.Empty : filtro.LogicalOperator) + $"[{DBAdvogadosDicInfo.PTabelaNome}].[{DBAdvogadosDicInfo.CTPSSerie}]  {DevourerConsts.MsiCollate} like @{nameof(DBAdvogadosDicInfo.CTPSSerie)}");
        cWhere.Append(filtro.CTPS.IsEmpty() ? string.Empty : (cWhere.Length == 0 ? string.Empty : filtro.LogicalOperator) + $"[{DBAdvogadosDicInfo.PTabelaNome}].[{DBAdvogadosDicInfo.CTPS}]  {DevourerConsts.MsiCollate} like @{nameof(DBAdvogadosDicInfo.CTPS)}");
        cWhere.Append(filtro.Fone.IsEmpty() ? string.Empty : (cWhere.Length == 0 ? string.Empty : filtro.LogicalOperator) + $"[{DBAdvogadosDicInfo.PTabelaNome}].[{DBAdvogadosDicInfo.Fone}]  {DevourerConsts.MsiCollate} like @{nameof(DBAdvogadosDicInfo.Fone)}");
        cWhere.Append(filtro.Fax.IsEmpty() ? string.Empty : (cWhere.Length == 0 ? string.Empty : filtro.LogicalOperator) + $"[{DBAdvogadosDicInfo.PTabelaNome}].[{DBAdvogadosDicInfo.Fax}]  {DevourerConsts.MsiCollate} like @{nameof(DBAdvogadosDicInfo.Fax)}");
        if (!filtro.Comissao.IsEmpty() && filtro.Comissao_end.IsEmpty())
        {
            cWhere.Append(filtro.Comissao <= 0 ? string.Empty : (cWhere.Length == 0 ? string.Empty : filtro.LogicalOperator) + $"[{DBAdvogadosDicInfo.PTabelaNome}].[{DBAdvogadosDicInfo.Comissao}] >= @{nameof(DBAdvogadosDicInfo.Comissao)}");
        }
        else
        {
            cWhere.Append((filtro.Comissao <= 0 && filtro.Comissao_end <= 0) ? string.Empty : (!(filtro.Comissao <= 0) && !(filtro.Comissao_end <= 0)) ? (cWhere.Length == 0 ? string.Empty : filtro.LogicalOperator) + $"{DBAdvogadosDicInfo.Comissao} BETWEEN @{nameof(DBAdvogadosDicInfo.Comissao)} AND @{nameof(DBAdvogadosDicInfo.Comissao)}_end" : !(filtro.Comissao <= 0) ? (cWhere.Length == 0 ? string.Empty : filtro.LogicalOperator) + $"{DBAdvogadosDicInfo.Comissao} = @{nameof(DBAdvogadosDicInfo.Comissao)}" : (cWhere.Length == 0 ? string.Empty : filtro.LogicalOperator) + $"{DBAdvogadosDicInfo.Comissao} <= @{nameof(DBAdvogadosDicInfo.Comissao)}_end");
        }

        if (!filtro.DtInicio.IsEmpty() && filtro.DtInicio_end.IsEmpty())
        {
            cWhere.Append(filtro.DtInicio.IsEmpty() ? string.Empty : (cWhere.Length == 0 ? string.Empty : filtro.LogicalOperator) + $"CONVERT(DATE,[{DBAdvogadosDicInfo.PTabelaNome}].[{DBAdvogadosDicInfo.DtInicio}], 103) >= CONVERT(DATE, @{nameof(DBAdvogadosDicInfo.DtInicio)}, 103)");
        }
        else
        {
            cWhere.Append((filtro.DtInicio.IsEmpty() && filtro.DtInicio_end.IsEmpty()) ? string.Empty : (!(filtro.DtInicio.IsEmpty()) && !(filtro.DtInicio_end.IsEmpty())) ? (cWhere.Length == 0 ? string.Empty : filtro.LogicalOperator) + $"{DBAdvogadosDicInfo.DtInicio} BETWEEN @{nameof(DBAdvogadosDicInfo.DtInicio)} AND @{nameof(DBAdvogadosDicInfo.DtInicio)}_end" : !(filtro.DtInicio.IsEmpty()) ? (cWhere.Length == 0 ? string.Empty : filtro.LogicalOperator) + $"{DBAdvogadosDicInfo.DtInicio} = @{nameof(DBAdvogadosDicInfo.DtInicio)}" : (cWhere.Length == 0 ? string.Empty : filtro.LogicalOperator) + $"{DBAdvogadosDicInfo.DtInicio} <= @{nameof(DBAdvogadosDicInfo.DtInicio)}_end");
        }

        if (!filtro.DtFim.IsEmpty() && filtro.DtFim_end.IsEmpty())
        {
            cWhere.Append(filtro.DtFim.IsEmpty() ? string.Empty : (cWhere.Length == 0 ? string.Empty : filtro.LogicalOperator) + $"CONVERT(DATE,[{DBAdvogadosDicInfo.PTabelaNome}].[{DBAdvogadosDicInfo.DtFim}], 103) >= CONVERT(DATE, @{nameof(DBAdvogadosDicInfo.DtFim)}, 103)");
        }
        else
        {
            cWhere.Append((filtro.DtFim.IsEmpty() && filtro.DtFim_end.IsEmpty()) ? string.Empty : (!(filtro.DtFim.IsEmpty()) && !(filtro.DtFim_end.IsEmpty())) ? (cWhere.Length == 0 ? string.Empty : filtro.LogicalOperator) + $"{DBAdvogadosDicInfo.DtFim} BETWEEN @{nameof(DBAdvogadosDicInfo.DtFim)} AND @{nameof(DBAdvogadosDicInfo.DtFim)}_end" : !(filtro.DtFim.IsEmpty()) ? (cWhere.Length == 0 ? string.Empty : filtro.LogicalOperator) + $"{DBAdvogadosDicInfo.DtFim} = @{nameof(DBAdvogadosDicInfo.DtFim)}" : (cWhere.Length == 0 ? string.Empty : filtro.LogicalOperator) + $"{DBAdvogadosDicInfo.DtFim} <= @{nameof(DBAdvogadosDicInfo.DtFim)}_end");
        }

        if (!filtro.DtNasc.IsEmpty() && filtro.DtNasc_end.IsEmpty())
        {
            cWhere.Append(filtro.DtNasc.IsEmpty() ? string.Empty : (cWhere.Length == 0 ? string.Empty : filtro.LogicalOperator) + $"CONVERT(DATE,[{DBAdvogadosDicInfo.PTabelaNome}].[{DBAdvogadosDicInfo.DtNasc}], 103) >= CONVERT(DATE, @{nameof(DBAdvogadosDicInfo.DtNasc)}, 103)");
        }
        else
        {
            cWhere.Append((filtro.DtNasc.IsEmpty() && filtro.DtNasc_end.IsEmpty()) ? string.Empty : (!(filtro.DtNasc.IsEmpty()) && !(filtro.DtNasc_end.IsEmpty())) ? (cWhere.Length == 0 ? string.Empty : filtro.LogicalOperator) + $"{DBAdvogadosDicInfo.DtNasc} BETWEEN @{nameof(DBAdvogadosDicInfo.DtNasc)} AND @{nameof(DBAdvogadosDicInfo.DtNasc)}_end" : !(filtro.DtNasc.IsEmpty()) ? (cWhere.Length == 0 ? string.Empty : filtro.LogicalOperator) + $"{DBAdvogadosDicInfo.DtNasc} = @{nameof(DBAdvogadosDicInfo.DtNasc)}" : (cWhere.Length == 0 ? string.Empty : filtro.LogicalOperator) + $"{DBAdvogadosDicInfo.DtNasc} <= @{nameof(DBAdvogadosDicInfo.DtNasc)}_end");
        }

        if (!filtro.Salario.IsEmpty() && filtro.Salario_end.IsEmpty())
        {
            cWhere.Append(filtro.Salario == decimal.MinValue ? string.Empty : (cWhere.Length == 0 ? string.Empty : filtro.LogicalOperator) + $"[{DBAdvogadosDicInfo.PTabelaNome}].[{DBAdvogadosDicInfo.Salario}] >= @{nameof(DBAdvogadosDicInfo.Salario)}");
        }
        else
        {
            cWhere.Append((filtro.Salario == decimal.MinValue && filtro.Salario_end == decimal.MinValue) ? string.Empty : (!(filtro.Salario == decimal.MinValue) && !(filtro.Salario_end == decimal.MinValue)) ? (cWhere.Length == 0 ? string.Empty : filtro.LogicalOperator) + $"{DBAdvogadosDicInfo.Salario} BETWEEN @{nameof(DBAdvogadosDicInfo.Salario)} AND @{nameof(DBAdvogadosDicInfo.Salario)}_end" : !(filtro.Salario == decimal.MinValue) ? (cWhere.Length == 0 ? string.Empty : filtro.LogicalOperator) + $"{DBAdvogadosDicInfo.Salario} = @{nameof(DBAdvogadosDicInfo.Salario)}" : (cWhere.Length == 0 ? string.Empty : filtro.LogicalOperator) + $"{DBAdvogadosDicInfo.Salario} <= @{nameof(DBAdvogadosDicInfo.Salario)}_end");
        }

        cWhere.Append(filtro.Secretaria.IsEmpty() ? string.Empty : (cWhere.Length == 0 ? string.Empty : filtro.LogicalOperator) + $"[{DBAdvogadosDicInfo.PTabelaNome}].[{DBAdvogadosDicInfo.Secretaria}]  {DevourerConsts.MsiCollate} like @{nameof(DBAdvogadosDicInfo.Secretaria)}");
        cWhere.Append(filtro.TextoProcuracao.IsEmpty() ? string.Empty : (cWhere.Length == 0 ? string.Empty : filtro.LogicalOperator) + $"[{DBAdvogadosDicInfo.PTabelaNome}].[{DBAdvogadosDicInfo.TextoProcuracao}]  {DevourerConsts.MsiCollate} like @{nameof(DBAdvogadosDicInfo.TextoProcuracao)}");
        cWhere.Append(filtro.EMail.IsEmpty() ? string.Empty : (cWhere.Length == 0 ? string.Empty : filtro.LogicalOperator) + $"[{DBAdvogadosDicInfo.PTabelaNome}].[{DBAdvogadosDicInfo.EMail}]  {DevourerConsts.MsiCollate} like @{nameof(DBAdvogadosDicInfo.EMail)}");
        cWhere.Append(filtro.Especializacao.IsEmpty() ? string.Empty : (cWhere.Length == 0 ? string.Empty : filtro.LogicalOperator) + $"[{DBAdvogadosDicInfo.PTabelaNome}].[{DBAdvogadosDicInfo.Especializacao}]  {DevourerConsts.MsiCollate} like @{nameof(DBAdvogadosDicInfo.Especializacao)}");
        cWhere.Append(filtro.Pasta.IsEmpty() ? string.Empty : (cWhere.Length == 0 ? string.Empty : filtro.LogicalOperator) + $"[{DBAdvogadosDicInfo.PTabelaNome}].[{DBAdvogadosDicInfo.Pasta}]  {DevourerConsts.MsiCollate} like @{nameof(DBAdvogadosDicInfo.Pasta)}");
        cWhere.Append(filtro.Observacao.IsEmpty() ? string.Empty : (cWhere.Length == 0 ? string.Empty : filtro.LogicalOperator) + $"[{DBAdvogadosDicInfo.PTabelaNome}].[{DBAdvogadosDicInfo.Observacao}]  {DevourerConsts.MsiCollate} like @{nameof(DBAdvogadosDicInfo.Observacao)}");
        cWhere.Append(filtro.ContaBancaria.IsEmpty() ? string.Empty : (cWhere.Length == 0 ? string.Empty : filtro.LogicalOperator) + $"[{DBAdvogadosDicInfo.PTabelaNome}].[{DBAdvogadosDicInfo.ContaBancaria}]  {DevourerConsts.MsiCollate} like @{nameof(DBAdvogadosDicInfo.ContaBancaria)}");
        cWhere.Append(filtro.ParcTop == int.MinValue ? string.Empty : (cWhere.Length == 0 ? string.Empty : filtro.LogicalOperator) + $"[{DBAdvogadosDicInfo.PTabelaNome}].[{DBAdvogadosDicInfo.ParcTop}] = @{nameof(DBAdvogadosDicInfo.ParcTop)}");
        cWhere.Append(filtro.Class.IsEmpty() ? string.Empty : (cWhere.Length == 0 ? string.Empty : filtro.LogicalOperator) + $"[{DBAdvogadosDicInfo.PTabelaNome}].[{DBAdvogadosDicInfo.Class}]  {DevourerConsts.MsiCollate} like @{nameof(DBAdvogadosDicInfo.Class)}");
        cWhere.Append(filtro.Top == int.MinValue ? string.Empty : (cWhere.Length == 0 ? string.Empty : filtro.LogicalOperator) + $"[{DBAdvogadosDicInfo.PTabelaNome}].[{DBAdvogadosDicInfo.Top}] = @{nameof(DBAdvogadosDicInfo.Top)}");
        cWhere.Append(filtro.GUID.IsEmpty() ? string.Empty : (cWhere.Length == 0 ? string.Empty : filtro.LogicalOperator) + $"[{DBAdvogadosDicInfo.PTabelaNome}].[{DBAdvogadosDicInfo.GUID}]  {DevourerConsts.MsiCollate} like @{nameof(DBAdvogadosDicInfo.GUID)}");
        if (!filtro.Codigo_filtro.IsEmpty() && filtro.Codigo_filtro_end.IsEmpty())
        {
            cWhere.Append(filtro.Codigo_filtro <= 0 ? string.Empty : (cWhere.Length == 0 ? string.Empty : filtro.LogicalOperator) + $"[{DBAdvogadosDicInfo.PTabelaNome}].[{DBAdvogadosDicInfo.CampoCodigo}] >= @{nameof(DBAdvogadosDicInfo.CampoCodigo)}");
        }
        else
        {
            cWhere.Append((filtro.Codigo_filtro <= 0 && filtro.Codigo_filtro_end <= 0) ? string.Empty : (!(filtro.Codigo_filtro <= 0) && !(filtro.Codigo_filtro_end <= 0)) ? (cWhere.Length == 0 ? string.Empty : filtro.LogicalOperator) + $"{DBAdvogadosDicInfo.CampoCodigo} BETWEEN @{nameof(DBAdvogadosDicInfo.CampoCodigo)} AND @{nameof(DBAdvogadosDicInfo.CampoCodigo)}_end" : !(filtro.Codigo_filtro <= 0) ? (cWhere.Length == 0 ? string.Empty : filtro.LogicalOperator) + $"{DBAdvogadosDicInfo.CampoCodigo} = @{nameof(DBAdvogadosDicInfo.CampoCodigo)}" : (cWhere.Length == 0 ? string.Empty : filtro.LogicalOperator) + $"{DBAdvogadosDicInfo.CampoCodigo} <= @{nameof(DBAdvogadosDicInfo.CampoCodigo)}_end");
        }

        return (cWhere.ToString().Trim(), parameters);
    }

    private static string ApplyWildCard(char wildcardChar, string value)
    {
        if (wildcardChar == '\0' || wildcardChar == ' ')
        {
            return value;
        }

        var result = $"{wildcardChar}{value.Replace(" ", wildcardChar.ToString())}{wildcardChar}";
        return result;
    }

    public async Task<IEnumerable<NomeID>> GetListN([FromQuery] int max, [FromBody] Filters.FilterAdvogados? filtro, [FromRoute, Required] string uri, CancellationToken token)
    {
        // Tracking: 20250606-0
        ThrowIfDisposed();
        var filtroResult = filtro == null ? null : WFiltro(filtro!);
        string where = filtroResult?.where ?? string.Empty;
        List<SqlParameter> parameters = filtroResult?.parametros ?? [];
        using var oCnn = Configuracoes.GetConnectionByUri(uri);
        if (oCnn == null)
        {
            throw new Exception($"Coneão nula.");
        }

        var keyCache = await reader.ReadStringAuditor(uri, "", [], oCnn);
        var cacheKey = $"{uri}-Advogados-{max}-{where.GetHashCode()}-GetListN-{keyCache}";
        var entryOptions = new HybridCacheEntryOptions
        {
            Expiration = TimeSpan.FromSeconds(BaseConsts.PMaxSecondsCacheId),
            LocalCacheExpiration = TimeSpan.FromSeconds(BaseConsts.PMaxSecondsCacheId)
        };
        return await _cache.GetOrCreateAsync(cacheKey, async cancel => await GetDataListNAsync(max, uri, where, parameters, cancel), entryOptions, cancellationToken: token) ?? [];
    }

    private async Task<IEnumerable<NomeID>> GetDataListNAsync(int max, string uri, string where, List<SqlParameter> parameters, CancellationToken token)
    {
        var result = new List<NomeID>(max);
        var lista = await reader.ListarN(max, uri, where, parameters, DBAdvogadosDicInfo.CampoNome);
        foreach (var item in lista)
        {
            if (token.IsCancellationRequested)
                break;
            if (item?.FNome != null)
            {
                result.Add(new NomeID { Nome = item.FNome, ID = item.ID });
            }
        }

        return result;
    }

    private async Task<IEnumerable<AdvogadosResponseAll>> GetDataAllAsync(int max, string where, List<SqlParameter> parameters, string uri, CancellationToken token)
    {
        using var oCnn = Configuracoes.GetConnectionByUri(uri);
        if (oCnn == null)
        {
            throw new DatabaseConnectionException();
        }

        var result = await reader.Listar(max, uri, where, parameters, string.Empty, token);
        return result;
    }
}