// 100% auto-generated by Source Genesys WebApi Front & Back Creator
// copyright © 2000-2025 Menphis - Sistemas Inteligentes
// This file is part of the Source Genesys project                     
namespace MenphisSI.GerAdv.Factory
{
    /// <summary>
    /// Factory interface for creating FTipoRecurso instances in a DI-compatible way
    /// </summary>
    public interface IFTipoRecursoFactory
    {
        /// <summary>
        /// Creates a new FTipoRecurso instance
        /// </summary>
        FTipoRecurso Create();
        /// <summary>
        /// Creates a FTipoRecurso instance from SqlDataReader
        /// </summary>
        FTipoRecurso CreateFromReader(SqlDataReader? dbRec);
        /// <summary>
        /// Creates a FTipoRecurso instance from DataRow
        /// </summary>
        FTipoRecurso CreateFromDataRow(DataRow? dbRec);
        /// <summary>
        /// Creates a FTipoRecurso instance with parameters
        /// </summary>
        FTipoRecurso CreateFromParameters(List<SqlParameter>? parameters, MsiSqlConnection? oCnn, in string? cNome = "", string? fullSql = "", string sqlWhere = "", in string join = "");
        Task<FTipoRecurso> CreateAsync();
        Task<FTipoRecurso> CreateFromIdAsync(int id, MsiSqlConnection? oCnn);
        Task DeleteAsync(int operadorId, int id, MsiSqlConnection? oCnn);
    }
}