// 100% auto-generated by Source Genesys WebApi Front & Back Creator
// copyright © 2000-2025 Menphis - Sistemas Inteligentes
// This file is part of the Source Genesys project                     
export interface FilterProcessOutputRequest
{
    operator?: string;
    wildcardChar?: string;
    processoutputengine?: number;
    processoutputengine_end?: number;
    operador?: number;
    operador_end?: number;
    processo?: number;
    processo_end?: number;
    ultimoidtabelaexo?: number;
    ultimoidtabelaexo_end?: number;
    codigo_filtro?: number;
    codigo_filtro_end?: number;
}

export class FilterProcessOutputRequestDefaults implements FilterProcessOutputRequest {
    logicalOperator?: string = ' AND ';
    wildcardChar?: string = '';
    processoutputengine?: number = -2147483648;
    processoutputengine_end?: number = -2147483648;
    operador?: number = -2147483648;
    operador_end?: number = -2147483648;
    processo?: number = -2147483648;
    processo_end?: number = -2147483648;
    ultimoidtabelaexo?: number = -2147483648;
    ultimoidtabelaexo_end?: number = -2147483648;
    codigo_filtro?: number = -2147483648;
    codigo_filtro_end?: number = -2147483648;
}
    