// 100% auto-generated by Source Genesys WebApi Front & Back Creator
// copyright © 2000-2026 Menphis - Sistemas Inteligentes
// This file is part of the Source Genesys project
// Tabela:HorasTrab
// Fonte:ValidationsGenerator
namespace MenphisSI.GerAdv.Validations;
public partial interface IHorasTrabValidation
{
    Task<bool> ValidateReg(Models.HorasTrab reg, IHorasTrabService service, IClientesReader clientesReader, IAdvogadosReader advogadosReader, IFuncionariosReader funcionariosReader, IServicosReader servicosReader, [FromRoute, Required] string uri, MsiSqlConnection? oCnn);
    Task<bool> CanDelete(int? id, IHorasTrabService service, [FromRoute, Required] string uri, MsiSqlConnection? oCnn);
}

public class HorasTrabValidation : IHorasTrabValidation
{
    public async Task<bool> CanDelete(int? id, IHorasTrabService service, [FromRoute, Required] string uri, MsiSqlConnection? oCnn)
    {
        if (id == null || id <= 0)
            throw new SGValidationException("Id inválido");
        var reg = await service.GetById(id ?? default, uri, default);
        if (reg == null)
            throw new SGValidationException($"Registro com id {id} não encontrado.");
        return true;
    }

    private bool ValidSizes(Models.HorasTrab reg)
    {
        if (reg.HrIni != null && reg.HrIni.Length > DBHorasTrabDicInfo.HtbHrIni.FTamanho)
            throw new SGValidationException($"HrIni deve ter no máximo {DBHorasTrabDicInfo.HtbHrIni.FTamanho} caracteres.");
        if (reg.HrFim != null && reg.HrFim.Length > DBHorasTrabDicInfo.HtbHrFim.FTamanho)
            throw new SGValidationException($"HrFim deve ter no máximo {DBHorasTrabDicInfo.HtbHrFim.FTamanho} caracteres.");
        if (reg.Anexo != null && reg.Anexo.Length > DBHorasTrabDicInfo.HtbAnexo.FTamanho)
            throw new SGValidationException($"Anexo deve ter no máximo {DBHorasTrabDicInfo.HtbAnexo.FTamanho} caracteres.");
        if (reg.AnexoComp != null && reg.AnexoComp.Length > DBHorasTrabDicInfo.HtbAnexoComp.FTamanho)
            throw new SGValidationException($"AnexoComp deve ter no máximo {DBHorasTrabDicInfo.HtbAnexoComp.FTamanho} caracteres.");
        if (reg.AnexoUNC != null && reg.AnexoUNC.Length > DBHorasTrabDicInfo.HtbAnexoUNC.FTamanho)
            throw new SGValidationException($"AnexoUNC deve ter no máximo {DBHorasTrabDicInfo.HtbAnexoUNC.FTamanho} caracteres.");
        return true;
    }

    public async Task<bool> ValidateReg(Models.HorasTrab reg, IHorasTrabService service, IClientesReader clientesReader, IAdvogadosReader advogadosReader, IFuncionariosReader funcionariosReader, IServicosReader servicosReader, [FromRoute, Required] string uri, MsiSqlConnection? oCnn)
    {
        if (reg == null)
            throw new SGValidationException("Objeto está nulo");
        if (string.IsNullOrWhiteSpace(reg.Data))
            throw new SGValidationException("Data é obrigatório");
        if (reg.Data.Contains("%"))
            throw new SGValidationException("Data possui caracter inválido (%)");
        var validSizes = ValidSizes(reg);
        if (!validSizes)
            return false;
        if (!string.IsNullOrWhiteSpace(reg.Data))
        {
            if (DateTime.TryParse(reg.Data, out DateTime dataAntiga))
            {
                if (dataAntiga < new DateTime(1900, 1, 1))
                    throw new SGValidationException("Data não pode ser anterior a 01/01/1900.");
            }
        }

        // Clientes
        if (!reg.Cliente.IsEmptyIDNumber())
        {
            var regClientes = await clientesReader.ReadAsync(reg.Cliente, oCnn);
            if (regClientes == null || regClientes.Id != reg.Cliente)
            {
                throw new SGValidationException($"Clientes não encontrado ({regClientes?.Id}).");
            }
        }

        // Advogados
        if (!reg.Advogado.IsEmptyIDNumber())
        {
            var regAdvogados = await advogadosReader.ReadAsync(reg.Advogado, oCnn);
            if (regAdvogados == null || regAdvogados.Id != reg.Advogado)
            {
                throw new SGValidationException($"Advogados não encontrado ({regAdvogados?.Id}).");
            }
        }

        // Funcionarios
        if (!reg.Funcionario.IsEmptyIDNumber())
        {
            var regFuncionarios = await funcionariosReader.ReadAsync(reg.Funcionario, oCnn);
            if (regFuncionarios == null || regFuncionarios.Id != reg.Funcionario)
            {
                throw new SGValidationException($"Colaborador não encontrado ({regFuncionarios?.Id}).");
            }
        }

        // Servicos
        if (!reg.Servico.IsEmptyIDNumber())
        {
            var regServicos = await servicosReader.ReadAsync(reg.Servico, oCnn);
            if (regServicos == null || regServicos.Id != reg.Servico)
            {
                throw new SGValidationException($"Serviço não encontrado ({regServicos?.Id}).");
            }
        }

        return true;
    }
}