// 100% auto-generated by Source Genesys WebApi Front & Back Creator
// copyright © 2000-2025 Menphis - Sistemas Inteligentes
// This file is part of the Source Genesys project                     
namespace MenphisSI.GerAdv.Tests;
public class PenhoraStatusServiceTests : IDisposable
{
    private readonly Mock<IOptions<AppSettings>> _mockAppSettings;
    private readonly Mock<IFPenhoraStatusFactory> _mockPenhoraStatusFactory;
    private readonly Mock<IPenhoraStatusReader> _mockReader;
    private readonly Mock<IPenhoraStatusValidation> _mockValidation;
    private readonly Mock<IPenhoraStatusWriter> _mockWriter;
    private readonly Mock<IPenhoraService> _mockPenhoraService;
    private readonly Mock<IHttpContextAccessor> _mockHttpContextAccessor;
    private readonly Mock<HybridCache> _mockCache;
    private readonly Mock<IMemoryCache> _mockMemoryCache;
    private readonly PenhoraStatusService _service;
    private readonly string _validUri = "test-uri";
    public PenhoraStatusServiceTests()
    {
        _mockAppSettings = new Mock<IOptions<AppSettings>>();
        _mockPenhoraStatusFactory = new Mock<IFPenhoraStatusFactory>();
        _mockReader = new Mock<IPenhoraStatusReader>();
        _mockValidation = new Mock<IPenhoraStatusValidation>();
        _mockWriter = new Mock<IPenhoraStatusWriter>();
        _mockPenhoraService = new Mock<IPenhoraService>();
        _mockHttpContextAccessor = new Mock<IHttpContextAccessor>();
        _mockCache = new Mock<HybridCache>();
        _mockMemoryCache = new Mock<IMemoryCache>();
        var appSettings = new AppSettings();
        _mockAppSettings.Setup(x => x.Value).Returns(appSettings);
        _service = new PenhoraStatusService(_mockAppSettings.Object, _mockPenhoraStatusFactory.Object, _mockReader.Object, _mockValidation.Object, _mockWriter.Object, _mockPenhoraService.Object, _mockHttpContextAccessor.Object, _mockCache.Object, _mockMemoryCache.Object);
    }

    [Fact]
    public void Constructor_WithValidParameters_InitializesService()
    {
        // Arrange & Act
        var service = new PenhoraStatusService(_mockAppSettings.Object, _mockPenhoraStatusFactory.Object, _mockReader.Object, _mockValidation.Object, _mockWriter.Object, _mockPenhoraService.Object, _mockHttpContextAccessor.Object, _mockCache.Object, _mockMemoryCache.Object);
        // Assert
        Assert.NotNull(service);
    }

    [Fact]
    public async Task AddAndUpdate_WithNullInput_ReturnsNull()
    {
        // Act
        var result = await _service.AddAndUpdate(null, _validUri);
        // Assert
        Assert.Null(result);
    }

    [Fact]
    public async Task Delete_WithZeroId_ReturnsNull()
    {
        // Arrange
        var id = 0;
        // Act  
        var result = await _service.Delete(id, _validUri);
        // Assert
        Assert.Null(result);
    }

    [Fact]
    public async Task Delete_WithNegativeId_ReturnsNull()
    {
        // Arrange
        var id = -5;
        // Act
        var result = await _service.Delete(id, _validUri);
        // Assert
        Assert.Null(result);
    }

    [Fact]
    public async Task GetById_WithZeroId_ReturnsDefaultResponse()
    {
        // Arrange
        var id = 0;
        // Act
        var result = await _service.GetById(id, _validUri, CancellationToken.None);
        // Assert
        Assert.NotNull(result);
        Assert.Equal(0, result.Id);
    }

    [Fact]
    public async Task GetById_WithNegativeId_ReturnsDefaultResponse()
    {
        // Arrange
        var id = -1;
        // Act
        var result = await _service.GetById(id, _validUri, CancellationToken.None);
        // Assert
        Assert.NotNull(result);
        Assert.Equal(0, result.Id);
    }

    [Fact]
    public void Dispose_CalledOnce_DisposesCorrectly()
    {
        // Act
        _service.Dispose();
        // Assert - Should not throw any exception
        Assert.True(true);
    }

    [Fact]
    public void Dispose_CalledTwice_DoesNotThrow()
    {
        // Act
        _service.Dispose();
        _service.Dispose();
        // Assert - Should not throw any exception
        Assert.True(true);
    }

    [Fact]
    public void GetFilterHash_QuandoFiltroNull_DeveRetornarStringVazia()
    {
        // Usar reflexão para testar método privado
        var result = InvokePrivateMethod("GetFilterHash", null);
        result.Should().Be(string.Empty);
    }

    [Fact]
    public void GetFilterHash_QuandoFiltroValido_DeveRetornarHashSHA256()
    {
        var filtro = new FilterPenhoraStatus
        {
            Nome = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        };
        var result = InvokePrivateMethod("GetFilterHash", filtro);
        result.Should().NotBeNull();
        result.Should().BeOfType<string>();
        ((string)result).Should().NotBeNullOrEmpty();
        ((string)result).Length.Should().Be(64); // SHA256 hash length
    }

    private object InvokePrivateMethod(string methodName, Filters.FilterPenhoraStatus? parameters)
    {
        var method = typeof(PenhoraStatusService).GetMethod(methodName, BindingFlags.NonPublic | BindingFlags.Instance);
        return method.Invoke(_service, [parameters]);
    }

    [Fact]
    public async Task ThrowIfDisposed_AfterDispose_ThrowsObjectDisposedException()
    {
        // Arrange
        _service.Dispose();
        // Act & Assert
        await Assert.ThrowsAsync<ObjectDisposedException>(() => _service.GetAll(10, _validUri));
    }

    [Fact]
    public async Task Filter_WithNullFilter_ReturnsEmptyResult()
    {
        // Arrange
        var max = 10;
        var invalidUri = "invalid-uri";
        // Act & Assert
        await Assert.ThrowsAsync<Exception>(() => _service.Filter(max, null, invalidUri));
    }

    [Fact]
    public async Task GetListN_WithValidParameters_ReturnsNomeIDList()
    {
        // Arrange
        var max = 10;
        // Act
        await Assert.ThrowsAsync<Exception>(async () => await _service.GetListN(max, new Filters.FilterPenhoraStatus(), _validUri, CancellationToken.None));
    }

    public virtual void Dispose()
    {
        _service?.Dispose();
    }
}