// 100% auto-generated by Source Genesys Core
// copyright © 2000-2026 Menphis - Sistemas Inteligentes
// This file is part of the Source Genesys project                     
using MenphisSI.SG.GerAdv.DicInfo;

// ReSharper disable once CheckNamespace
namespace MenphisSI.SG.GerAdv;
public static partial class DBAreaDicInfo
{
    public const string CampoCodigo = "areCodigo";
    public const string CampoNome = "areDescricao";
    public const string TablePrefix = "are";
    public const string Descricao = "areDescricao"; // LOCALIZACAO 170523
    public const string Top = "areTop"; // LOCALIZACAO 170523
    public const string Guid = "areGuid"; // LOCALIZACAO 170523
    public const string QuemCad = "areQuemCad"; // LOCALIZACAO 170523
    public const string DtCad = "areDtCad"; // LOCALIZACAO 170523
    public const string QuemAtu = "areQuemAtu"; // LOCALIZACAO 170523
    public const string DtAtu = "areDtAtu"; // LOCALIZACAO 170523
    public const string Visto = "areVisto"; // LOCALIZACAO 170523
    public static string GetNameFieldByENum(NomesCamposTabela idField) => ((int)idField) switch
    {
        1 => Descricao,
        2 => Top,
        3 => QuemCad,
        4 => DtCad,
        5 => QuemAtu,
        6 => DtAtu,
        7 => Visto,
        _ => string.Empty
    };
    public static string TabelaNome => PTabelaNome;

    public const string PTabelaNome = "Area";
#region PropriedadesDaTabela
    public static DBInfoSystem AreDescricao => new(0, PTabelaNome, CampoCodigo, Descricao, 40, "Descrição", "Descrição", EDataTypeSystemInfo.SystemInfoText, true, false, false, prefixo: "are");
    public static DBInfoSystem AreTop => new(0, PTabelaNome, CampoCodigo, Top, "Top", "Top", EDataTypeSystemInfo.SystemInfoBoolean, prefixo: "are");
    public static DBInfoSystem AreGuid => new(0, PTabelaNome, CampoCodigo, Guid, 100, "GUID", "GUID", EDataTypeSystemInfo.SystemInfoTextGuid, true, false, false, prefixo: "are");
    public static DBInfoSystem AreQuemCad => new(0, PTabelaNome, CampoCodigo, QuemCad, "Usuário de Cadastro", "Usuário de Cadastro", EDataTypeSystemInfo.SystemInfoForeingkeyWhoAdd, DBOperadorDicInfo.CampoCodigo, DBOperadorDicInfo.TabelaNome, new DBOperadorODicInfo(), false, prefixo: "are"); // DBI 11 
    public static DBInfoSystem AreDtCad => new(0, PTabelaNome, CampoCodigo, DtCad, "Data de Cadastro", "Data de Cadastro", EDataTypeSystemInfo.SystemInfoDateAdd, prefixo: "are");
    public static DBInfoSystem AreQuemAtu => new(0, PTabelaNome, CampoCodigo, QuemAtu, "Usuário de Atualização", "Usuário de Atualização", EDataTypeSystemInfo.SystemInfoForeingkeyWhoUpdt, DBOperadorDicInfo.CampoCodigo, DBOperadorDicInfo.TabelaNome, new DBOperadorODicInfo(), false, prefixo: "are"); // DBI 11 
    public static DBInfoSystem AreDtAtu => new(0, PTabelaNome, CampoCodigo, DtAtu, "Data de Atualização", "Data de Atualização", EDataTypeSystemInfo.SystemInfoDateUpdt, prefixo: "are");
    public static DBInfoSystem AreVisto => new(0, PTabelaNome, CampoCodigo, Visto, "Visto", "Visto", EDataTypeSystemInfo.SystemInfoBooleanAuditorReviewed, prefixo: "are", isRequired: true);

#endregion
    [Serializable]
    public enum NomesCamposTabela
    {
        AreDescricao = 1,
        AreTop = 2,
        AreQuemCad = 3,
        AreDtCad = 4,
        AreQuemAtu = 5,
        AreDtAtu = 6,
        AreVisto = 7
    }

    public static DBInfoSystem? GetInfoSystemByEnum(NomesCamposTabela idTable) => idTable switch
    {
        NomesCamposTabela.AreDescricao => AreDescricao,
        NomesCamposTabela.AreTop => AreTop,
        NomesCamposTabela.AreQuemCad => AreQuemCad,
        NomesCamposTabela.AreDtCad => AreDtCad,
        NomesCamposTabela.AreQuemAtu => AreQuemAtu,
        NomesCamposTabela.AreDtAtu => AreDtAtu,
        NomesCamposTabela.AreVisto => AreVisto,
        _ => null
    };
}