namespace MenphisSI.GerAdv.Interface;
public partial interface IDBProcessos
{
    public int ID { get; set; }
    public int FAdvParc { get; set; }
    public bool FAJGPedidoNegado { get; set; }
    public bool FAJGCliente { get; set; }
    public bool FAJGPedidoNegadoOPO { get; set; }
    public bool FNotificarPOE { get; set; }
    public decimal FValorProvisionado { get; set; }
    public bool FAJGOponente { get; set; }
    public decimal FValorCacheCalculo { get; set; }
    public bool FAJGPedidoOPO { get; set; }
    public decimal FValorCacheCalculoProv { get; set; }
    public bool FConsiderarParado { get; set; }
    public bool FValorCalculado { get; set; }
    public bool FAJGConcedidoOPO { get; set; }
    public bool FCobranca { get; set; }
    public string? FDataEntrada { get; set; }
    public bool FPenhora { get; set; }
    public bool FAJGPedido { get; set; }
    public int FTipoBaixa { get; set; }
    public int FClassRisco { get; set; }
    public bool FIsApenso { get; set; }
    public decimal FValorCausaInicial { get; set; }
    public bool FAJGConcedido { get; set; }
    public string? FObsBCX { get; set; }
    public decimal FValorCausaDefinitivo { get; set; }
    public decimal FPercProbExito { get; set; }
    public bool FMNA { get; set; }
    public decimal FPercExito { get; set; }
    public string? FNroExtra { get; set; }
    public int FAdvOpo { get; set; }
    public bool FExtra { get; set; }
    public int FJustica { get; set; }
    public int FAdvogado { get; set; }
    public string? FNroCaixa { get; set; }
    public int FPreposto { get; set; }
    public int FCliente { get; set; }
    public int FOponente { get; set; }
    public int FArea { get; set; }
    public int FCidade { get; set; }
    public int FSituacao { get; set; }
    public bool FIDSituacao { get; set; }
    public decimal FValor { get; set; }
    public int FRito { get; set; }
    public string? FFato { get; set; }
    public string? FNroPasta { get; set; }
    public int FAtividade { get; set; }
    public string? FCaixaMorto { get; set; }
    public bool FBaixado { get; set; }
    public string? FDtBaixa { get; set; }
    public string? FMotivoBaixa { get; set; }
    public string? FOBS { get; set; }
    public bool FPrinted { get; set; }
    public string? FZKey { get; set; }
    public int FZKeyQuem { get; set; }
    public string? FZKeyQuando { get; set; }
    public string? FResumo { get; set; }
    public bool FNaoImprimir { get; set; }
    public bool FEletronico { get; set; }
    public string? FNroContrato { get; set; }
    public string? FPercProbExitoJustificativa { get; set; }
    public decimal FHonorarioValor { get; set; }
    public decimal FHonorarioPercentual { get; set; }
    public decimal FHonorarioSucumbencia { get; set; }
    public int FFaseAuditoria { get; set; }
    public decimal FValorCondenacao { get; set; }
    public decimal FValorCondenacaoCalculado { get; set; }
    public int FValorCondenacaoProvisorio { get; set; }
    public string? FGUID { get; set; }
}