// 100% auto-generated by Source Genesys WebApi Front & Back Creator
// copyright © 2000-2025 Menphis - Sistemas Inteligentes
// This file is part of the Source Genesys project                     
namespace MenphisSI.SG.GerAdv;
public partial class DBAgendaRecords
{
    /// <summary>
    /// Factory method async para carregar [tableMin]
    /// </summary>
    public static async Task<DBAgendaRecords> CreateAsync(int nCodigo, MsiSqlConnection? oCnn, CancellationToken cancellationToken = default)
    {
        var registro = new DBAgendaRecords();
        await registro.CarregarAsync(nCodigo, oCnn, cancellationToken);
        return registro;
    }

    /// <summary>
    /// Carregar dados async
    /// </summary>
    protected async Task CarregarAsync(int id, MsiSqlConnection? oCnn, CancellationToken cancellationToken = default)
    {
        if (id.IsEmptyIDNumber() || oCnn is null)
            return;
        using var cmd = new SqlCommand($"{ConfiguracoesDBT.SQLNoCount}SELECT TOP (1) {CamposSqlX} FROM {PTabelaNome.dbo(oCnn)} WHERE [{CampoCodigo}] = @ThisIDToLoad", oCnn.InnerConnection);
        cmd.Parameters.AddWithValue("@ThisIDToLoad", id);
        using var ds = await ConfiguracoesDBT.GetDataTableAsync(cmd, CommandBehavior.SingleRow, oCnn, cancellationToken);
        if (ds?.Rows.Count > 0)
        {
            CarregarDadosBd(ds.Rows[0]);
        }
    }

#if (!NOTSTORED_AgendaRecords)
    /// <summary>
    /// Update async com timeout e cancellation
    /// </summary>
    public async Task<int> UpdateAsync(MsiSqlConnection? oCnn, int insertId = 0, CancellationToken cancellationToken = default, int timeoutSeconds = 30)
    {
        var isInsert = insertId == 0 && ID == 0;
        if (!isInsert && !HasAnyFieldChanged())
            return 0;
        if (oCnn is null)
        {
#if DEBUG
            PTabelaNome.PopupBox("oCnn is null - UpdateAsync()");
#endif
            return 0;
        }

        try
        {
            var updateTool = new DBToolWTable32Async(PTabelaNome, CampoCodigo, ID == 0)
            {
                IsMachineCode = true,
            };
            updateTool.Where = isInsert ? string.Empty : $"{CampoCodigo}={ID}";
            ConfigureUpdateFields(updateTool);
            ConfigureAuditorFields(updateTool);
            if (insertId != 0)
            {
                return await GravaNewIdAsync(updateTool, insertId, oCnn, cancellationToken);
            }

            var result = await updateTool.RecUpdateAsync(oCnn, cancellationToken);
            if (updateTool.Insert && result == "OK")
            {
                ID = updateTool.GetCodigo();
                if (ID == 0)
                {
                    Error = -2;
                    ErrorDescription = "O registro não pode ser incluído, tente mais tarde.";
                    return Error;
                }
            }

            return result == "OK" ? 0 : -1;
        }
        catch (OperationCanceledException)
        {
            throw;
        }
        catch (Exception ex)
        {
            Error = -1;
            ErrorDescription = ex.Message;
            return Error;
        }
    }

#endif
    /// <summary>
    /// Verificar se existe async
    /// </summary>
    public static async Task<bool> ExisteAsync(int id, MsiSqlConnection? oCnn, CancellationToken cancellationToken = default)
    {
        if (oCnn is null || id <= 0)
            return false;
        var existe = await ConfiguracoesDBT.GetScalarAsync<int?>($"SELECT 1 FROM {PTabelaNome.dbo(oCnn)} WHERE {CampoCodigo} = {id}", oCnn, cancellationToken);
        return existe.HasValue;
    }

    /// <summary>
    /// Delete async
    /// </summary>
    /// <param name = "operadorId">For future Audity</param>
    /// <param name = "id"></param>
    /// <param name = "oCnn"></param>
    /// <param name = "cancellationToken"></param>
    /// <returns></returns>
    /// <exception cref = "InvalidOperationException"></exception>
    public static async Task<bool> DeleteRecordAsync(int operadorId, int id, MsiSqlConnection? oCnn, CancellationToken cancellationToken = default)
    {
        if (oCnn is null || id <= 0)
            return false;
        var sql = $"DELETE FROM {PTabelaNome.dbo(oCnn)} WHERE {CampoCodigo} = @Id";
        try
        {
            using var cmd = new SqlCommand(sql, oCnn.InnerConnection);
            cmd.Parameters.AddWithValue("@Id", id);
            var rowsAffected = await cmd.ExecuteNonQueryAsync(cancellationToken);
            return rowsAffected > 0;
        }
        catch (SqlException ex)when (ex.Number == 547)
        {
            throw new InvalidOperationException("Este registro não pode ser excluído, pois está vinculado a outros registros.");
        }
    }

#if (!NOTSTORED_AgendaRecords)
    // Helper methods
    private bool HasAnyFieldChanged() => pFldFAgenda || pFldFJulgador || pFldFClientesSocios || pFldFPerito || pFldFColaborador || pFldFForo || pFldFAviso1 || pFldFAviso2 || pFldFAviso3 || pFldFCrmAviso1 || pFldFCrmAviso2 || pFldFCrmAviso3 || pFldFDataAviso1 || pFldFDataAviso2 || pFldFDataAviso3;
    private void ConfigureUpdateFields(DBToolWTable32Async updateTool)
    {
        if (pFldFAgenda)
            updateTool.Fields(DBAgendaRecordsDicInfo.Agenda, m_FAgenda, ETiposCampos.FNumber);
        if (pFldFJulgador)
            updateTool.Fields(DBAgendaRecordsDicInfo.Julgador, m_FJulgador, ETiposCampos.FNumber);
        if (pFldFClientesSocios)
            updateTool.Fields(DBAgendaRecordsDicInfo.ClientesSocios, m_FClientesSocios, ETiposCampos.FNumber);
        if (pFldFPerito)
            updateTool.Fields(DBAgendaRecordsDicInfo.Perito, m_FPerito, ETiposCampos.FNumber);
        if (pFldFColaborador)
            updateTool.Fields(DBAgendaRecordsDicInfo.Colaborador, m_FColaborador, ETiposCampos.FNumber);
        if (pFldFForo)
            updateTool.Fields(DBAgendaRecordsDicInfo.Foro, m_FForo, ETiposCampos.FNumber);
        if (pFldFAviso1)
            updateTool.Fields(DBAgendaRecordsDicInfo.Aviso1, m_FAviso1, ETiposCampos.FBoolean);
        if (pFldFAviso2)
            updateTool.Fields(DBAgendaRecordsDicInfo.Aviso2, m_FAviso2, ETiposCampos.FBoolean);
        if (pFldFAviso3)
            updateTool.Fields(DBAgendaRecordsDicInfo.Aviso3, m_FAviso3, ETiposCampos.FBoolean);
        if (pFldFCrmAviso1)
            updateTool.Fields(DBAgendaRecordsDicInfo.CrmAviso1, m_FCrmAviso1, ETiposCampos.FNumber);
        if (pFldFCrmAviso2)
            updateTool.Fields(DBAgendaRecordsDicInfo.CrmAviso2, m_FCrmAviso2, ETiposCampos.FNumber);
        if (pFldFCrmAviso3)
            updateTool.Fields(DBAgendaRecordsDicInfo.CrmAviso3, m_FCrmAviso3, ETiposCampos.FNumber);
        if (pFldFDataAviso1)
            updateTool.Fields(DBAgendaRecordsDicInfo.DataAviso1, m_FDataAviso1, ETiposCampos.FDate);
        if (pFldFDataAviso2)
            updateTool.Fields(DBAgendaRecordsDicInfo.DataAviso2, m_FDataAviso2, ETiposCampos.FDate);
        if (pFldFDataAviso3)
            updateTool.Fields(DBAgendaRecordsDicInfo.DataAviso3, m_FDataAviso3, ETiposCampos.FDate);
    }

#endif
    private void ConfigureAuditorFields(DBToolWTable32Async updateTool)
    {
    }

    private async Task<int> GravaNewIdAsync(DBToolWTable32Async updateTool, int insertId, MsiSqlConnection oCnn, CancellationToken cancellationToken)
    {
        ID = insertId;
        updateTool.Fields(CampoCodigo, insertId, ETiposCampos.FNumber);
        var result = await updateTool.RecUpdateAsync(oCnn, cancellationToken, true);
        return result == "OK" ? 0 : -3;
    }
}