// 100% auto-generated by Source Genesys WebApi Front & Back Creator
// copyright © 2000-2025 Menphis - Sistemas Inteligentes
// This file is part of the Source Genesys project                     
// Page.test.tsx.txt
// Test for Operadores page
import React from 'react';
import { render, screen } from '@testing-library/react';
import '@testing-library/jest-dom';
import { jest, describe, test, beforeAll, afterAll, expect } from '@jest/globals';

// Mock PageTitle and PageLayout to keep test focused
jest.mock('@/app/components/PageTitle', () => ({
  PageTitle: ({ title }: any) => <h1>{title}</h1>
}));

jest.mock('@/app/components/Cruds/PageLayout', () => ({
  PageLayout: ({ children }: any) => <div data-testid='page-layout'>{children}</div>
}));

// Mock OperadoresGridAdapter to avoid instantiation complexity
jest.mock('@/app/GerAdv_TS/Operadores/Adapter/OperadoresGridAdapter', () => ({
  OperadoresGridAdapter: jest.fn().mockImplementation(() => ({
    render: () => <div data-testid='mock-grid'>Mock Grid</div>
  }))
}));

// Mock OperadoresGridContainer to assert it receives the mocked grid
jest.mock('@/app/GerAdv_TS/Operadores/Components/OperadoresGridContainer', () => ({
  __esModule: true,
  default: ({ grid }: any) => (
    <div data-testid='operadores-container'>{grid?.render ? grid.render() : null}</div>
  )
}));

// Import the page after mocks so imports pick them up
import OperadoresPage from '@/app/pages/operadores/page';

describe('Operadores page', () => {
  beforeAll(() => {
    jest.spyOn(console, 'error').mockImplementation(() => {});
  });

  afterAll(() => {
    (console.error as any).mockRestore?.();
  });

  test('renders PageTitle and OperadoresGridContainer', () => {
    render(<OperadoresPage />);

    expect(screen.getByRole('heading', { name: /Operadores/i })).toBeInTheDocument();
    expect(screen.getByTestId('operadores-container')).toBeInTheDocument();
    expect(screen.getByTestId('mock-grid')).toBeInTheDocument();
  });
});

