// 100% auto-generated by Source Genesys WebApi Front & Back Creator
// copyright © 2000-2026 Menphis - Sistemas Inteligentes
// This file is part of the Source Genesys project
// Tabela:EventoPrazoAgenda
// Fonte:ValidationsGenerator
namespace MenphisSI.GerAdv.Validations;
public partial interface IEventoPrazoAgendaValidation
{
    Task<bool> ValidateReg(Models.EventoPrazoAgenda reg, IEventoPrazoAgendaService service, [FromRoute, Required] string uri, MsiSqlConnection? oCnn);
    Task<bool> CanDelete(int? id, IEventoPrazoAgendaService service, [FromRoute, Required] string uri, MsiSqlConnection? oCnn);
}

public class EventoPrazoAgendaValidation : IEventoPrazoAgendaValidation
{
    public async Task<bool> CanDelete(int? id, IEventoPrazoAgendaService service, [FromRoute, Required] string uri, MsiSqlConnection? oCnn)
    {
        if (id == null || id <= 0)
            throw new SGValidationException("Id inválido");
        var reg = await service.GetById(id ?? default, uri, default);
        if (reg == null)
            throw new SGValidationException($"Registro com id {id} não encontrado.");
        return true;
    }

    private bool ValidSizes(Models.EventoPrazoAgenda reg)
    {
        if (reg.Nome != null && reg.Nome.Length > DBEventoPrazoAgendaDicInfo.EpaNome.FTamanho)
            throw new SGValidationException($"Nome deve ter no máximo {DBEventoPrazoAgendaDicInfo.EpaNome.FTamanho} caracteres.");
        return true;
    }

    public async Task<bool> ValidateReg(Models.EventoPrazoAgenda reg, IEventoPrazoAgendaService service, [FromRoute, Required] string uri, MsiSqlConnection? oCnn)
    {
        if (reg == null)
            throw new SGValidationException("Objeto está nulo");
        if (string.IsNullOrWhiteSpace(reg.Nome))
            throw new SGValidationException("Nome é obrigatório");
        if (reg.Nome.Contains("%"))
            throw new SGValidationException("Nome possui caracter inválido (%)");
        var validSizes = ValidSizes(reg);
        if (!validSizes)
            return false;
        await Task.Delay(0);
        return true;
    }
}