// 100% auto-generated by Source Genesys WebApi Front & Back Creator
// copyright © 2000-2025 Menphis - Sistemas Inteligentes
// This file is part of the Source Genesys project                     
// WindowId.test.tsx.txt
import PaisesWindowId from '@/app/GerAdv_TS/Paises/Crud/Grids/PaisesWindowId';
import React from 'react';
import { render, screen, waitFor } from '@testing-library/react';
import PaisesWindowId from '@/app/GerAdv_TS/Paises/Crud/Grids/PaisesWindowId';
import { PaisesEmpty } from '@/app/GerAdv_TS/Models/Paises';

describe('PaisesWindowId (basic)', () => {
  it('exports the component', () => {
    expect(PaisesWindowId).toBeDefined();
    expect(typeof PaisesWindowId === 'function' || typeof PaisesWindowId === 'object').toBe(true);
  });
});



// Mock system context used by the component
const mockUseSystemContext = jest.fn();
jest.mock('@/app/context/SystemContext', () => ({
  useSystemContext: () => mockUseSystemContext(),
}));

// Mock the PaisesService class so constructor usage doesn't throw and we can control fetchPaisesById
const mockFetchPaisesById = jest.fn();
jest.mock('@/app/GerAdv_TS/Paises/Services/Paises.service', () => ({
  PaisesService: jest.fn().mockImplementation(() => ({
    fetchPaisesById: (...args: any[]) => mockFetchPaisesById(...args),
  })),
}));

// Mock the child PaisesWindow to capture props passed to it
jest.mock('@/app/GerAdv_TS/Paises/Crud/Grids/PaisesWindow', () => ({
  __esModule: true,
  default: (p: any) => <div data-testid='paises-window' {...p} />,
}));

describe('PaisesWindowId', () => {
  beforeEach(() => {
    jest.clearAllMocks();
    mockUseSystemContext.mockReturnValue({ systemContext: { Uri: 'u', Token: 't' } });
  });

  it('is defined and is a component', () => {
    expect(PaisesWindowId).toBeDefined();
    expect(typeof PaisesWindowId === 'function' || typeof PaisesWindowId === 'object').toBe(true);
  });

  it('returns null (renders nothing) when isOpen is false', () => {
    const { container } = render(
      <PaisesWindowId isOpen={false} onClose={() => {}} onSuccess={() => {}} onError={() => {}} />
    );
    expect(container).toBeEmptyDOMElement();
  });

  it('renders PaisesWindow with PaisesEmpty when id is 0', async () => {
    render(
      <PaisesWindowId isOpen={true} id={0} onClose={() => {}} onSuccess={() => {}} onError={() => {}} />
    );

    // PaisesWindow should be rendered with selectedPaises equal to PaisesEmpty()
    const node = await screen.findByTestId('paises-window');
    expect(node).toBeInTheDocument();
    // prop exists on the mocked node as an attribute named "selectedPaises"
    // React testing library renders object props as [object Object] when stringified; assert presence
    expect(node.getAttribute('selectedpaises') || node.getAttribute('selectedPaises')).not.toBeNull();
  });

  it('fetches paises by id and passes it to PaisesWindow when id > 0', async () => {
    const fakePaises = { id: 123, nomecliente: 'Test' };
    mockFetchPaisesById.mockResolvedValue(fakePaises);

    render(
      <PaisesWindowId isOpen={true} id={123} onClose={() => {}} onSuccess={() => {}} onError={() => {}} />
    );

    // wait for child to be rendered after async fetch
    const node = await screen.findByTestId('paises-window');
    expect(node).toBeInTheDocument();
    // ensure our mock was called with the id
    await waitFor(() => expect(mockFetchPaisesById).toHaveBeenCalledWith(123));
  });
});
