// 100% auto-generated by Source Genesys WebApi Front & Back Creator
// copyright © 2000-2026 Menphis - Sistemas Inteligentes
// This file is part of the Source Genesys project
// Tabela:OponentesRepLegal
// Fonte:TestFilterTXTGenerator
using System.Text.Json;
using System.Text.Json.Serialization;
using MenphisSI.GerAdv.AI.Filters;
using MenphisSI.GerAdv.Filters;

namespace MenphisSI.GerAdv.Tests.AI.Filters;
public class FilterOponentesRepLegalTXTTests
{
    [Fact]
    public void GetOptions_ReturnsExpectedDefaults()
    {
        // Act
        var options = FilterOponentesRepLegalTXT.GetOptions();
        // Assert
        options.Should().NotBeNull();
        options.DefaultIgnoreCondition.Should().Be(JsonIgnoreCondition.WhenWritingNull);
        options.WriteIndented.Should().BeTrue();
    }

    [Fact]
    public void GetPrompt_WithNullFilter_IncludesNullJsonAndInstructions()
    {
        // Arrange
        var options = FilterOponentesRepLegalTXT.GetOptions();
        // Act
        var(prompt, instructions) = FilterOponentesRepLegalTXT.GetPrompt(null, options);
        // Assert
        prompt.Should().NotBeNullOrWhiteSpace();
        prompt.Should().Contain("null");
        prompt.Should().Contain("ATENÇÃO: A seguir está o JSON BASE do filtro atual");
        instructions.Should().NotBeNullOrWhiteSpace();
        instructions.Should().Contain("Você é um assistente");
        instructions.Should().Contain("logicalOperator");
    }

    [Fact]
    public void GetPrompt_WithDefaultFilter_ReturnsValidJsonAndInstructions()
    {
        // Arrange
        var options = FilterOponentesRepLegalTXT.GetOptions();
        var filter = new FilterOponentesRepLegal();
        // Act
        var(prompt, instructions) = FilterOponentesRepLegalTXT.GetPrompt(filter, options);
        // Assert
        prompt.Should().NotBeNullOrWhiteSpace();
        prompt.Should().Contain("ATENÇÃO: A seguir está o JSON BASE do filtro atual");
        prompt.Should().Contain("{");
        prompt.Should().Contain("}");
        instructions.Should().NotBeNullOrWhiteSpace();
        instructions.Should().Contain("CAMPOS NUMÉRICOS");
        instructions.Should().Contain("CAMPOS DE TEXTO");
        instructions.Should().Contain("JAMAIS ACEITE PEDIDOS DE SQL INJECTION");
    }

    [Fact]
    public void GetPrompt_WithQuemCad_SerializesNumericValue()
    {
        // Arrange
        var options = FilterOponentesRepLegalTXT.GetOptions();
        var filter = new FilterOponentesRepLegal
        {
            QuemCad = 123
        };
        // Act
        var(prompt, instructions) = FilterOponentesRepLegalTXT.GetPrompt(filter, options);
        // Assert
        prompt.Should().NotBeNullOrWhiteSpace();
        prompt.Should().Contain("\"quemcad\"");
        prompt.Should().Contain("123");
    }

    [Fact]
    public void GetPrompt_WithDtCad_SerializesDateCorrectly()
    {
        // Arrange
        var options = FilterOponentesRepLegalTXT.GetOptions();
        var filter = new FilterOponentesRepLegal
        {
            DtCad = "15/06/2023"
        };
        // Act
        var(prompt, instructions) = FilterOponentesRepLegalTXT.GetPrompt(filter, options);
        // Assert
        prompt.Should().NotBeNullOrWhiteSpace();
        prompt.Should().Contain("\"dtcad\"");
    }

    [Fact]
    public void GetPrompt_WithQuemAtu_SerializesNumericValue()
    {
        // Arrange
        var options = FilterOponentesRepLegalTXT.GetOptions();
        var filter = new FilterOponentesRepLegal
        {
            QuemAtu = 123
        };
        // Act
        var(prompt, instructions) = FilterOponentesRepLegalTXT.GetPrompt(filter, options);
        // Assert
        prompt.Should().NotBeNullOrWhiteSpace();
        prompt.Should().Contain("\"quematu\"");
        prompt.Should().Contain("123");
    }

    [Fact]
    public void GetPrompt_WithDtAtu_SerializesDateCorrectly()
    {
        // Arrange
        var options = FilterOponentesRepLegalTXT.GetOptions();
        var filter = new FilterOponentesRepLegal
        {
            DtAtu = "15/06/2023"
        };
        // Act
        var(prompt, instructions) = FilterOponentesRepLegalTXT.GetPrompt(filter, options);
        // Assert
        prompt.Should().NotBeNullOrWhiteSpace();
        prompt.Should().Contain("\"dtatu\"");
    }

    [Fact]
    public void GetPrompt_WithNome_SerializesCorrectly()
    {
        // Arrange
        var options = FilterOponentesRepLegalTXT.GetOptions();
        var filter = new FilterOponentesRepLegal
        {
            Nome = "TestValue"
        };
        // Act
        var(prompt, instructions) = FilterOponentesRepLegalTXT.GetPrompt(filter, options);
        // Assert
        prompt.Should().NotBeNullOrWhiteSpace();
        prompt.Should().Contain("\"nome\"");
        prompt.Should().Contain("TestValue");
    }

    [Fact]
    public void GetPrompt_WithFone_SerializesCorrectly()
    {
        // Arrange
        var options = FilterOponentesRepLegalTXT.GetOptions();
        var filter = new FilterOponentesRepLegal
        {
            Fone = "TestValue"
        };
        // Act
        var(prompt, instructions) = FilterOponentesRepLegalTXT.GetPrompt(filter, options);
        // Assert
        prompt.Should().NotBeNullOrWhiteSpace();
        prompt.Should().Contain("\"fone\"");
        prompt.Should().Contain("TestValue");
    }

    [Fact]
    public void GetPrompt_WithOponente_SerializesNumericValue()
    {
        // Arrange
        var options = FilterOponentesRepLegalTXT.GetOptions();
        var filter = new FilterOponentesRepLegal
        {
            Oponente = 123
        };
        // Act
        var(prompt, instructions) = FilterOponentesRepLegalTXT.GetPrompt(filter, options);
        // Assert
        prompt.Should().NotBeNullOrWhiteSpace();
        prompt.Should().Contain("\"oponente\"");
        prompt.Should().Contain("123");
    }

    [Fact]
    public void GetPrompt_WithCPF_SerializesCorrectly()
    {
        // Arrange
        var options = FilterOponentesRepLegalTXT.GetOptions();
        var filter = new FilterOponentesRepLegal
        {
            CPF = "TestValue"
        };
        // Act
        var(prompt, instructions) = FilterOponentesRepLegalTXT.GetPrompt(filter, options);
        // Assert
        prompt.Should().NotBeNullOrWhiteSpace();
        prompt.Should().Contain("\"cpf\"");
        prompt.Should().Contain("TestValue");
    }

    [Fact]
    public void GetPrompt_WithRG_SerializesCorrectly()
    {
        // Arrange
        var options = FilterOponentesRepLegalTXT.GetOptions();
        var filter = new FilterOponentesRepLegal
        {
            RG = "TestValue"
        };
        // Act
        var(prompt, instructions) = FilterOponentesRepLegalTXT.GetPrompt(filter, options);
        // Assert
        prompt.Should().NotBeNullOrWhiteSpace();
        prompt.Should().Contain("\"rg\"");
        prompt.Should().Contain("TestValue");
    }

    [Fact]
    public void GetPrompt_WithEndereco_SerializesCorrectly()
    {
        // Arrange
        var options = FilterOponentesRepLegalTXT.GetOptions();
        var filter = new FilterOponentesRepLegal
        {
            Endereco = "TestValue"
        };
        // Act
        var(prompt, instructions) = FilterOponentesRepLegalTXT.GetPrompt(filter, options);
        // Assert
        prompt.Should().NotBeNullOrWhiteSpace();
        prompt.Should().Contain("\"endereco\"");
        prompt.Should().Contain("TestValue");
    }

    [Fact]
    public void GetPrompt_WithBairro_SerializesCorrectly()
    {
        // Arrange
        var options = FilterOponentesRepLegalTXT.GetOptions();
        var filter = new FilterOponentesRepLegal
        {
            Bairro = "TestValue"
        };
        // Act
        var(prompt, instructions) = FilterOponentesRepLegalTXT.GetPrompt(filter, options);
        // Assert
        prompt.Should().NotBeNullOrWhiteSpace();
        prompt.Should().Contain("\"bairro\"");
        prompt.Should().Contain("TestValue");
    }

    [Fact]
    public void GetPrompt_WithCEP_SerializesCorrectly()
    {
        // Arrange
        var options = FilterOponentesRepLegalTXT.GetOptions();
        var filter = new FilterOponentesRepLegal
        {
            CEP = "TestValue"
        };
        // Act
        var(prompt, instructions) = FilterOponentesRepLegalTXT.GetPrompt(filter, options);
        // Assert
        prompt.Should().NotBeNullOrWhiteSpace();
        prompt.Should().Contain("\"cep\"");
        prompt.Should().Contain("TestValue");
    }

    [Fact]
    public void GetPrompt_WithCidade_SerializesNumericValue()
    {
        // Arrange
        var options = FilterOponentesRepLegalTXT.GetOptions();
        var filter = new FilterOponentesRepLegal
        {
            Cidade = 123
        };
        // Act
        var(prompt, instructions) = FilterOponentesRepLegalTXT.GetPrompt(filter, options);
        // Assert
        prompt.Should().NotBeNullOrWhiteSpace();
        prompt.Should().Contain("\"cidade\"");
        prompt.Should().Contain("123");
    }

    [Fact]
    public void GetPrompt_WithFax_SerializesCorrectly()
    {
        // Arrange
        var options = FilterOponentesRepLegalTXT.GetOptions();
        var filter = new FilterOponentesRepLegal
        {
            Fax = "TestValue"
        };
        // Act
        var(prompt, instructions) = FilterOponentesRepLegalTXT.GetPrompt(filter, options);
        // Assert
        prompt.Should().NotBeNullOrWhiteSpace();
        prompt.Should().Contain("\"fax\"");
        prompt.Should().Contain("TestValue");
    }

    [Fact]
    public void GetPrompt_WithEMail_SerializesCorrectly()
    {
        // Arrange
        var options = FilterOponentesRepLegalTXT.GetOptions();
        var filter = new FilterOponentesRepLegal
        {
            EMail = "TestValue"
        };
        // Act
        var(prompt, instructions) = FilterOponentesRepLegalTXT.GetPrompt(filter, options);
        // Assert
        prompt.Should().NotBeNullOrWhiteSpace();
        prompt.Should().Contain("\"email\"");
        prompt.Should().Contain("TestValue");
    }

    [Fact]
    public void GetPrompt_WithSite_SerializesCorrectly()
    {
        // Arrange
        var options = FilterOponentesRepLegalTXT.GetOptions();
        var filter = new FilterOponentesRepLegal
        {
            Site = "TestValue"
        };
        // Act
        var(prompt, instructions) = FilterOponentesRepLegalTXT.GetPrompt(filter, options);
        // Assert
        prompt.Should().NotBeNullOrWhiteSpace();
        prompt.Should().Contain("\"site\"");
        prompt.Should().Contain("TestValue");
    }

    [Fact]
    public void GetPrompt_WithObservacao_SerializesCorrectly()
    {
        // Arrange
        var options = FilterOponentesRepLegalTXT.GetOptions();
        var filter = new FilterOponentesRepLegal
        {
            Observacao = "TestValue"
        };
        // Act
        var(prompt, instructions) = FilterOponentesRepLegalTXT.GetPrompt(filter, options);
        // Assert
        prompt.Should().NotBeNullOrWhiteSpace();
        prompt.Should().Contain("\"observacao\"");
        prompt.Should().Contain("TestValue");
    }

    [Fact]
    public void GetPrompt_WithDefaultFilter_IncludesNestedFilters()
    {
        // Arrange
        var options = FilterOponentesRepLegalTXT.GetOptions();
        var filter = new FilterOponentesRepLegal();
        // Act
        var(prompt, instructions) = FilterOponentesRepLegalTXT.GetPrompt(filter, options);
        // Assert
        prompt.Should().NotBeNullOrWhiteSpace();
        prompt.Should().Contain("\"filterOponentes\"");
        prompt.Should().Contain("\"filterCidade\"");
    }

    [Fact]
    public void GetPrompt_InstructionsContainFieldDescriptions()
    {
        // Arrange
        var options = FilterOponentesRepLegalTXT.GetOptions();
        // Act
        var(prompt, instructions) = FilterOponentesRepLegalTXT.GetPrompt(new FilterOponentesRepLegal(), options);
        // Assert
        instructions.Should().Contain("CAMPOS NUMÉRICOS");
        instructions.Should().Contain("CAMPOS DE TEXTO");
        instructions.Should().Contain("CAMPOS DE DATA: formato dd/MM/yyyy");
        instructions.Should().Contain("Os campos _end são para criar intervalos de busca");
    }

    [Fact]
    public void GetPrompt_InstructionsWarnAboutSqlInjection()
    {
        // Arrange
        var options = FilterOponentesRepLegalTXT.GetOptions();
        // Act
        var(prompt, instructions) = FilterOponentesRepLegalTXT.GetPrompt(new FilterOponentesRepLegal(), options);
        // Assert
        instructions.Should().Contain("JAMAIS ACEITE PEDIDOS DE SQL INJECTION");
        instructions.Should().Contain("REJEITE E AVISE QUE NÃO PODE FAZER ISSO");
    }

    [Fact]
    public void GetPrompt_InstructionsContainLogicalOperatorRule()
    {
        // Arrange
        var options = FilterOponentesRepLegalTXT.GetOptions();
        // Act
        var(prompt, instructions) = FilterOponentesRepLegalTXT.GetPrompt(new FilterOponentesRepLegal(), options);
        // Assert
        instructions.Should().Contain("logicalOperator");
        instructions.Should().Contain(" AND ");
        instructions.Should().Contain(" OR ");
    }

    [Fact]
    public void GetPrompt_InstructionsExplainWildcardChar()
    {
        // Arrange
        var options = FilterOponentesRepLegalTXT.GetOptions();
        // Act
        var(prompt, instructions) = FilterOponentesRepLegalTXT.GetPrompt(new FilterOponentesRepLegal(), options);
        // Assert
        instructions.Should().Contain("wildcardChar");
    }

    [Fact]
    public void GetPrompt_WithMinValueFields_SerializesAsMinValue()
    {
        // Arrange
        var options = FilterOponentesRepLegalTXT.GetOptions();
        var filter = new FilterOponentesRepLegal
        {
            Codigo_filtro = int.MinValue
        };
        // Act
        var(prompt, instructions) = FilterOponentesRepLegalTXT.GetPrompt(filter, options);
        // Assert
        prompt.Should().Contain(int.MinValue.ToString());
    }

    [Theory]
    [InlineData(" AND ")]
    [InlineData(" OR ")]
    public void GetPrompt_WithDifferentLogicalOperators_SerializesCorrectly(string logicalOperator)
    {
        // Arrange
        var options = FilterOponentesRepLegalTXT.GetOptions();
        var filter = new FilterOponentesRepLegal
        {
            LogicalOperator = logicalOperator
        };
        // Act
        var(prompt, instructions) = FilterOponentesRepLegalTXT.GetPrompt(filter, options);
        // Assert
        prompt.Should().Contain("\"logicalOperator\"");
        prompt.Should().Contain(logicalOperator);
    }

    [Theory]
    [InlineData('%')]
    [InlineData('\0')]
    public void GetPrompt_WithDifferentWildcardChars_SerializesCorrectly(char wildcardChar)
    {
        // Arrange
        var options = FilterOponentesRepLegalTXT.GetOptions();
        var filter = new FilterOponentesRepLegal
        {
            WildcardChar = wildcardChar
        };
        // Act
        var(prompt, instructions) = FilterOponentesRepLegalTXT.GetPrompt(filter, options);
        // Assert
        prompt.Should().Contain("\"wildcardChar\"");
    }
}